// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package grpc

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	"go.gmountie.dev/gmountie/pkg/client/grpc"
	"go.gmountie.dev/gmountie/pkg/proto"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return(err error) *MockClient_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Connect provides a mock function for the type MockClient
func (_mock *MockClient) Connect() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Connect")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Connect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Connect'
type MockClient_Connect_Call struct {
	*mock.Call
}

// Connect is a helper method to define mock.On call
func (_e *MockClient_Expecter) Connect() *MockClient_Connect_Call {
	return &MockClient_Connect_Call{Call: _e.mock.On("Connect")}
}

func (_c *MockClient_Connect_Call) Run(run func()) *MockClient_Connect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Connect_Call) Return(err error) *MockClient_Connect_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Connect_Call) RunAndReturn(run func() error) *MockClient_Connect_Call {
	_c.Call.Return(run)
	return _c
}

// File provides a mock function for the type MockClient
func (_mock *MockClient) File() proto.RpcFileClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for File")
	}

	var r0 proto.RpcFileClient
	if returnFunc, ok := ret.Get(0).(func() proto.RpcFileClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.RpcFileClient)
		}
	}
	return r0
}

// MockClient_File_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'File'
type MockClient_File_Call struct {
	*mock.Call
}

// File is a helper method to define mock.On call
func (_e *MockClient_Expecter) File() *MockClient_File_Call {
	return &MockClient_File_Call{Call: _e.mock.On("File")}
}

func (_c *MockClient_File_Call) Run(run func()) *MockClient_File_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_File_Call) Return(rpcFileClient proto.RpcFileClient) *MockClient_File_Call {
	_c.Call.Return(rpcFileClient)
	return _c
}

func (_c *MockClient_File_Call) RunAndReturn(run func() proto.RpcFileClient) *MockClient_File_Call {
	_c.Call.Return(run)
	return _c
}

// Fs provides a mock function for the type MockClient
func (_mock *MockClient) Fs() proto.RpcFsClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fs")
	}

	var r0 proto.RpcFsClient
	if returnFunc, ok := ret.Get(0).(func() proto.RpcFsClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.RpcFsClient)
		}
	}
	return r0
}

// MockClient_Fs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fs'
type MockClient_Fs_Call struct {
	*mock.Call
}

// Fs is a helper method to define mock.On call
func (_e *MockClient_Expecter) Fs() *MockClient_Fs_Call {
	return &MockClient_Fs_Call{Call: _e.mock.On("Fs")}
}

func (_c *MockClient_Fs_Call) Run(run func()) *MockClient_Fs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Fs_Call) Return(rpcFsClient proto.RpcFsClient) *MockClient_Fs_Call {
	_c.Call.Return(rpcFsClient)
	return _c
}

func (_c *MockClient_Fs_Call) RunAndReturn(run func() proto.RpcFsClient) *MockClient_Fs_Call {
	_c.Call.Return(run)
	return _c
}

// GetEndpoint provides a mock function for the type MockClient
func (_mock *MockClient) GetEndpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEndpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_GetEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEndpoint'
type MockClient_GetEndpoint_Call struct {
	*mock.Call
}

// GetEndpoint is a helper method to define mock.On call
func (_e *MockClient_Expecter) GetEndpoint() *MockClient_GetEndpoint_Call {
	return &MockClient_GetEndpoint_Call{Call: _e.mock.On("GetEndpoint")}
}

func (_c *MockClient_GetEndpoint_Call) Run(run func()) *MockClient_GetEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_GetEndpoint_Call) Return(s string) *MockClient_GetEndpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_GetEndpoint_Call) RunAndReturn(run func() string) *MockClient_GetEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// IOTimeout provides a mock function for the type MockClient
func (_mock *MockClient) IOTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IOTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockClient_IOTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IOTimeout'
type MockClient_IOTimeout_Call struct {
	*mock.Call
}

// IOTimeout is a helper method to define mock.On call
func (_e *MockClient_Expecter) IOTimeout() *MockClient_IOTimeout_Call {
	return &MockClient_IOTimeout_Call{Call: _e.mock.On("IOTimeout")}
}

func (_c *MockClient_IOTimeout_Call) Run(run func()) *MockClient_IOTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_IOTimeout_Call) Return(duration time.Duration) *MockClient_IOTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockClient_IOTimeout_Call) RunAndReturn(run func() time.Duration) *MockClient_IOTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// Lifetime provides a mock function for the type MockClient
func (_mock *MockClient) Lifetime() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Lifetime")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockClient_Lifetime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lifetime'
type MockClient_Lifetime_Call struct {
	*mock.Call
}

// Lifetime is a helper method to define mock.On call
func (_e *MockClient_Expecter) Lifetime() *MockClient_Lifetime_Call {
	return &MockClient_Lifetime_Call{Call: _e.mock.On("Lifetime")}
}

func (_c *MockClient_Lifetime_Call) Run(run func()) *MockClient_Lifetime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Lifetime_Call) Return(context1 context.Context) *MockClient_Lifetime_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockClient_Lifetime_Call) RunAndReturn(run func() context.Context) *MockClient_Lifetime_Call {
	_c.Call.Return(run)
	return _c
}

// MetaTimeout provides a mock function for the type MockClient
func (_mock *MockClient) MetaTimeout() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MetaTimeout")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockClient_MetaTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MetaTimeout'
type MockClient_MetaTimeout_Call struct {
	*mock.Call
}

// MetaTimeout is a helper method to define mock.On call
func (_e *MockClient_Expecter) MetaTimeout() *MockClient_MetaTimeout_Call {
	return &MockClient_MetaTimeout_Call{Call: _e.mock.On("MetaTimeout")}
}

func (_c *MockClient_MetaTimeout_Call) Run(run func()) *MockClient_MetaTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_MetaTimeout_Call) Return(duration time.Duration) *MockClient_MetaTimeout_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockClient_MetaTimeout_Call) RunAndReturn(run func() time.Duration) *MockClient_MetaTimeout_Call {
	_c.Call.Return(run)
	return _c
}

// PerFileConfig provides a mock function for the type MockClient
func (_mock *MockClient) PerFileConfig() grpc.PerFileConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PerFileConfig")
	}

	var r0 grpc.PerFileConfig
	if returnFunc, ok := ret.Get(0).(func() grpc.PerFileConfig); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(grpc.PerFileConfig)
	}
	return r0
}

// MockClient_PerFileConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PerFileConfig'
type MockClient_PerFileConfig_Call struct {
	*mock.Call
}

// PerFileConfig is a helper method to define mock.On call
func (_e *MockClient_Expecter) PerFileConfig() *MockClient_PerFileConfig_Call {
	return &MockClient_PerFileConfig_Call{Call: _e.mock.On("PerFileConfig")}
}

func (_c *MockClient_PerFileConfig_Call) Run(run func()) *MockClient_PerFileConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_PerFileConfig_Call) Return(perFileConfig grpc.PerFileConfig) *MockClient_PerFileConfig_Call {
	_c.Call.Return(perFileConfig)
	return _c
}

func (_c *MockClient_PerFileConfig_Call) RunAndReturn(run func() grpc.PerFileConfig) *MockClient_PerFileConfig_Call {
	_c.Call.Return(run)
	return _c
}

// RetryWindow provides a mock function for the type MockClient
func (_mock *MockClient) RetryWindow() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RetryWindow")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockClient_RetryWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetryWindow'
type MockClient_RetryWindow_Call struct {
	*mock.Call
}

// RetryWindow is a helper method to define mock.On call
func (_e *MockClient_Expecter) RetryWindow() *MockClient_RetryWindow_Call {
	return &MockClient_RetryWindow_Call{Call: _e.mock.On("RetryWindow")}
}

func (_c *MockClient_RetryWindow_Call) Run(run func()) *MockClient_RetryWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_RetryWindow_Call) Return(duration time.Duration) *MockClient_RetryWindow_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockClient_RetryWindow_Call) RunAndReturn(run func() time.Duration) *MockClient_RetryWindow_Call {
	_c.Call.Return(run)
	return _c
}

// SessionID provides a mock function for the type MockClient
func (_mock *MockClient) SessionID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SessionID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockClient_SessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SessionID'
type MockClient_SessionID_Call struct {
	*mock.Call
}

// SessionID is a helper method to define mock.On call
func (_e *MockClient_Expecter) SessionID() *MockClient_SessionID_Call {
	return &MockClient_SessionID_Call{Call: _e.mock.On("SessionID")}
}

func (_c *MockClient_SessionID_Call) Run(run func()) *MockClient_SessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_SessionID_Call) Return(s string) *MockClient_SessionID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockClient_SessionID_Call) RunAndReturn(run func() string) *MockClient_SessionID_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockClient
func (_mock *MockClient) Version() proto.VersionServiceClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 proto.VersionServiceClient
	if returnFunc, ok := ret.Get(0).(func() proto.VersionServiceClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.VersionServiceClient)
		}
	}
	return r0
}

// MockClient_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockClient_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockClient_Expecter) Version() *MockClient_Version_Call {
	return &MockClient_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockClient_Version_Call) Run(run func()) *MockClient_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Version_Call) Return(versionServiceClient proto.VersionServiceClient) *MockClient_Version_Call {
	_c.Call.Return(versionServiceClient)
	return _c
}

func (_c *MockClient_Version_Call) RunAndReturn(run func() proto.VersionServiceClient) *MockClient_Version_Call {
	_c.Call.Return(run)
	return _c
}

// Volume provides a mock function for the type MockClient
func (_mock *MockClient) Volume() proto.VolumeServiceClient {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Volume")
	}

	var r0 proto.VolumeServiceClient
	if returnFunc, ok := ret.Get(0).(func() proto.VolumeServiceClient); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(proto.VolumeServiceClient)
		}
	}
	return r0
}

// MockClient_Volume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Volume'
type MockClient_Volume_Call struct {
	*mock.Call
}

// Volume is a helper method to define mock.On call
func (_e *MockClient_Expecter) Volume() *MockClient_Volume_Call {
	return &MockClient_Volume_Call{Call: _e.mock.On("Volume")}
}

func (_c *MockClient_Volume_Call) Run(run func()) *MockClient_Volume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Volume_Call) Return(volumeServiceClient proto.VolumeServiceClient) *MockClient_Volume_Call {
	_c.Call.Return(volumeServiceClient)
	return _c
}

func (_c *MockClient_Volume_Call) RunAndReturn(run func() proto.VolumeServiceClient) *MockClient_Volume_Call {
	_c.Call.Return(run)
	return _c
}

// WhoAmI provides a mock function for the type MockClient
func (_mock *MockClient) WhoAmI(ctx context.Context, volume string) (*proto.Identity, error) {
	ret := _mock.Called(ctx, volume)

	if len(ret) == 0 {
		panic("no return value specified for WhoAmI")
	}

	var r0 *proto.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*proto.Identity, error)); ok {
		return returnFunc(ctx, volume)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *proto.Identity); ok {
		r0 = returnFunc(ctx, volume)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, volume)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_WhoAmI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhoAmI'
type MockClient_WhoAmI_Call struct {
	*mock.Call
}

// WhoAmI is a helper method to define mock.On call
//   - ctx context.Context
//   - volume string
func (_e *MockClient_Expecter) WhoAmI(ctx interface{}, volume interface{}) *MockClient_WhoAmI_Call {
	return &MockClient_WhoAmI_Call{Call: _e.mock.On("WhoAmI", ctx, volume)}
}

func (_c *MockClient_WhoAmI_Call) Run(run func(ctx context.Context, volume string)) *MockClient_WhoAmI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_WhoAmI_Call) Return(identity *proto.Identity, err error) *MockClient_WhoAmI_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockClient_WhoAmI_Call) RunAndReturn(run func(ctx context.Context, volume string) (*proto.Identity, error)) *MockClient_WhoAmI_Call {
	_c.Call.Return(run)
	return _c
}
