// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.gmountie.dev/gmountie/pkg/proto"
	"google.golang.org/grpc/metadata"
)

// NewMockRpcFs_ApplyClient creates a new instance of MockRpcFs_ApplyClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcFs_ApplyClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcFs_ApplyClient {
	mock := &MockRpcFs_ApplyClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcFs_ApplyClient is an autogenerated mock type for the RpcFs_ApplyClient type
type MockRpcFs_ApplyClient struct {
	mock.Mock
}

type MockRpcFs_ApplyClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcFs_ApplyClient) EXPECT() *MockRpcFs_ApplyClient_Expecter {
	return &MockRpcFs_ApplyClient_Expecter{mock: &_m.Mock}
}

// CloseAndRecv provides a mock function for the type MockRpcFs_ApplyClient
func (_mock *MockRpcFs_ApplyClient) CloseAndRecv() (*proto.ApplyAck, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseAndRecv")
	}

	var r0 *proto.ApplyAck
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*proto.ApplyAck, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *proto.ApplyAck); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ApplyAck)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFs_ApplyClient_CloseAndRecv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseAndRecv'
type MockRpcFs_ApplyClient_CloseAndRecv_Call struct {
	*mock.Call
}

// CloseAndRecv is a helper method to define mock.On call
func (_e *MockRpcFs_ApplyClient_Expecter) CloseAndRecv() *MockRpcFs_ApplyClient_CloseAndRecv_Call {
	return &MockRpcFs_ApplyClient_CloseAndRecv_Call{Call: _e.mock.On("CloseAndRecv")}
}

func (_c *MockRpcFs_ApplyClient_CloseAndRecv_Call) Run(run func()) *MockRpcFs_ApplyClient_CloseAndRecv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_ApplyClient_CloseAndRecv_Call) Return(applyAck *proto.ApplyAck, err error) *MockRpcFs_ApplyClient_CloseAndRecv_Call {
	_c.Call.Return(applyAck, err)
	return _c
}

func (_c *MockRpcFs_ApplyClient_CloseAndRecv_Call) RunAndReturn(run func() (*proto.ApplyAck, error)) *MockRpcFs_ApplyClient_CloseAndRecv_Call {
	_c.Call.Return(run)
	return _c
}

// CloseSend provides a mock function for the type MockRpcFs_ApplyClient
func (_mock *MockRpcFs_ApplyClient) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ApplyClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockRpcFs_ApplyClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockRpcFs_ApplyClient_Expecter) CloseSend() *MockRpcFs_ApplyClient_CloseSend_Call {
	return &MockRpcFs_ApplyClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *MockRpcFs_ApplyClient_CloseSend_Call) Run(run func()) *MockRpcFs_ApplyClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_ApplyClient_CloseSend_Call) Return(err error) *MockRpcFs_ApplyClient_CloseSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ApplyClient_CloseSend_Call) RunAndReturn(run func() error) *MockRpcFs_ApplyClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockRpcFs_ApplyClient
func (_mock *MockRpcFs_ApplyClient) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockRpcFs_ApplyClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockRpcFs_ApplyClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockRpcFs_ApplyClient_Expecter) Context() *MockRpcFs_ApplyClient_Context_Call {
	return &MockRpcFs_ApplyClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockRpcFs_ApplyClient_Context_Call) Run(run func()) *MockRpcFs_ApplyClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_ApplyClient_Context_Call) Return(context1 context.Context) *MockRpcFs_ApplyClient_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockRpcFs_ApplyClient_Context_Call) RunAndReturn(run func() context.Context) *MockRpcFs_ApplyClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockRpcFs_ApplyClient
func (_mock *MockRpcFs_ApplyClient) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFs_ApplyClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockRpcFs_ApplyClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockRpcFs_ApplyClient_Expecter) Header() *MockRpcFs_ApplyClient_Header_Call {
	return &MockRpcFs_ApplyClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockRpcFs_ApplyClient_Header_Call) Run(run func()) *MockRpcFs_ApplyClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_ApplyClient_Header_Call) Return(mD metadata.MD, err error) *MockRpcFs_ApplyClient_Header_Call {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *MockRpcFs_ApplyClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *MockRpcFs_ApplyClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockRpcFs_ApplyClient
func (_mock *MockRpcFs_ApplyClient) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ApplyClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockRpcFs_ApplyClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFs_ApplyClient_Expecter) RecvMsg(m interface{}) *MockRpcFs_ApplyClient_RecvMsg_Call {
	return &MockRpcFs_ApplyClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockRpcFs_ApplyClient_RecvMsg_Call) Run(run func(m any)) *MockRpcFs_ApplyClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ApplyClient_RecvMsg_Call) Return(err error) *MockRpcFs_ApplyClient_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ApplyClient_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFs_ApplyClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockRpcFs_ApplyClient
func (_mock *MockRpcFs_ApplyClient) Send(walOp *proto.WalOp) error {
	ret := _mock.Called(walOp)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*proto.WalOp) error); ok {
		r0 = returnFunc(walOp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ApplyClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockRpcFs_ApplyClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - walOp *proto.WalOp
func (_e *MockRpcFs_ApplyClient_Expecter) Send(walOp interface{}) *MockRpcFs_ApplyClient_Send_Call {
	return &MockRpcFs_ApplyClient_Send_Call{Call: _e.mock.On("Send", walOp)}
}

func (_c *MockRpcFs_ApplyClient_Send_Call) Run(run func(walOp *proto.WalOp)) *MockRpcFs_ApplyClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *proto.WalOp
		if args[0] != nil {
			arg0 = args[0].(*proto.WalOp)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ApplyClient_Send_Call) Return(err error) *MockRpcFs_ApplyClient_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ApplyClient_Send_Call) RunAndReturn(run func(walOp *proto.WalOp) error) *MockRpcFs_ApplyClient_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockRpcFs_ApplyClient
func (_mock *MockRpcFs_ApplyClient) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ApplyClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockRpcFs_ApplyClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFs_ApplyClient_Expecter) SendMsg(m interface{}) *MockRpcFs_ApplyClient_SendMsg_Call {
	return &MockRpcFs_ApplyClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockRpcFs_ApplyClient_SendMsg_Call) Run(run func(m any)) *MockRpcFs_ApplyClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ApplyClient_SendMsg_Call) Return(err error) *MockRpcFs_ApplyClient_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ApplyClient_SendMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFs_ApplyClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type MockRpcFs_ApplyClient
func (_mock *MockRpcFs_ApplyClient) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// MockRpcFs_ApplyClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockRpcFs_ApplyClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockRpcFs_ApplyClient_Expecter) Trailer() *MockRpcFs_ApplyClient_Trailer_Call {
	return &MockRpcFs_ApplyClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *MockRpcFs_ApplyClient_Trailer_Call) Run(run func()) *MockRpcFs_ApplyClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_ApplyClient_Trailer_Call) Return(mD metadata.MD) *MockRpcFs_ApplyClient_Trailer_Call {
	_c.Call.Return(mD)
	return _c
}

func (_c *MockRpcFs_ApplyClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *MockRpcFs_ApplyClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}
