// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnsafeSessionServiceServer creates a new instance of MockUnsafeSessionServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeSessionServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeSessionServiceServer {
	mock := &MockUnsafeSessionServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsafeSessionServiceServer is an autogenerated mock type for the UnsafeSessionServiceServer type
type MockUnsafeSessionServiceServer struct {
	mock.Mock
}

type MockUnsafeSessionServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeSessionServiceServer) EXPECT() *MockUnsafeSessionServiceServer_Expecter {
	return &MockUnsafeSessionServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedSessionServiceServer provides a mock function for the type MockUnsafeSessionServiceServer
func (_mock *MockUnsafeSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {
	_mock.Called()
	return
}

// MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSessionServiceServer'
type MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSessionServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeSessionServiceServer_Expecter) mustEmbedUnimplementedSessionServiceServer() *MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call {
	return &MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSessionServiceServer")}
}

func (_c *MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call) Run(run func()) *MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call) Return() *MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call) RunAndReturn(run func()) *MockUnsafeSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call {
	_c.Run(run)
	return _c
}
