// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnsafeVolumeServiceServer creates a new instance of MockUnsafeVolumeServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeVolumeServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeVolumeServiceServer {
	mock := &MockUnsafeVolumeServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsafeVolumeServiceServer is an autogenerated mock type for the UnsafeVolumeServiceServer type
type MockUnsafeVolumeServiceServer struct {
	mock.Mock
}

type MockUnsafeVolumeServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeVolumeServiceServer) EXPECT() *MockUnsafeVolumeServiceServer_Expecter {
	return &MockUnsafeVolumeServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedVolumeServiceServer provides a mock function for the type MockUnsafeVolumeServiceServer
func (_mock *MockUnsafeVolumeServiceServer) mustEmbedUnimplementedVolumeServiceServer() {
	_mock.Called()
	return
}

// MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedVolumeServiceServer'
type MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedVolumeServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeVolumeServiceServer_Expecter) mustEmbedUnimplementedVolumeServiceServer() *MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	return &MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedVolumeServiceServer")}
}

func (_c *MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) Run(run func()) *MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) Return() *MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call) RunAndReturn(run func()) *MockUnsafeVolumeServiceServer_mustEmbedUnimplementedVolumeServiceServer_Call {
	_c.Run(run)
	return _c
}
