// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"
	"go.gmountie.dev/gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockSessionServiceServer creates a new instance of MockSessionServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionServiceServer {
	mock := &MockSessionServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionServiceServer is an autogenerated mock type for the SessionServiceServer type
type MockSessionServiceServer struct {
	mock.Mock
}

type MockSessionServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionServiceServer) EXPECT() *MockSessionServiceServer_Expecter {
	return &MockSessionServiceServer_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionServiceServer
func (_mock *MockSessionServiceServer) Create(context1 context.Context, sessionCreateRequest *proto.SessionCreateRequest) (*proto.SessionCreateReply, error) {
	ret := _mock.Called(context1, sessionCreateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *proto.SessionCreateReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SessionCreateRequest) (*proto.SessionCreateReply, error)); ok {
		return returnFunc(context1, sessionCreateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SessionCreateRequest) *proto.SessionCreateReply); ok {
		r0 = returnFunc(context1, sessionCreateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SessionCreateReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.SessionCreateRequest) error); ok {
		r1 = returnFunc(context1, sessionCreateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionServiceServer_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionServiceServer_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - sessionCreateRequest *proto.SessionCreateRequest
func (_e *MockSessionServiceServer_Expecter) Create(context1 interface{}, sessionCreateRequest interface{}) *MockSessionServiceServer_Create_Call {
	return &MockSessionServiceServer_Create_Call{Call: _e.mock.On("Create", context1, sessionCreateRequest)}
}

func (_c *MockSessionServiceServer_Create_Call) Run(run func(context1 context.Context, sessionCreateRequest *proto.SessionCreateRequest)) *MockSessionServiceServer_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.SessionCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.SessionCreateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionServiceServer_Create_Call) Return(sessionCreateReply *proto.SessionCreateReply, err error) *MockSessionServiceServer_Create_Call {
	_c.Call.Return(sessionCreateReply, err)
	return _c
}

func (_c *MockSessionServiceServer_Create_Call) RunAndReturn(run func(context1 context.Context, sessionCreateRequest *proto.SessionCreateRequest) (*proto.SessionCreateReply, error)) *MockSessionServiceServer_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Keepalive provides a mock function for the type MockSessionServiceServer
func (_mock *MockSessionServiceServer) Keepalive(keepaliveRequest *proto.KeepaliveRequest, serverStreamingServer grpc.ServerStreamingServer[proto.KeepalivePing]) error {
	ret := _mock.Called(keepaliveRequest, serverStreamingServer)

	if len(ret) == 0 {
		panic("no return value specified for Keepalive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*proto.KeepaliveRequest, grpc.ServerStreamingServer[proto.KeepalivePing]) error); ok {
		r0 = returnFunc(keepaliveRequest, serverStreamingServer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionServiceServer_Keepalive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keepalive'
type MockSessionServiceServer_Keepalive_Call struct {
	*mock.Call
}

// Keepalive is a helper method to define mock.On call
//   - keepaliveRequest *proto.KeepaliveRequest
//   - serverStreamingServer grpc.ServerStreamingServer[proto.KeepalivePing]
func (_e *MockSessionServiceServer_Expecter) Keepalive(keepaliveRequest interface{}, serverStreamingServer interface{}) *MockSessionServiceServer_Keepalive_Call {
	return &MockSessionServiceServer_Keepalive_Call{Call: _e.mock.On("Keepalive", keepaliveRequest, serverStreamingServer)}
}

func (_c *MockSessionServiceServer_Keepalive_Call) Run(run func(keepaliveRequest *proto.KeepaliveRequest, serverStreamingServer grpc.ServerStreamingServer[proto.KeepalivePing])) *MockSessionServiceServer_Keepalive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *proto.KeepaliveRequest
		if args[0] != nil {
			arg0 = args[0].(*proto.KeepaliveRequest)
		}
		var arg1 grpc.ServerStreamingServer[proto.KeepalivePing]
		if args[1] != nil {
			arg1 = args[1].(grpc.ServerStreamingServer[proto.KeepalivePing])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionServiceServer_Keepalive_Call) Return(err error) *MockSessionServiceServer_Keepalive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionServiceServer_Keepalive_Call) RunAndReturn(run func(keepaliveRequest *proto.KeepaliveRequest, serverStreamingServer grpc.ServerStreamingServer[proto.KeepalivePing]) error) *MockSessionServiceServer_Keepalive_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockSessionServiceServer
func (_mock *MockSessionServiceServer) Resume(context1 context.Context, sessionResumeRequest *proto.SessionResumeRequest) (*proto.SessionResumeReply, error) {
	ret := _mock.Called(context1, sessionResumeRequest)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 *proto.SessionResumeReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SessionResumeRequest) (*proto.SessionResumeReply, error)); ok {
		return returnFunc(context1, sessionResumeRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SessionResumeRequest) *proto.SessionResumeReply); ok {
		r0 = returnFunc(context1, sessionResumeRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SessionResumeReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.SessionResumeRequest) error); ok {
		r1 = returnFunc(context1, sessionResumeRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionServiceServer_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockSessionServiceServer_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - context1 context.Context
//   - sessionResumeRequest *proto.SessionResumeRequest
func (_e *MockSessionServiceServer_Expecter) Resume(context1 interface{}, sessionResumeRequest interface{}) *MockSessionServiceServer_Resume_Call {
	return &MockSessionServiceServer_Resume_Call{Call: _e.mock.On("Resume", context1, sessionResumeRequest)}
}

func (_c *MockSessionServiceServer_Resume_Call) Run(run func(context1 context.Context, sessionResumeRequest *proto.SessionResumeRequest)) *MockSessionServiceServer_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.SessionResumeRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.SessionResumeRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionServiceServer_Resume_Call) Return(sessionResumeReply *proto.SessionResumeReply, err error) *MockSessionServiceServer_Resume_Call {
	_c.Call.Return(sessionResumeReply, err)
	return _c
}

func (_c *MockSessionServiceServer_Resume_Call) RunAndReturn(run func(context1 context.Context, sessionResumeRequest *proto.SessionResumeRequest) (*proto.SessionResumeReply, error)) *MockSessionServiceServer_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// WhoAmI provides a mock function for the type MockSessionServiceServer
func (_mock *MockSessionServiceServer) WhoAmI(context1 context.Context, whoAmIRequest *proto.WhoAmIRequest) (*proto.Identity, error) {
	ret := _mock.Called(context1, whoAmIRequest)

	if len(ret) == 0 {
		panic("no return value specified for WhoAmI")
	}

	var r0 *proto.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.WhoAmIRequest) (*proto.Identity, error)); ok {
		return returnFunc(context1, whoAmIRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.WhoAmIRequest) *proto.Identity); ok {
		r0 = returnFunc(context1, whoAmIRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.WhoAmIRequest) error); ok {
		r1 = returnFunc(context1, whoAmIRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionServiceServer_WhoAmI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhoAmI'
type MockSessionServiceServer_WhoAmI_Call struct {
	*mock.Call
}

// WhoAmI is a helper method to define mock.On call
//   - context1 context.Context
//   - whoAmIRequest *proto.WhoAmIRequest
func (_e *MockSessionServiceServer_Expecter) WhoAmI(context1 interface{}, whoAmIRequest interface{}) *MockSessionServiceServer_WhoAmI_Call {
	return &MockSessionServiceServer_WhoAmI_Call{Call: _e.mock.On("WhoAmI", context1, whoAmIRequest)}
}

func (_c *MockSessionServiceServer_WhoAmI_Call) Run(run func(context1 context.Context, whoAmIRequest *proto.WhoAmIRequest)) *MockSessionServiceServer_WhoAmI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.WhoAmIRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.WhoAmIRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionServiceServer_WhoAmI_Call) Return(identity *proto.Identity, err error) *MockSessionServiceServer_WhoAmI_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockSessionServiceServer_WhoAmI_Call) RunAndReturn(run func(context1 context.Context, whoAmIRequest *proto.WhoAmIRequest) (*proto.Identity, error)) *MockSessionServiceServer_WhoAmI_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedSessionServiceServer provides a mock function for the type MockSessionServiceServer
func (_mock *MockSessionServiceServer) mustEmbedUnimplementedSessionServiceServer() {
	_mock.Called()
	return
}

// MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedSessionServiceServer'
type MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedSessionServiceServer is a helper method to define mock.On call
func (_e *MockSessionServiceServer_Expecter) mustEmbedUnimplementedSessionServiceServer() *MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call {
	return &MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedSessionServiceServer")}
}

func (_c *MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call) Run(run func()) *MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call) Return() *MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call) RunAndReturn(run func()) *MockSessionServiceServer_mustEmbedUnimplementedSessionServiceServer_Call {
	_c.Run(run)
	return _c
}
