// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"
	"gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockVersionServiceClient creates a new instance of MockVersionServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionServiceClient {
	mock := &MockVersionServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersionServiceClient is an autogenerated mock type for the VersionServiceClient type
type MockVersionServiceClient struct {
	mock.Mock
}

type MockVersionServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionServiceClient) EXPECT() *MockVersionServiceClient_Expecter {
	return &MockVersionServiceClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockVersionServiceClient
func (_mock *MockVersionServiceClient) Get(ctx context.Context, in *proto.VersionRequest, opts ...grpc.CallOption) (*proto.VersionReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *proto.VersionReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.VersionRequest, ...grpc.CallOption) (*proto.VersionReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.VersionRequest, ...grpc.CallOption) *proto.VersionReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.VersionReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.VersionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockVersionServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.VersionRequest
//   - opts ...grpc.CallOption
func (_e *MockVersionServiceClient_Expecter) Get(ctx interface{}, in interface{}, opts ...interface{}) *MockVersionServiceClient_Get_Call {
	return &MockVersionServiceClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockVersionServiceClient_Get_Call) Run(run func(ctx context.Context, in *proto.VersionRequest, opts ...grpc.CallOption)) *MockVersionServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.VersionRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.VersionRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVersionServiceClient_Get_Call) Return(versionReply *proto.VersionReply, err error) *MockVersionServiceClient_Get_Call {
	_c.Call.Return(versionReply, err)
	return _c
}

func (_c *MockVersionServiceClient_Get_Call) RunAndReturn(run func(ctx context.Context, in *proto.VersionRequest, opts ...grpc.CallOption) (*proto.VersionReply, error)) *MockVersionServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}
