// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"
	"go.gmountie.dev/gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockRpcFs_SubscribeServer creates a new instance of MockRpcFs_SubscribeServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcFs_SubscribeServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcFs_SubscribeServer {
	mock := &MockRpcFs_SubscribeServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcFs_SubscribeServer is an autogenerated mock type for the RpcFs_SubscribeServer type
type MockRpcFs_SubscribeServer struct {
	mock.Mock
}

type MockRpcFs_SubscribeServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcFs_SubscribeServer) EXPECT() *MockRpcFs_SubscribeServer_Expecter {
	return &MockRpcFs_SubscribeServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockRpcFs_SubscribeServer
func (_mock *MockRpcFs_SubscribeServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockRpcFs_SubscribeServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockRpcFs_SubscribeServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockRpcFs_SubscribeServer_Expecter) Context() *MockRpcFs_SubscribeServer_Context_Call {
	return &MockRpcFs_SubscribeServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockRpcFs_SubscribeServer_Context_Call) Run(run func()) *MockRpcFs_SubscribeServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_SubscribeServer_Context_Call) Return(context1 context.Context) *MockRpcFs_SubscribeServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockRpcFs_SubscribeServer_Context_Call) RunAndReturn(run func() context.Context) *MockRpcFs_SubscribeServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockRpcFs_SubscribeServer
func (_mock *MockRpcFs_SubscribeServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_SubscribeServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockRpcFs_SubscribeServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFs_SubscribeServer_Expecter) RecvMsg(m interface{}) *MockRpcFs_SubscribeServer_RecvMsg_Call {
	return &MockRpcFs_SubscribeServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockRpcFs_SubscribeServer_RecvMsg_Call) Run(run func(m any)) *MockRpcFs_SubscribeServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_SubscribeServer_RecvMsg_Call) Return(err error) *MockRpcFs_SubscribeServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_SubscribeServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFs_SubscribeServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockRpcFs_SubscribeServer
func (_mock *MockRpcFs_SubscribeServer) Send(subscribeEvent *proto.SubscribeEvent) error {
	ret := _mock.Called(subscribeEvent)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*proto.SubscribeEvent) error); ok {
		r0 = returnFunc(subscribeEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_SubscribeServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockRpcFs_SubscribeServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - subscribeEvent *proto.SubscribeEvent
func (_e *MockRpcFs_SubscribeServer_Expecter) Send(subscribeEvent interface{}) *MockRpcFs_SubscribeServer_Send_Call {
	return &MockRpcFs_SubscribeServer_Send_Call{Call: _e.mock.On("Send", subscribeEvent)}
}

func (_c *MockRpcFs_SubscribeServer_Send_Call) Run(run func(subscribeEvent *proto.SubscribeEvent)) *MockRpcFs_SubscribeServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *proto.SubscribeEvent
		if args[0] != nil {
			arg0 = args[0].(*proto.SubscribeEvent)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_SubscribeServer_Send_Call) Return(err error) *MockRpcFs_SubscribeServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_SubscribeServer_Send_Call) RunAndReturn(run func(subscribeEvent *proto.SubscribeEvent) error) *MockRpcFs_SubscribeServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockRpcFs_SubscribeServer
func (_mock *MockRpcFs_SubscribeServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_SubscribeServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockRpcFs_SubscribeServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFs_SubscribeServer_Expecter) SendHeader(mD interface{}) *MockRpcFs_SubscribeServer_SendHeader_Call {
	return &MockRpcFs_SubscribeServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockRpcFs_SubscribeServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockRpcFs_SubscribeServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_SubscribeServer_SendHeader_Call) Return(err error) *MockRpcFs_SubscribeServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_SubscribeServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockRpcFs_SubscribeServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockRpcFs_SubscribeServer
func (_mock *MockRpcFs_SubscribeServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_SubscribeServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockRpcFs_SubscribeServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFs_SubscribeServer_Expecter) SendMsg(m interface{}) *MockRpcFs_SubscribeServer_SendMsg_Call {
	return &MockRpcFs_SubscribeServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockRpcFs_SubscribeServer_SendMsg_Call) Run(run func(m any)) *MockRpcFs_SubscribeServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_SubscribeServer_SendMsg_Call) Return(err error) *MockRpcFs_SubscribeServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_SubscribeServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFs_SubscribeServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockRpcFs_SubscribeServer
func (_mock *MockRpcFs_SubscribeServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_SubscribeServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockRpcFs_SubscribeServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFs_SubscribeServer_Expecter) SetHeader(mD interface{}) *MockRpcFs_SubscribeServer_SetHeader_Call {
	return &MockRpcFs_SubscribeServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockRpcFs_SubscribeServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockRpcFs_SubscribeServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_SubscribeServer_SetHeader_Call) Return(err error) *MockRpcFs_SubscribeServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_SubscribeServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockRpcFs_SubscribeServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockRpcFs_SubscribeServer
func (_mock *MockRpcFs_SubscribeServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockRpcFs_SubscribeServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockRpcFs_SubscribeServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFs_SubscribeServer_Expecter) SetTrailer(mD interface{}) *MockRpcFs_SubscribeServer_SetTrailer_Call {
	return &MockRpcFs_SubscribeServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockRpcFs_SubscribeServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockRpcFs_SubscribeServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_SubscribeServer_SetTrailer_Call) Return() *MockRpcFs_SubscribeServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRpcFs_SubscribeServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockRpcFs_SubscribeServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
