// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"
	"go.gmountie.dev/gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockRpcFs_SubscribeClient creates a new instance of MockRpcFs_SubscribeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcFs_SubscribeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcFs_SubscribeClient {
	mock := &MockRpcFs_SubscribeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcFs_SubscribeClient is an autogenerated mock type for the RpcFs_SubscribeClient type
type MockRpcFs_SubscribeClient struct {
	mock.Mock
}

type MockRpcFs_SubscribeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcFs_SubscribeClient) EXPECT() *MockRpcFs_SubscribeClient_Expecter {
	return &MockRpcFs_SubscribeClient_Expecter{mock: &_m.Mock}
}

// CloseSend provides a mock function for the type MockRpcFs_SubscribeClient
func (_mock *MockRpcFs_SubscribeClient) CloseSend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CloseSend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_SubscribeClient_CloseSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CloseSend'
type MockRpcFs_SubscribeClient_CloseSend_Call struct {
	*mock.Call
}

// CloseSend is a helper method to define mock.On call
func (_e *MockRpcFs_SubscribeClient_Expecter) CloseSend() *MockRpcFs_SubscribeClient_CloseSend_Call {
	return &MockRpcFs_SubscribeClient_CloseSend_Call{Call: _e.mock.On("CloseSend")}
}

func (_c *MockRpcFs_SubscribeClient_CloseSend_Call) Run(run func()) *MockRpcFs_SubscribeClient_CloseSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_SubscribeClient_CloseSend_Call) Return(err error) *MockRpcFs_SubscribeClient_CloseSend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_SubscribeClient_CloseSend_Call) RunAndReturn(run func() error) *MockRpcFs_SubscribeClient_CloseSend_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockRpcFs_SubscribeClient
func (_mock *MockRpcFs_SubscribeClient) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockRpcFs_SubscribeClient_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockRpcFs_SubscribeClient_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockRpcFs_SubscribeClient_Expecter) Context() *MockRpcFs_SubscribeClient_Context_Call {
	return &MockRpcFs_SubscribeClient_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockRpcFs_SubscribeClient_Context_Call) Run(run func()) *MockRpcFs_SubscribeClient_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_SubscribeClient_Context_Call) Return(context1 context.Context) *MockRpcFs_SubscribeClient_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockRpcFs_SubscribeClient_Context_Call) RunAndReturn(run func() context.Context) *MockRpcFs_SubscribeClient_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Header provides a mock function for the type MockRpcFs_SubscribeClient
func (_mock *MockRpcFs_SubscribeClient) Header() (metadata.MD, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Header")
	}

	var r0 metadata.MD
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (metadata.MD, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFs_SubscribeClient_Header_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Header'
type MockRpcFs_SubscribeClient_Header_Call struct {
	*mock.Call
}

// Header is a helper method to define mock.On call
func (_e *MockRpcFs_SubscribeClient_Expecter) Header() *MockRpcFs_SubscribeClient_Header_Call {
	return &MockRpcFs_SubscribeClient_Header_Call{Call: _e.mock.On("Header")}
}

func (_c *MockRpcFs_SubscribeClient_Header_Call) Run(run func()) *MockRpcFs_SubscribeClient_Header_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_SubscribeClient_Header_Call) Return(mD metadata.MD, err error) *MockRpcFs_SubscribeClient_Header_Call {
	_c.Call.Return(mD, err)
	return _c
}

func (_c *MockRpcFs_SubscribeClient_Header_Call) RunAndReturn(run func() (metadata.MD, error)) *MockRpcFs_SubscribeClient_Header_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type MockRpcFs_SubscribeClient
func (_mock *MockRpcFs_SubscribeClient) Recv() (*proto.SubscribeEvent, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *proto.SubscribeEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*proto.SubscribeEvent, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *proto.SubscribeEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SubscribeEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFs_SubscribeClient_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockRpcFs_SubscribeClient_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockRpcFs_SubscribeClient_Expecter) Recv() *MockRpcFs_SubscribeClient_Recv_Call {
	return &MockRpcFs_SubscribeClient_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockRpcFs_SubscribeClient_Recv_Call) Run(run func()) *MockRpcFs_SubscribeClient_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_SubscribeClient_Recv_Call) Return(subscribeEvent *proto.SubscribeEvent, err error) *MockRpcFs_SubscribeClient_Recv_Call {
	_c.Call.Return(subscribeEvent, err)
	return _c
}

func (_c *MockRpcFs_SubscribeClient_Recv_Call) RunAndReturn(run func() (*proto.SubscribeEvent, error)) *MockRpcFs_SubscribeClient_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockRpcFs_SubscribeClient
func (_mock *MockRpcFs_SubscribeClient) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_SubscribeClient_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockRpcFs_SubscribeClient_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFs_SubscribeClient_Expecter) RecvMsg(m interface{}) *MockRpcFs_SubscribeClient_RecvMsg_Call {
	return &MockRpcFs_SubscribeClient_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockRpcFs_SubscribeClient_RecvMsg_Call) Run(run func(m any)) *MockRpcFs_SubscribeClient_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_SubscribeClient_RecvMsg_Call) Return(err error) *MockRpcFs_SubscribeClient_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_SubscribeClient_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFs_SubscribeClient_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockRpcFs_SubscribeClient
func (_mock *MockRpcFs_SubscribeClient) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_SubscribeClient_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockRpcFs_SubscribeClient_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFs_SubscribeClient_Expecter) SendMsg(m interface{}) *MockRpcFs_SubscribeClient_SendMsg_Call {
	return &MockRpcFs_SubscribeClient_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockRpcFs_SubscribeClient_SendMsg_Call) Run(run func(m any)) *MockRpcFs_SubscribeClient_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_SubscribeClient_SendMsg_Call) Return(err error) *MockRpcFs_SubscribeClient_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_SubscribeClient_SendMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFs_SubscribeClient_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Trailer provides a mock function for the type MockRpcFs_SubscribeClient
func (_mock *MockRpcFs_SubscribeClient) Trailer() metadata.MD {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Trailer")
	}

	var r0 metadata.MD
	if returnFunc, ok := ret.Get(0).(func() metadata.MD); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata.MD)
		}
	}
	return r0
}

// MockRpcFs_SubscribeClient_Trailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Trailer'
type MockRpcFs_SubscribeClient_Trailer_Call struct {
	*mock.Call
}

// Trailer is a helper method to define mock.On call
func (_e *MockRpcFs_SubscribeClient_Expecter) Trailer() *MockRpcFs_SubscribeClient_Trailer_Call {
	return &MockRpcFs_SubscribeClient_Trailer_Call{Call: _e.mock.On("Trailer")}
}

func (_c *MockRpcFs_SubscribeClient_Trailer_Call) Run(run func()) *MockRpcFs_SubscribeClient_Trailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_SubscribeClient_Trailer_Call) Return(mD metadata.MD) *MockRpcFs_SubscribeClient_Trailer_Call {
	_c.Call.Return(mD)
	return _c
}

func (_c *MockRpcFs_SubscribeClient_Trailer_Call) RunAndReturn(run func() metadata.MD) *MockRpcFs_SubscribeClient_Trailer_Call {
	_c.Call.Return(run)
	return _c
}
