// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"
	"gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRpcFsServer creates a new instance of MockRpcFsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcFsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcFsServer {
	mock := &MockRpcFsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcFsServer is an autogenerated mock type for the RpcFsServer type
type MockRpcFsServer struct {
	mock.Mock
}

type MockRpcFsServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcFsServer) EXPECT() *MockRpcFsServer_Expecter {
	return &MockRpcFsServer_Expecter{mock: &_m.Mock}
}

// Access provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) Access(context1 context.Context, accessRequest *proto.AccessRequest) (*proto.AccessReply, error) {
	ret := _mock.Called(context1, accessRequest)

	if len(ret) == 0 {
		panic("no return value specified for Access")
	}

	var r0 *proto.AccessReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.AccessRequest) (*proto.AccessReply, error)); ok {
		return returnFunc(context1, accessRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.AccessRequest) *proto.AccessReply); ok {
		r0 = returnFunc(context1, accessRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.AccessReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.AccessRequest) error); ok {
		r1 = returnFunc(context1, accessRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_Access_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Access'
type MockRpcFsServer_Access_Call struct {
	*mock.Call
}

// Access is a helper method to define mock.On call
//   - context1 context.Context
//   - accessRequest *proto.AccessRequest
func (_e *MockRpcFsServer_Expecter) Access(context1 interface{}, accessRequest interface{}) *MockRpcFsServer_Access_Call {
	return &MockRpcFsServer_Access_Call{Call: _e.mock.On("Access", context1, accessRequest)}
}

func (_c *MockRpcFsServer_Access_Call) Run(run func(context1 context.Context, accessRequest *proto.AccessRequest)) *MockRpcFsServer_Access_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.AccessRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.AccessRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_Access_Call) Return(accessReply *proto.AccessReply, err error) *MockRpcFsServer_Access_Call {
	_c.Call.Return(accessReply, err)
	return _c
}

func (_c *MockRpcFsServer_Access_Call) RunAndReturn(run func(context1 context.Context, accessRequest *proto.AccessRequest) (*proto.AccessReply, error)) *MockRpcFsServer_Access_Call {
	_c.Call.Return(run)
	return _c
}

// Chmod provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) Chmod(context1 context.Context, chmodRequest *proto.ChmodRequest) (*proto.ChmodReply, error) {
	ret := _mock.Called(context1, chmodRequest)

	if len(ret) == 0 {
		panic("no return value specified for Chmod")
	}

	var r0 *proto.ChmodReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.ChmodRequest) (*proto.ChmodReply, error)); ok {
		return returnFunc(context1, chmodRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.ChmodRequest) *proto.ChmodReply); ok {
		r0 = returnFunc(context1, chmodRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ChmodReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.ChmodRequest) error); ok {
		r1 = returnFunc(context1, chmodRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_Chmod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chmod'
type MockRpcFsServer_Chmod_Call struct {
	*mock.Call
}

// Chmod is a helper method to define mock.On call
//   - context1 context.Context
//   - chmodRequest *proto.ChmodRequest
func (_e *MockRpcFsServer_Expecter) Chmod(context1 interface{}, chmodRequest interface{}) *MockRpcFsServer_Chmod_Call {
	return &MockRpcFsServer_Chmod_Call{Call: _e.mock.On("Chmod", context1, chmodRequest)}
}

func (_c *MockRpcFsServer_Chmod_Call) Run(run func(context1 context.Context, chmodRequest *proto.ChmodRequest)) *MockRpcFsServer_Chmod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.ChmodRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.ChmodRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_Chmod_Call) Return(chmodReply *proto.ChmodReply, err error) *MockRpcFsServer_Chmod_Call {
	_c.Call.Return(chmodReply, err)
	return _c
}

func (_c *MockRpcFsServer_Chmod_Call) RunAndReturn(run func(context1 context.Context, chmodRequest *proto.ChmodRequest) (*proto.ChmodReply, error)) *MockRpcFsServer_Chmod_Call {
	_c.Call.Return(run)
	return _c
}

// Chown provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) Chown(context1 context.Context, chownRequest *proto.ChownRequest) (*proto.ChownReply, error) {
	ret := _mock.Called(context1, chownRequest)

	if len(ret) == 0 {
		panic("no return value specified for Chown")
	}

	var r0 *proto.ChownReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.ChownRequest) (*proto.ChownReply, error)); ok {
		return returnFunc(context1, chownRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.ChownRequest) *proto.ChownReply); ok {
		r0 = returnFunc(context1, chownRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ChownReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.ChownRequest) error); ok {
		r1 = returnFunc(context1, chownRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_Chown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chown'
type MockRpcFsServer_Chown_Call struct {
	*mock.Call
}

// Chown is a helper method to define mock.On call
//   - context1 context.Context
//   - chownRequest *proto.ChownRequest
func (_e *MockRpcFsServer_Expecter) Chown(context1 interface{}, chownRequest interface{}) *MockRpcFsServer_Chown_Call {
	return &MockRpcFsServer_Chown_Call{Call: _e.mock.On("Chown", context1, chownRequest)}
}

func (_c *MockRpcFsServer_Chown_Call) Run(run func(context1 context.Context, chownRequest *proto.ChownRequest)) *MockRpcFsServer_Chown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.ChownRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.ChownRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_Chown_Call) Return(chownReply *proto.ChownReply, err error) *MockRpcFsServer_Chown_Call {
	_c.Call.Return(chownReply, err)
	return _c
}

func (_c *MockRpcFsServer_Chown_Call) RunAndReturn(run func(context1 context.Context, chownRequest *proto.ChownRequest) (*proto.ChownReply, error)) *MockRpcFsServer_Chown_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttr provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) GetAttr(context1 context.Context, getAttrRequest *proto.GetAttrRequest) (*proto.GetAttrReply, error) {
	ret := _mock.Called(context1, getAttrRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetAttr")
	}

	var r0 *proto.GetAttrReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetAttrRequest) (*proto.GetAttrReply, error)); ok {
		return returnFunc(context1, getAttrRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetAttrRequest) *proto.GetAttrReply); ok {
		r0 = returnFunc(context1, getAttrRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetAttrReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.GetAttrRequest) error); ok {
		r1 = returnFunc(context1, getAttrRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_GetAttr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttr'
type MockRpcFsServer_GetAttr_Call struct {
	*mock.Call
}

// GetAttr is a helper method to define mock.On call
//   - context1 context.Context
//   - getAttrRequest *proto.GetAttrRequest
func (_e *MockRpcFsServer_Expecter) GetAttr(context1 interface{}, getAttrRequest interface{}) *MockRpcFsServer_GetAttr_Call {
	return &MockRpcFsServer_GetAttr_Call{Call: _e.mock.On("GetAttr", context1, getAttrRequest)}
}

func (_c *MockRpcFsServer_GetAttr_Call) Run(run func(context1 context.Context, getAttrRequest *proto.GetAttrRequest)) *MockRpcFsServer_GetAttr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.GetAttrRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.GetAttrRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_GetAttr_Call) Return(getAttrReply *proto.GetAttrReply, err error) *MockRpcFsServer_GetAttr_Call {
	_c.Call.Return(getAttrReply, err)
	return _c
}

func (_c *MockRpcFsServer_GetAttr_Call) RunAndReturn(run func(context1 context.Context, getAttrRequest *proto.GetAttrRequest) (*proto.GetAttrReply, error)) *MockRpcFsServer_GetAttr_Call {
	_c.Call.Return(run)
	return _c
}

// GetXAttr provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) GetXAttr(context1 context.Context, getXAttrRequest *proto.GetXAttrRequest) (*proto.GetXAttrReply, error) {
	ret := _mock.Called(context1, getXAttrRequest)

	if len(ret) == 0 {
		panic("no return value specified for GetXAttr")
	}

	var r0 *proto.GetXAttrReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetXAttrRequest) (*proto.GetXAttrReply, error)); ok {
		return returnFunc(context1, getXAttrRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetXAttrRequest) *proto.GetXAttrReply); ok {
		r0 = returnFunc(context1, getXAttrRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetXAttrReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.GetXAttrRequest) error); ok {
		r1 = returnFunc(context1, getXAttrRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_GetXAttr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetXAttr'
type MockRpcFsServer_GetXAttr_Call struct {
	*mock.Call
}

// GetXAttr is a helper method to define mock.On call
//   - context1 context.Context
//   - getXAttrRequest *proto.GetXAttrRequest
func (_e *MockRpcFsServer_Expecter) GetXAttr(context1 interface{}, getXAttrRequest interface{}) *MockRpcFsServer_GetXAttr_Call {
	return &MockRpcFsServer_GetXAttr_Call{Call: _e.mock.On("GetXAttr", context1, getXAttrRequest)}
}

func (_c *MockRpcFsServer_GetXAttr_Call) Run(run func(context1 context.Context, getXAttrRequest *proto.GetXAttrRequest)) *MockRpcFsServer_GetXAttr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.GetXAttrRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.GetXAttrRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_GetXAttr_Call) Return(getXAttrReply *proto.GetXAttrReply, err error) *MockRpcFsServer_GetXAttr_Call {
	_c.Call.Return(getXAttrReply, err)
	return _c
}

func (_c *MockRpcFsServer_GetXAttr_Call) RunAndReturn(run func(context1 context.Context, getXAttrRequest *proto.GetXAttrRequest) (*proto.GetXAttrReply, error)) *MockRpcFsServer_GetXAttr_Call {
	_c.Call.Return(run)
	return _c
}

// Mkdir provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) Mkdir(context1 context.Context, mkdirRequest *proto.MkdirRequest) (*proto.MkdirReply, error) {
	ret := _mock.Called(context1, mkdirRequest)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 *proto.MkdirReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.MkdirRequest) (*proto.MkdirReply, error)); ok {
		return returnFunc(context1, mkdirRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.MkdirRequest) *proto.MkdirReply); ok {
		r0 = returnFunc(context1, mkdirRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.MkdirReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.MkdirRequest) error); ok {
		r1 = returnFunc(context1, mkdirRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type MockRpcFsServer_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - context1 context.Context
//   - mkdirRequest *proto.MkdirRequest
func (_e *MockRpcFsServer_Expecter) Mkdir(context1 interface{}, mkdirRequest interface{}) *MockRpcFsServer_Mkdir_Call {
	return &MockRpcFsServer_Mkdir_Call{Call: _e.mock.On("Mkdir", context1, mkdirRequest)}
}

func (_c *MockRpcFsServer_Mkdir_Call) Run(run func(context1 context.Context, mkdirRequest *proto.MkdirRequest)) *MockRpcFsServer_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.MkdirRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.MkdirRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_Mkdir_Call) Return(mkdirReply *proto.MkdirReply, err error) *MockRpcFsServer_Mkdir_Call {
	_c.Call.Return(mkdirReply, err)
	return _c
}

func (_c *MockRpcFsServer_Mkdir_Call) RunAndReturn(run func(context1 context.Context, mkdirRequest *proto.MkdirRequest) (*proto.MkdirReply, error)) *MockRpcFsServer_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// OpenDir provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) OpenDir(context1 context.Context, openDirRequest *proto.OpenDirRequest) (*proto.OpenDirReply, error) {
	ret := _mock.Called(context1, openDirRequest)

	if len(ret) == 0 {
		panic("no return value specified for OpenDir")
	}

	var r0 *proto.OpenDirReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.OpenDirRequest) (*proto.OpenDirReply, error)); ok {
		return returnFunc(context1, openDirRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.OpenDirRequest) *proto.OpenDirReply); ok {
		r0 = returnFunc(context1, openDirRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.OpenDirReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.OpenDirRequest) error); ok {
		r1 = returnFunc(context1, openDirRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_OpenDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDir'
type MockRpcFsServer_OpenDir_Call struct {
	*mock.Call
}

// OpenDir is a helper method to define mock.On call
//   - context1 context.Context
//   - openDirRequest *proto.OpenDirRequest
func (_e *MockRpcFsServer_Expecter) OpenDir(context1 interface{}, openDirRequest interface{}) *MockRpcFsServer_OpenDir_Call {
	return &MockRpcFsServer_OpenDir_Call{Call: _e.mock.On("OpenDir", context1, openDirRequest)}
}

func (_c *MockRpcFsServer_OpenDir_Call) Run(run func(context1 context.Context, openDirRequest *proto.OpenDirRequest)) *MockRpcFsServer_OpenDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.OpenDirRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.OpenDirRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_OpenDir_Call) Return(openDirReply *proto.OpenDirReply, err error) *MockRpcFsServer_OpenDir_Call {
	_c.Call.Return(openDirReply, err)
	return _c
}

func (_c *MockRpcFsServer_OpenDir_Call) RunAndReturn(run func(context1 context.Context, openDirRequest *proto.OpenDirRequest) (*proto.OpenDirReply, error)) *MockRpcFsServer_OpenDir_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) Rename(context1 context.Context, renameRequest *proto.RenameRequest) (*proto.RenameReply, error) {
	ret := _mock.Called(context1, renameRequest)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 *proto.RenameReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.RenameRequest) (*proto.RenameReply, error)); ok {
		return returnFunc(context1, renameRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.RenameRequest) *proto.RenameReply); ok {
		r0 = returnFunc(context1, renameRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RenameReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.RenameRequest) error); ok {
		r1 = returnFunc(context1, renameRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockRpcFsServer_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - context1 context.Context
//   - renameRequest *proto.RenameRequest
func (_e *MockRpcFsServer_Expecter) Rename(context1 interface{}, renameRequest interface{}) *MockRpcFsServer_Rename_Call {
	return &MockRpcFsServer_Rename_Call{Call: _e.mock.On("Rename", context1, renameRequest)}
}

func (_c *MockRpcFsServer_Rename_Call) Run(run func(context1 context.Context, renameRequest *proto.RenameRequest)) *MockRpcFsServer_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.RenameRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.RenameRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_Rename_Call) Return(renameReply *proto.RenameReply, err error) *MockRpcFsServer_Rename_Call {
	_c.Call.Return(renameReply, err)
	return _c
}

func (_c *MockRpcFsServer_Rename_Call) RunAndReturn(run func(context1 context.Context, renameRequest *proto.RenameRequest) (*proto.RenameReply, error)) *MockRpcFsServer_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Rmdir provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) Rmdir(context1 context.Context, rmdirRequest *proto.RmdirRequest) (*proto.RmdirReply, error) {
	ret := _mock.Called(context1, rmdirRequest)

	if len(ret) == 0 {
		panic("no return value specified for Rmdir")
	}

	var r0 *proto.RmdirReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.RmdirRequest) (*proto.RmdirReply, error)); ok {
		return returnFunc(context1, rmdirRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.RmdirRequest) *proto.RmdirReply); ok {
		r0 = returnFunc(context1, rmdirRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RmdirReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.RmdirRequest) error); ok {
		r1 = returnFunc(context1, rmdirRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_Rmdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rmdir'
type MockRpcFsServer_Rmdir_Call struct {
	*mock.Call
}

// Rmdir is a helper method to define mock.On call
//   - context1 context.Context
//   - rmdirRequest *proto.RmdirRequest
func (_e *MockRpcFsServer_Expecter) Rmdir(context1 interface{}, rmdirRequest interface{}) *MockRpcFsServer_Rmdir_Call {
	return &MockRpcFsServer_Rmdir_Call{Call: _e.mock.On("Rmdir", context1, rmdirRequest)}
}

func (_c *MockRpcFsServer_Rmdir_Call) Run(run func(context1 context.Context, rmdirRequest *proto.RmdirRequest)) *MockRpcFsServer_Rmdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.RmdirRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.RmdirRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_Rmdir_Call) Return(rmdirReply *proto.RmdirReply, err error) *MockRpcFsServer_Rmdir_Call {
	_c.Call.Return(rmdirReply, err)
	return _c
}

func (_c *MockRpcFsServer_Rmdir_Call) RunAndReturn(run func(context1 context.Context, rmdirRequest *proto.RmdirRequest) (*proto.RmdirReply, error)) *MockRpcFsServer_Rmdir_Call {
	_c.Call.Return(run)
	return _c
}

// StatFs provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) StatFs(context1 context.Context, statFsRequest *proto.StatFsRequest) (*proto.StatFsReply, error) {
	ret := _mock.Called(context1, statFsRequest)

	if len(ret) == 0 {
		panic("no return value specified for StatFs")
	}

	var r0 *proto.StatFsReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.StatFsRequest) (*proto.StatFsReply, error)); ok {
		return returnFunc(context1, statFsRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.StatFsRequest) *proto.StatFsReply); ok {
		r0 = returnFunc(context1, statFsRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.StatFsReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.StatFsRequest) error); ok {
		r1 = returnFunc(context1, statFsRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_StatFs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatFs'
type MockRpcFsServer_StatFs_Call struct {
	*mock.Call
}

// StatFs is a helper method to define mock.On call
//   - context1 context.Context
//   - statFsRequest *proto.StatFsRequest
func (_e *MockRpcFsServer_Expecter) StatFs(context1 interface{}, statFsRequest interface{}) *MockRpcFsServer_StatFs_Call {
	return &MockRpcFsServer_StatFs_Call{Call: _e.mock.On("StatFs", context1, statFsRequest)}
}

func (_c *MockRpcFsServer_StatFs_Call) Run(run func(context1 context.Context, statFsRequest *proto.StatFsRequest)) *MockRpcFsServer_StatFs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.StatFsRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.StatFsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_StatFs_Call) Return(statFsReply *proto.StatFsReply, err error) *MockRpcFsServer_StatFs_Call {
	_c.Call.Return(statFsReply, err)
	return _c
}

func (_c *MockRpcFsServer_StatFs_Call) RunAndReturn(run func(context1 context.Context, statFsRequest *proto.StatFsRequest) (*proto.StatFsReply, error)) *MockRpcFsServer_StatFs_Call {
	_c.Call.Return(run)
	return _c
}

// Truncate provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) Truncate(context1 context.Context, truncateRequest *proto.TruncateRequest) (*proto.TruncateReply, error) {
	ret := _mock.Called(context1, truncateRequest)

	if len(ret) == 0 {
		panic("no return value specified for Truncate")
	}

	var r0 *proto.TruncateReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.TruncateRequest) (*proto.TruncateReply, error)); ok {
		return returnFunc(context1, truncateRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.TruncateRequest) *proto.TruncateReply); ok {
		r0 = returnFunc(context1, truncateRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TruncateReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.TruncateRequest) error); ok {
		r1 = returnFunc(context1, truncateRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_Truncate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Truncate'
type MockRpcFsServer_Truncate_Call struct {
	*mock.Call
}

// Truncate is a helper method to define mock.On call
//   - context1 context.Context
//   - truncateRequest *proto.TruncateRequest
func (_e *MockRpcFsServer_Expecter) Truncate(context1 interface{}, truncateRequest interface{}) *MockRpcFsServer_Truncate_Call {
	return &MockRpcFsServer_Truncate_Call{Call: _e.mock.On("Truncate", context1, truncateRequest)}
}

func (_c *MockRpcFsServer_Truncate_Call) Run(run func(context1 context.Context, truncateRequest *proto.TruncateRequest)) *MockRpcFsServer_Truncate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.TruncateRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.TruncateRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_Truncate_Call) Return(truncateReply *proto.TruncateReply, err error) *MockRpcFsServer_Truncate_Call {
	_c.Call.Return(truncateReply, err)
	return _c
}

func (_c *MockRpcFsServer_Truncate_Call) RunAndReturn(run func(context1 context.Context, truncateRequest *proto.TruncateRequest) (*proto.TruncateReply, error)) *MockRpcFsServer_Truncate_Call {
	_c.Call.Return(run)
	return _c
}

// Unlink provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) Unlink(context1 context.Context, unlinkRequest *proto.UnlinkRequest) (*proto.UnlinkReply, error) {
	ret := _mock.Called(context1, unlinkRequest)

	if len(ret) == 0 {
		panic("no return value specified for Unlink")
	}

	var r0 *proto.UnlinkReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.UnlinkRequest) (*proto.UnlinkReply, error)); ok {
		return returnFunc(context1, unlinkRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.UnlinkRequest) *proto.UnlinkReply); ok {
		r0 = returnFunc(context1, unlinkRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UnlinkReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.UnlinkRequest) error); ok {
		r1 = returnFunc(context1, unlinkRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsServer_Unlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlink'
type MockRpcFsServer_Unlink_Call struct {
	*mock.Call
}

// Unlink is a helper method to define mock.On call
//   - context1 context.Context
//   - unlinkRequest *proto.UnlinkRequest
func (_e *MockRpcFsServer_Expecter) Unlink(context1 interface{}, unlinkRequest interface{}) *MockRpcFsServer_Unlink_Call {
	return &MockRpcFsServer_Unlink_Call{Call: _e.mock.On("Unlink", context1, unlinkRequest)}
}

func (_c *MockRpcFsServer_Unlink_Call) Run(run func(context1 context.Context, unlinkRequest *proto.UnlinkRequest)) *MockRpcFsServer_Unlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.UnlinkRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.UnlinkRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcFsServer_Unlink_Call) Return(unlinkReply *proto.UnlinkReply, err error) *MockRpcFsServer_Unlink_Call {
	_c.Call.Return(unlinkReply, err)
	return _c
}

func (_c *MockRpcFsServer_Unlink_Call) RunAndReturn(run func(context1 context.Context, unlinkRequest *proto.UnlinkRequest) (*proto.UnlinkReply, error)) *MockRpcFsServer_Unlink_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedRpcFsServer provides a mock function for the type MockRpcFsServer
func (_mock *MockRpcFsServer) mustEmbedUnimplementedRpcFsServer() {
	_mock.Called()
	return
}

// MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedRpcFsServer'
type MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedRpcFsServer is a helper method to define mock.On call
func (_e *MockRpcFsServer_Expecter) mustEmbedUnimplementedRpcFsServer() *MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call {
	return &MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call{Call: _e.mock.On("mustEmbedUnimplementedRpcFsServer")}
}

func (_c *MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call) Run(run func()) *MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call) Return() *MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call) RunAndReturn(run func()) *MockRpcFsServer_mustEmbedUnimplementedRpcFsServer_Call {
	_c.Run(run)
	return _c
}
