// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.gmountie.dev/gmountie/pkg/proto"
	"google.golang.org/grpc/metadata"
)

// NewMockRpcFs_ReadDirServer creates a new instance of MockRpcFs_ReadDirServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcFs_ReadDirServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcFs_ReadDirServer {
	mock := &MockRpcFs_ReadDirServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcFs_ReadDirServer is an autogenerated mock type for the RpcFs_ReadDirServer type
type MockRpcFs_ReadDirServer struct {
	mock.Mock
}

type MockRpcFs_ReadDirServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcFs_ReadDirServer) EXPECT() *MockRpcFs_ReadDirServer_Expecter {
	return &MockRpcFs_ReadDirServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockRpcFs_ReadDirServer
func (_mock *MockRpcFs_ReadDirServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockRpcFs_ReadDirServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockRpcFs_ReadDirServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockRpcFs_ReadDirServer_Expecter) Context() *MockRpcFs_ReadDirServer_Context_Call {
	return &MockRpcFs_ReadDirServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockRpcFs_ReadDirServer_Context_Call) Run(run func()) *MockRpcFs_ReadDirServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFs_ReadDirServer_Context_Call) Return(context1 context.Context) *MockRpcFs_ReadDirServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockRpcFs_ReadDirServer_Context_Call) RunAndReturn(run func() context.Context) *MockRpcFs_ReadDirServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockRpcFs_ReadDirServer
func (_mock *MockRpcFs_ReadDirServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ReadDirServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockRpcFs_ReadDirServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFs_ReadDirServer_Expecter) RecvMsg(m interface{}) *MockRpcFs_ReadDirServer_RecvMsg_Call {
	return &MockRpcFs_ReadDirServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockRpcFs_ReadDirServer_RecvMsg_Call) Run(run func(m any)) *MockRpcFs_ReadDirServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ReadDirServer_RecvMsg_Call) Return(err error) *MockRpcFs_ReadDirServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ReadDirServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFs_ReadDirServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockRpcFs_ReadDirServer
func (_mock *MockRpcFs_ReadDirServer) Send(readDirBatch *proto.ReadDirBatch) error {
	ret := _mock.Called(readDirBatch)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*proto.ReadDirBatch) error); ok {
		r0 = returnFunc(readDirBatch)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ReadDirServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockRpcFs_ReadDirServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - readDirBatch *proto.ReadDirBatch
func (_e *MockRpcFs_ReadDirServer_Expecter) Send(readDirBatch interface{}) *MockRpcFs_ReadDirServer_Send_Call {
	return &MockRpcFs_ReadDirServer_Send_Call{Call: _e.mock.On("Send", readDirBatch)}
}

func (_c *MockRpcFs_ReadDirServer_Send_Call) Run(run func(readDirBatch *proto.ReadDirBatch)) *MockRpcFs_ReadDirServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *proto.ReadDirBatch
		if args[0] != nil {
			arg0 = args[0].(*proto.ReadDirBatch)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ReadDirServer_Send_Call) Return(err error) *MockRpcFs_ReadDirServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ReadDirServer_Send_Call) RunAndReturn(run func(readDirBatch *proto.ReadDirBatch) error) *MockRpcFs_ReadDirServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockRpcFs_ReadDirServer
func (_mock *MockRpcFs_ReadDirServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ReadDirServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockRpcFs_ReadDirServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFs_ReadDirServer_Expecter) SendHeader(mD interface{}) *MockRpcFs_ReadDirServer_SendHeader_Call {
	return &MockRpcFs_ReadDirServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockRpcFs_ReadDirServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockRpcFs_ReadDirServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ReadDirServer_SendHeader_Call) Return(err error) *MockRpcFs_ReadDirServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ReadDirServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockRpcFs_ReadDirServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockRpcFs_ReadDirServer
func (_mock *MockRpcFs_ReadDirServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ReadDirServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockRpcFs_ReadDirServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFs_ReadDirServer_Expecter) SendMsg(m interface{}) *MockRpcFs_ReadDirServer_SendMsg_Call {
	return &MockRpcFs_ReadDirServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockRpcFs_ReadDirServer_SendMsg_Call) Run(run func(m any)) *MockRpcFs_ReadDirServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ReadDirServer_SendMsg_Call) Return(err error) *MockRpcFs_ReadDirServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ReadDirServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFs_ReadDirServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockRpcFs_ReadDirServer
func (_mock *MockRpcFs_ReadDirServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFs_ReadDirServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockRpcFs_ReadDirServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFs_ReadDirServer_Expecter) SetHeader(mD interface{}) *MockRpcFs_ReadDirServer_SetHeader_Call {
	return &MockRpcFs_ReadDirServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockRpcFs_ReadDirServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockRpcFs_ReadDirServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ReadDirServer_SetHeader_Call) Return(err error) *MockRpcFs_ReadDirServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFs_ReadDirServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockRpcFs_ReadDirServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockRpcFs_ReadDirServer
func (_mock *MockRpcFs_ReadDirServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockRpcFs_ReadDirServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockRpcFs_ReadDirServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFs_ReadDirServer_Expecter) SetTrailer(mD interface{}) *MockRpcFs_ReadDirServer_SetTrailer_Call {
	return &MockRpcFs_ReadDirServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockRpcFs_ReadDirServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockRpcFs_ReadDirServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFs_ReadDirServer_SetTrailer_Call) Return() *MockRpcFs_ReadDirServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRpcFs_ReadDirServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockRpcFs_ReadDirServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
