// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"
	"gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockRpcFsClient creates a new instance of MockRpcFsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcFsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcFsClient {
	mock := &MockRpcFsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcFsClient is an autogenerated mock type for the RpcFsClient type
type MockRpcFsClient struct {
	mock.Mock
}

type MockRpcFsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcFsClient) EXPECT() *MockRpcFsClient_Expecter {
	return &MockRpcFsClient_Expecter{mock: &_m.Mock}
}

// Access provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Access(ctx context.Context, in *proto.AccessRequest, opts ...grpc.CallOption) (*proto.AccessReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Access")
	}

	var r0 *proto.AccessReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.AccessRequest, ...grpc.CallOption) (*proto.AccessReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.AccessRequest, ...grpc.CallOption) *proto.AccessReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.AccessReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.AccessRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Access_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Access'
type MockRpcFsClient_Access_Call struct {
	*mock.Call
}

// Access is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.AccessRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Access(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Access_Call {
	return &MockRpcFsClient_Access_Call{Call: _e.mock.On("Access",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Access_Call) Run(run func(ctx context.Context, in *proto.AccessRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Access_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.AccessRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.AccessRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Access_Call) Return(accessReply *proto.AccessReply, err error) *MockRpcFsClient_Access_Call {
	_c.Call.Return(accessReply, err)
	return _c
}

func (_c *MockRpcFsClient_Access_Call) RunAndReturn(run func(ctx context.Context, in *proto.AccessRequest, opts ...grpc.CallOption) (*proto.AccessReply, error)) *MockRpcFsClient_Access_Call {
	_c.Call.Return(run)
	return _c
}

// Chmod provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Chmod(ctx context.Context, in *proto.ChmodRequest, opts ...grpc.CallOption) (*proto.ChmodReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Chmod")
	}

	var r0 *proto.ChmodReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.ChmodRequest, ...grpc.CallOption) (*proto.ChmodReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.ChmodRequest, ...grpc.CallOption) *proto.ChmodReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ChmodReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.ChmodRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Chmod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chmod'
type MockRpcFsClient_Chmod_Call struct {
	*mock.Call
}

// Chmod is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.ChmodRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Chmod(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Chmod_Call {
	return &MockRpcFsClient_Chmod_Call{Call: _e.mock.On("Chmod",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Chmod_Call) Run(run func(ctx context.Context, in *proto.ChmodRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Chmod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.ChmodRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.ChmodRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Chmod_Call) Return(chmodReply *proto.ChmodReply, err error) *MockRpcFsClient_Chmod_Call {
	_c.Call.Return(chmodReply, err)
	return _c
}

func (_c *MockRpcFsClient_Chmod_Call) RunAndReturn(run func(ctx context.Context, in *proto.ChmodRequest, opts ...grpc.CallOption) (*proto.ChmodReply, error)) *MockRpcFsClient_Chmod_Call {
	_c.Call.Return(run)
	return _c
}

// Chown provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Chown(ctx context.Context, in *proto.ChownRequest, opts ...grpc.CallOption) (*proto.ChownReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Chown")
	}

	var r0 *proto.ChownReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.ChownRequest, ...grpc.CallOption) (*proto.ChownReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.ChownRequest, ...grpc.CallOption) *proto.ChownReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ChownReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.ChownRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Chown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chown'
type MockRpcFsClient_Chown_Call struct {
	*mock.Call
}

// Chown is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.ChownRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Chown(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Chown_Call {
	return &MockRpcFsClient_Chown_Call{Call: _e.mock.On("Chown",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Chown_Call) Run(run func(ctx context.Context, in *proto.ChownRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Chown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.ChownRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.ChownRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Chown_Call) Return(chownReply *proto.ChownReply, err error) *MockRpcFsClient_Chown_Call {
	_c.Call.Return(chownReply, err)
	return _c
}

func (_c *MockRpcFsClient_Chown_Call) RunAndReturn(run func(ctx context.Context, in *proto.ChownRequest, opts ...grpc.CallOption) (*proto.ChownReply, error)) *MockRpcFsClient_Chown_Call {
	_c.Call.Return(run)
	return _c
}

// Compound provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Compound(ctx context.Context, in *proto.CompoundRequest, opts ...grpc.CallOption) (*proto.CompoundBatch, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Compound")
	}

	var r0 *proto.CompoundBatch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.CompoundRequest, ...grpc.CallOption) (*proto.CompoundBatch, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.CompoundRequest, ...grpc.CallOption) *proto.CompoundBatch); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CompoundBatch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.CompoundRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Compound_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compound'
type MockRpcFsClient_Compound_Call struct {
	*mock.Call
}

// Compound is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.CompoundRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Compound(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Compound_Call {
	return &MockRpcFsClient_Compound_Call{Call: _e.mock.On("Compound",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Compound_Call) Run(run func(ctx context.Context, in *proto.CompoundRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Compound_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.CompoundRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.CompoundRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Compound_Call) Return(compoundBatch *proto.CompoundBatch, err error) *MockRpcFsClient_Compound_Call {
	_c.Call.Return(compoundBatch, err)
	return _c
}

func (_c *MockRpcFsClient_Compound_Call) RunAndReturn(run func(ctx context.Context, in *proto.CompoundRequest, opts ...grpc.CallOption) (*proto.CompoundBatch, error)) *MockRpcFsClient_Compound_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttr provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) GetAttr(ctx context.Context, in *proto.GetAttrRequest, opts ...grpc.CallOption) (*proto.GetAttrReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAttr")
	}

	var r0 *proto.GetAttrReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetAttrRequest, ...grpc.CallOption) (*proto.GetAttrReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetAttrRequest, ...grpc.CallOption) *proto.GetAttrReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetAttrReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.GetAttrRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_GetAttr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttr'
type MockRpcFsClient_GetAttr_Call struct {
	*mock.Call
}

// GetAttr is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetAttrRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) GetAttr(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_GetAttr_Call {
	return &MockRpcFsClient_GetAttr_Call{Call: _e.mock.On("GetAttr",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_GetAttr_Call) Run(run func(ctx context.Context, in *proto.GetAttrRequest, opts ...grpc.CallOption)) *MockRpcFsClient_GetAttr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.GetAttrRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.GetAttrRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_GetAttr_Call) Return(getAttrReply *proto.GetAttrReply, err error) *MockRpcFsClient_GetAttr_Call {
	_c.Call.Return(getAttrReply, err)
	return _c
}

func (_c *MockRpcFsClient_GetAttr_Call) RunAndReturn(run func(ctx context.Context, in *proto.GetAttrRequest, opts ...grpc.CallOption) (*proto.GetAttrReply, error)) *MockRpcFsClient_GetAttr_Call {
	_c.Call.Return(run)
	return _c
}

// GetAttrIfChanged provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) GetAttrIfChanged(ctx context.Context, in *proto.GetAttrIfChangedRequest, opts ...grpc.CallOption) (*proto.GetAttrIfChangedReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetAttrIfChanged")
	}

	var r0 *proto.GetAttrIfChangedReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetAttrIfChangedRequest, ...grpc.CallOption) (*proto.GetAttrIfChangedReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetAttrIfChangedRequest, ...grpc.CallOption) *proto.GetAttrIfChangedReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetAttrIfChangedReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.GetAttrIfChangedRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_GetAttrIfChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAttrIfChanged'
type MockRpcFsClient_GetAttrIfChanged_Call struct {
	*mock.Call
}

// GetAttrIfChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetAttrIfChangedRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) GetAttrIfChanged(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_GetAttrIfChanged_Call {
	return &MockRpcFsClient_GetAttrIfChanged_Call{Call: _e.mock.On("GetAttrIfChanged",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_GetAttrIfChanged_Call) Run(run func(ctx context.Context, in *proto.GetAttrIfChangedRequest, opts ...grpc.CallOption)) *MockRpcFsClient_GetAttrIfChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.GetAttrIfChangedRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.GetAttrIfChangedRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_GetAttrIfChanged_Call) Return(getAttrIfChangedReply *proto.GetAttrIfChangedReply, err error) *MockRpcFsClient_GetAttrIfChanged_Call {
	_c.Call.Return(getAttrIfChangedReply, err)
	return _c
}

func (_c *MockRpcFsClient_GetAttrIfChanged_Call) RunAndReturn(run func(ctx context.Context, in *proto.GetAttrIfChangedRequest, opts ...grpc.CallOption) (*proto.GetAttrIfChangedReply, error)) *MockRpcFsClient_GetAttrIfChanged_Call {
	_c.Call.Return(run)
	return _c
}

// GetXAttr provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) GetXAttr(ctx context.Context, in *proto.GetXAttrRequest, opts ...grpc.CallOption) (*proto.GetXAttrReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetXAttr")
	}

	var r0 *proto.GetXAttrReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetXAttrRequest, ...grpc.CallOption) (*proto.GetXAttrReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.GetXAttrRequest, ...grpc.CallOption) *proto.GetXAttrReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetXAttrReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.GetXAttrRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_GetXAttr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetXAttr'
type MockRpcFsClient_GetXAttr_Call struct {
	*mock.Call
}

// GetXAttr is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetXAttrRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) GetXAttr(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_GetXAttr_Call {
	return &MockRpcFsClient_GetXAttr_Call{Call: _e.mock.On("GetXAttr",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_GetXAttr_Call) Run(run func(ctx context.Context, in *proto.GetXAttrRequest, opts ...grpc.CallOption)) *MockRpcFsClient_GetXAttr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.GetXAttrRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.GetXAttrRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_GetXAttr_Call) Return(getXAttrReply *proto.GetXAttrReply, err error) *MockRpcFsClient_GetXAttr_Call {
	_c.Call.Return(getXAttrReply, err)
	return _c
}

func (_c *MockRpcFsClient_GetXAttr_Call) RunAndReturn(run func(ctx context.Context, in *proto.GetXAttrRequest, opts ...grpc.CallOption) (*proto.GetXAttrReply, error)) *MockRpcFsClient_GetXAttr_Call {
	_c.Call.Return(run)
	return _c
}

// Mkdir provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Mkdir(ctx context.Context, in *proto.MkdirRequest, opts ...grpc.CallOption) (*proto.MkdirReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Mkdir")
	}

	var r0 *proto.MkdirReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.MkdirRequest, ...grpc.CallOption) (*proto.MkdirReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.MkdirRequest, ...grpc.CallOption) *proto.MkdirReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.MkdirReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.MkdirRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Mkdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mkdir'
type MockRpcFsClient_Mkdir_Call struct {
	*mock.Call
}

// Mkdir is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.MkdirRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Mkdir(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Mkdir_Call {
	return &MockRpcFsClient_Mkdir_Call{Call: _e.mock.On("Mkdir",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Mkdir_Call) Run(run func(ctx context.Context, in *proto.MkdirRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Mkdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.MkdirRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.MkdirRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Mkdir_Call) Return(mkdirReply *proto.MkdirReply, err error) *MockRpcFsClient_Mkdir_Call {
	_c.Call.Return(mkdirReply, err)
	return _c
}

func (_c *MockRpcFsClient_Mkdir_Call) RunAndReturn(run func(ctx context.Context, in *proto.MkdirRequest, opts ...grpc.CallOption) (*proto.MkdirReply, error)) *MockRpcFsClient_Mkdir_Call {
	_c.Call.Return(run)
	return _c
}

// OpenDir provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) OpenDir(ctx context.Context, in *proto.OpenDirRequest, opts ...grpc.CallOption) (*proto.OpenDirReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OpenDir")
	}

	var r0 *proto.OpenDirReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.OpenDirRequest, ...grpc.CallOption) (*proto.OpenDirReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.OpenDirRequest, ...grpc.CallOption) *proto.OpenDirReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.OpenDirReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.OpenDirRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_OpenDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OpenDir'
type MockRpcFsClient_OpenDir_Call struct {
	*mock.Call
}

// OpenDir is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.OpenDirRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) OpenDir(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_OpenDir_Call {
	return &MockRpcFsClient_OpenDir_Call{Call: _e.mock.On("OpenDir",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_OpenDir_Call) Run(run func(ctx context.Context, in *proto.OpenDirRequest, opts ...grpc.CallOption)) *MockRpcFsClient_OpenDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.OpenDirRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.OpenDirRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_OpenDir_Call) Return(openDirReply *proto.OpenDirReply, err error) *MockRpcFsClient_OpenDir_Call {
	_c.Call.Return(openDirReply, err)
	return _c
}

func (_c *MockRpcFsClient_OpenDir_Call) RunAndReturn(run func(ctx context.Context, in *proto.OpenDirRequest, opts ...grpc.CallOption) (*proto.OpenDirReply, error)) *MockRpcFsClient_OpenDir_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Rename(ctx context.Context, in *proto.RenameRequest, opts ...grpc.CallOption) (*proto.RenameReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 *proto.RenameReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.RenameRequest, ...grpc.CallOption) (*proto.RenameReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.RenameRequest, ...grpc.CallOption) *proto.RenameReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RenameReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.RenameRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockRpcFsClient_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.RenameRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Rename(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Rename_Call {
	return &MockRpcFsClient_Rename_Call{Call: _e.mock.On("Rename",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Rename_Call) Run(run func(ctx context.Context, in *proto.RenameRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.RenameRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.RenameRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Rename_Call) Return(renameReply *proto.RenameReply, err error) *MockRpcFsClient_Rename_Call {
	_c.Call.Return(renameReply, err)
	return _c
}

func (_c *MockRpcFsClient_Rename_Call) RunAndReturn(run func(ctx context.Context, in *proto.RenameRequest, opts ...grpc.CallOption) (*proto.RenameReply, error)) *MockRpcFsClient_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// Rmdir provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Rmdir(ctx context.Context, in *proto.RmdirRequest, opts ...grpc.CallOption) (*proto.RmdirReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Rmdir")
	}

	var r0 *proto.RmdirReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.RmdirRequest, ...grpc.CallOption) (*proto.RmdirReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.RmdirRequest, ...grpc.CallOption) *proto.RmdirReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RmdirReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.RmdirRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Rmdir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rmdir'
type MockRpcFsClient_Rmdir_Call struct {
	*mock.Call
}

// Rmdir is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.RmdirRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Rmdir(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Rmdir_Call {
	return &MockRpcFsClient_Rmdir_Call{Call: _e.mock.On("Rmdir",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Rmdir_Call) Run(run func(ctx context.Context, in *proto.RmdirRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Rmdir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.RmdirRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.RmdirRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Rmdir_Call) Return(rmdirReply *proto.RmdirReply, err error) *MockRpcFsClient_Rmdir_Call {
	_c.Call.Return(rmdirReply, err)
	return _c
}

func (_c *MockRpcFsClient_Rmdir_Call) RunAndReturn(run func(ctx context.Context, in *proto.RmdirRequest, opts ...grpc.CallOption) (*proto.RmdirReply, error)) *MockRpcFsClient_Rmdir_Call {
	_c.Call.Return(run)
	return _c
}

// StatFs provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) StatFs(ctx context.Context, in *proto.StatFsRequest, opts ...grpc.CallOption) (*proto.StatFsReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StatFs")
	}

	var r0 *proto.StatFsReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.StatFsRequest, ...grpc.CallOption) (*proto.StatFsReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.StatFsRequest, ...grpc.CallOption) *proto.StatFsReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.StatFsReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.StatFsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_StatFs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StatFs'
type MockRpcFsClient_StatFs_Call struct {
	*mock.Call
}

// StatFs is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.StatFsRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) StatFs(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_StatFs_Call {
	return &MockRpcFsClient_StatFs_Call{Call: _e.mock.On("StatFs",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_StatFs_Call) Run(run func(ctx context.Context, in *proto.StatFsRequest, opts ...grpc.CallOption)) *MockRpcFsClient_StatFs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.StatFsRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.StatFsRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_StatFs_Call) Return(statFsReply *proto.StatFsReply, err error) *MockRpcFsClient_StatFs_Call {
	_c.Call.Return(statFsReply, err)
	return _c
}

func (_c *MockRpcFsClient_StatFs_Call) RunAndReturn(run func(ctx context.Context, in *proto.StatFsRequest, opts ...grpc.CallOption) (*proto.StatFsReply, error)) *MockRpcFsClient_StatFs_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Subscribe(ctx context.Context, in *proto.SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.SubscribeEvent], error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 grpc.ServerStreamingClient[proto.SubscribeEvent]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SubscribeRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[proto.SubscribeEvent], error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SubscribeRequest, ...grpc.CallOption) grpc.ServerStreamingClient[proto.SubscribeEvent]); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[proto.SubscribeEvent])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.SubscribeRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockRpcFsClient_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.SubscribeRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Subscribe(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Subscribe_Call {
	return &MockRpcFsClient_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Subscribe_Call) Run(run func(ctx context.Context, in *proto.SubscribeRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.SubscribeRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.SubscribeRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Subscribe_Call) Return(serverStreamingClient grpc.ServerStreamingClient[proto.SubscribeEvent], err error) *MockRpcFsClient_Subscribe_Call {
	_c.Call.Return(serverStreamingClient, err)
	return _c
}

func (_c *MockRpcFsClient_Subscribe_Call) RunAndReturn(run func(ctx context.Context, in *proto.SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.SubscribeEvent], error)) *MockRpcFsClient_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Truncate provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Truncate(ctx context.Context, in *proto.TruncateRequest, opts ...grpc.CallOption) (*proto.TruncateReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Truncate")
	}

	var r0 *proto.TruncateReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.TruncateRequest, ...grpc.CallOption) (*proto.TruncateReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.TruncateRequest, ...grpc.CallOption) *proto.TruncateReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.TruncateReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.TruncateRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Truncate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Truncate'
type MockRpcFsClient_Truncate_Call struct {
	*mock.Call
}

// Truncate is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.TruncateRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Truncate(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Truncate_Call {
	return &MockRpcFsClient_Truncate_Call{Call: _e.mock.On("Truncate",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Truncate_Call) Run(run func(ctx context.Context, in *proto.TruncateRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Truncate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.TruncateRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.TruncateRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Truncate_Call) Return(truncateReply *proto.TruncateReply, err error) *MockRpcFsClient_Truncate_Call {
	_c.Call.Return(truncateReply, err)
	return _c
}

func (_c *MockRpcFsClient_Truncate_Call) RunAndReturn(run func(ctx context.Context, in *proto.TruncateRequest, opts ...grpc.CallOption) (*proto.TruncateReply, error)) *MockRpcFsClient_Truncate_Call {
	_c.Call.Return(run)
	return _c
}

// Unlink provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Unlink(ctx context.Context, in *proto.UnlinkRequest, opts ...grpc.CallOption) (*proto.UnlinkReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Unlink")
	}

	var r0 *proto.UnlinkReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.UnlinkRequest, ...grpc.CallOption) (*proto.UnlinkReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.UnlinkRequest, ...grpc.CallOption) *proto.UnlinkReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UnlinkReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.UnlinkRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Unlink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlink'
type MockRpcFsClient_Unlink_Call struct {
	*mock.Call
}

// Unlink is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UnlinkRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Unlink(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Unlink_Call {
	return &MockRpcFsClient_Unlink_Call{Call: _e.mock.On("Unlink",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Unlink_Call) Run(run func(ctx context.Context, in *proto.UnlinkRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Unlink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.UnlinkRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.UnlinkRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Unlink_Call) Return(unlinkReply *proto.UnlinkReply, err error) *MockRpcFsClient_Unlink_Call {
	_c.Call.Return(unlinkReply, err)
	return _c
}

func (_c *MockRpcFsClient_Unlink_Call) RunAndReturn(run func(ctx context.Context, in *proto.UnlinkRequest, opts ...grpc.CallOption) (*proto.UnlinkReply, error)) *MockRpcFsClient_Unlink_Call {
	_c.Call.Return(run)
	return _c
}

// Utimens provides a mock function for the type MockRpcFsClient
func (_mock *MockRpcFsClient) Utimens(ctx context.Context, in *proto.UtimensRequest, opts ...grpc.CallOption) (*proto.UtimensReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Utimens")
	}

	var r0 *proto.UtimensReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.UtimensRequest, ...grpc.CallOption) (*proto.UtimensReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.UtimensRequest, ...grpc.CallOption) *proto.UtimensReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UtimensReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.UtimensRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFsClient_Utimens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Utimens'
type MockRpcFsClient_Utimens_Call struct {
	*mock.Call
}

// Utimens is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UtimensRequest
//   - opts ...grpc.CallOption
func (_e *MockRpcFsClient_Expecter) Utimens(ctx interface{}, in interface{}, opts ...interface{}) *MockRpcFsClient_Utimens_Call {
	return &MockRpcFsClient_Utimens_Call{Call: _e.mock.On("Utimens",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockRpcFsClient_Utimens_Call) Run(run func(ctx context.Context, in *proto.UtimensRequest, opts ...grpc.CallOption)) *MockRpcFsClient_Utimens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.UtimensRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.UtimensRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRpcFsClient_Utimens_Call) Return(utimensReply *proto.UtimensReply, err error) *MockRpcFsClient_Utimens_Call {
	_c.Call.Return(utimensReply, err)
	return _c
}

func (_c *MockRpcFsClient_Utimens_Call) RunAndReturn(run func(ctx context.Context, in *proto.UtimensRequest, opts ...grpc.CallOption) (*proto.UtimensReply, error)) *MockRpcFsClient_Utimens_Call {
	_c.Call.Return(run)
	return _c
}
