// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"
	"go.gmountie.dev/gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockSessionServiceClient creates a new instance of MockSessionServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionServiceClient {
	mock := &MockSessionServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionServiceClient is an autogenerated mock type for the SessionServiceClient type
type MockSessionServiceClient struct {
	mock.Mock
}

type MockSessionServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionServiceClient) EXPECT() *MockSessionServiceClient_Expecter {
	return &MockSessionServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionServiceClient
func (_mock *MockSessionServiceClient) Create(ctx context.Context, in *proto.SessionCreateRequest, opts ...grpc.CallOption) (*proto.SessionCreateReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *proto.SessionCreateReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SessionCreateRequest, ...grpc.CallOption) (*proto.SessionCreateReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SessionCreateRequest, ...grpc.CallOption) *proto.SessionCreateReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SessionCreateReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.SessionCreateRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.SessionCreateRequest
//   - opts ...grpc.CallOption
func (_e *MockSessionServiceClient_Expecter) Create(ctx interface{}, in interface{}, opts ...interface{}) *MockSessionServiceClient_Create_Call {
	return &MockSessionServiceClient_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSessionServiceClient_Create_Call) Run(run func(ctx context.Context, in *proto.SessionCreateRequest, opts ...grpc.CallOption)) *MockSessionServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.SessionCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.SessionCreateRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSessionServiceClient_Create_Call) Return(sessionCreateReply *proto.SessionCreateReply, err error) *MockSessionServiceClient_Create_Call {
	_c.Call.Return(sessionCreateReply, err)
	return _c
}

func (_c *MockSessionServiceClient_Create_Call) RunAndReturn(run func(ctx context.Context, in *proto.SessionCreateRequest, opts ...grpc.CallOption) (*proto.SessionCreateReply, error)) *MockSessionServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Keepalive provides a mock function for the type MockSessionServiceClient
func (_mock *MockSessionServiceClient) Keepalive(ctx context.Context, in *proto.KeepaliveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.KeepalivePing], error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Keepalive")
	}

	var r0 grpc.ServerStreamingClient[proto.KeepalivePing]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.KeepaliveRequest, ...grpc.CallOption) (grpc.ServerStreamingClient[proto.KeepalivePing], error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.KeepaliveRequest, ...grpc.CallOption) grpc.ServerStreamingClient[proto.KeepalivePing]); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.ServerStreamingClient[proto.KeepalivePing])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.KeepaliveRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionServiceClient_Keepalive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Keepalive'
type MockSessionServiceClient_Keepalive_Call struct {
	*mock.Call
}

// Keepalive is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.KeepaliveRequest
//   - opts ...grpc.CallOption
func (_e *MockSessionServiceClient_Expecter) Keepalive(ctx interface{}, in interface{}, opts ...interface{}) *MockSessionServiceClient_Keepalive_Call {
	return &MockSessionServiceClient_Keepalive_Call{Call: _e.mock.On("Keepalive",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSessionServiceClient_Keepalive_Call) Run(run func(ctx context.Context, in *proto.KeepaliveRequest, opts ...grpc.CallOption)) *MockSessionServiceClient_Keepalive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.KeepaliveRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.KeepaliveRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSessionServiceClient_Keepalive_Call) Return(serverStreamingClient grpc.ServerStreamingClient[proto.KeepalivePing], err error) *MockSessionServiceClient_Keepalive_Call {
	_c.Call.Return(serverStreamingClient, err)
	return _c
}

func (_c *MockSessionServiceClient_Keepalive_Call) RunAndReturn(run func(ctx context.Context, in *proto.KeepaliveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[proto.KeepalivePing], error)) *MockSessionServiceClient_Keepalive_Call {
	_c.Call.Return(run)
	return _c
}

// Resume provides a mock function for the type MockSessionServiceClient
func (_mock *MockSessionServiceClient) Resume(ctx context.Context, in *proto.SessionResumeRequest, opts ...grpc.CallOption) (*proto.SessionResumeReply, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Resume")
	}

	var r0 *proto.SessionResumeReply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SessionResumeRequest, ...grpc.CallOption) (*proto.SessionResumeReply, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.SessionResumeRequest, ...grpc.CallOption) *proto.SessionResumeReply); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.SessionResumeReply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.SessionResumeRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionServiceClient_Resume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resume'
type MockSessionServiceClient_Resume_Call struct {
	*mock.Call
}

// Resume is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.SessionResumeRequest
//   - opts ...grpc.CallOption
func (_e *MockSessionServiceClient_Expecter) Resume(ctx interface{}, in interface{}, opts ...interface{}) *MockSessionServiceClient_Resume_Call {
	return &MockSessionServiceClient_Resume_Call{Call: _e.mock.On("Resume",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSessionServiceClient_Resume_Call) Run(run func(ctx context.Context, in *proto.SessionResumeRequest, opts ...grpc.CallOption)) *MockSessionServiceClient_Resume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.SessionResumeRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.SessionResumeRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSessionServiceClient_Resume_Call) Return(sessionResumeReply *proto.SessionResumeReply, err error) *MockSessionServiceClient_Resume_Call {
	_c.Call.Return(sessionResumeReply, err)
	return _c
}

func (_c *MockSessionServiceClient_Resume_Call) RunAndReturn(run func(ctx context.Context, in *proto.SessionResumeRequest, opts ...grpc.CallOption) (*proto.SessionResumeReply, error)) *MockSessionServiceClient_Resume_Call {
	_c.Call.Return(run)
	return _c
}

// WhoAmI provides a mock function for the type MockSessionServiceClient
func (_mock *MockSessionServiceClient) WhoAmI(ctx context.Context, in *proto.WhoAmIRequest, opts ...grpc.CallOption) (*proto.Identity, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WhoAmI")
	}

	var r0 *proto.Identity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.WhoAmIRequest, ...grpc.CallOption) (*proto.Identity, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *proto.WhoAmIRequest, ...grpc.CallOption) *proto.Identity); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.Identity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *proto.WhoAmIRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionServiceClient_WhoAmI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WhoAmI'
type MockSessionServiceClient_WhoAmI_Call struct {
	*mock.Call
}

// WhoAmI is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.WhoAmIRequest
//   - opts ...grpc.CallOption
func (_e *MockSessionServiceClient_Expecter) WhoAmI(ctx interface{}, in interface{}, opts ...interface{}) *MockSessionServiceClient_WhoAmI_Call {
	return &MockSessionServiceClient_WhoAmI_Call{Call: _e.mock.On("WhoAmI",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockSessionServiceClient_WhoAmI_Call) Run(run func(ctx context.Context, in *proto.WhoAmIRequest, opts ...grpc.CallOption)) *MockSessionServiceClient_WhoAmI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *proto.WhoAmIRequest
		if args[1] != nil {
			arg1 = args[1].(*proto.WhoAmIRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSessionServiceClient_WhoAmI_Call) Return(identity *proto.Identity, err error) *MockSessionServiceClient_WhoAmI_Call {
	_c.Call.Return(identity, err)
	return _c
}

func (_c *MockSessionServiceClient_WhoAmI_Call) RunAndReturn(run func(ctx context.Context, in *proto.WhoAmIRequest, opts ...grpc.CallOption) (*proto.Identity, error)) *MockSessionServiceClient_WhoAmI_Call {
	_c.Call.Return(run)
	return _c
}
