// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"
	"go.gmountie.dev/gmountie/pkg/proto"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc/metadata"
)

// NewMockRpcFile_WriteServer creates a new instance of MockRpcFile_WriteServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcFile_WriteServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcFile_WriteServer {
	mock := &MockRpcFile_WriteServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcFile_WriteServer is an autogenerated mock type for the RpcFile_WriteServer type
type MockRpcFile_WriteServer struct {
	mock.Mock
}

type MockRpcFile_WriteServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcFile_WriteServer) EXPECT() *MockRpcFile_WriteServer_Expecter {
	return &MockRpcFile_WriteServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockRpcFile_WriteServer
func (_mock *MockRpcFile_WriteServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockRpcFile_WriteServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockRpcFile_WriteServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockRpcFile_WriteServer_Expecter) Context() *MockRpcFile_WriteServer_Context_Call {
	return &MockRpcFile_WriteServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockRpcFile_WriteServer_Context_Call) Run(run func()) *MockRpcFile_WriteServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFile_WriteServer_Context_Call) Return(context1 context.Context) *MockRpcFile_WriteServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockRpcFile_WriteServer_Context_Call) RunAndReturn(run func() context.Context) *MockRpcFile_WriteServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function for the type MockRpcFile_WriteServer
func (_mock *MockRpcFile_WriteServer) Recv() (*proto.WriteFrame, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *proto.WriteFrame
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*proto.WriteFrame, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *proto.WriteFrame); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.WriteFrame)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcFile_WriteServer_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockRpcFile_WriteServer_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockRpcFile_WriteServer_Expecter) Recv() *MockRpcFile_WriteServer_Recv_Call {
	return &MockRpcFile_WriteServer_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockRpcFile_WriteServer_Recv_Call) Run(run func()) *MockRpcFile_WriteServer_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFile_WriteServer_Recv_Call) Return(writeFrame *proto.WriteFrame, err error) *MockRpcFile_WriteServer_Recv_Call {
	_c.Call.Return(writeFrame, err)
	return _c
}

func (_c *MockRpcFile_WriteServer_Recv_Call) RunAndReturn(run func() (*proto.WriteFrame, error)) *MockRpcFile_WriteServer_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockRpcFile_WriteServer
func (_mock *MockRpcFile_WriteServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_WriteServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockRpcFile_WriteServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFile_WriteServer_Expecter) RecvMsg(m interface{}) *MockRpcFile_WriteServer_RecvMsg_Call {
	return &MockRpcFile_WriteServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockRpcFile_WriteServer_RecvMsg_Call) Run(run func(m any)) *MockRpcFile_WriteServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_WriteServer_RecvMsg_Call) Return(err error) *MockRpcFile_WriteServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_WriteServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFile_WriteServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SendAndClose provides a mock function for the type MockRpcFile_WriteServer
func (_mock *MockRpcFile_WriteServer) SendAndClose(writeReply *proto.WriteReply) error {
	ret := _mock.Called(writeReply)

	if len(ret) == 0 {
		panic("no return value specified for SendAndClose")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*proto.WriteReply) error); ok {
		r0 = returnFunc(writeReply)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_WriteServer_SendAndClose_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendAndClose'
type MockRpcFile_WriteServer_SendAndClose_Call struct {
	*mock.Call
}

// SendAndClose is a helper method to define mock.On call
//   - writeReply *proto.WriteReply
func (_e *MockRpcFile_WriteServer_Expecter) SendAndClose(writeReply interface{}) *MockRpcFile_WriteServer_SendAndClose_Call {
	return &MockRpcFile_WriteServer_SendAndClose_Call{Call: _e.mock.On("SendAndClose", writeReply)}
}

func (_c *MockRpcFile_WriteServer_SendAndClose_Call) Run(run func(writeReply *proto.WriteReply)) *MockRpcFile_WriteServer_SendAndClose_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *proto.WriteReply
		if args[0] != nil {
			arg0 = args[0].(*proto.WriteReply)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_WriteServer_SendAndClose_Call) Return(err error) *MockRpcFile_WriteServer_SendAndClose_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_WriteServer_SendAndClose_Call) RunAndReturn(run func(writeReply *proto.WriteReply) error) *MockRpcFile_WriteServer_SendAndClose_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockRpcFile_WriteServer
func (_mock *MockRpcFile_WriteServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_WriteServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockRpcFile_WriteServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFile_WriteServer_Expecter) SendHeader(mD interface{}) *MockRpcFile_WriteServer_SendHeader_Call {
	return &MockRpcFile_WriteServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockRpcFile_WriteServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockRpcFile_WriteServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_WriteServer_SendHeader_Call) Return(err error) *MockRpcFile_WriteServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_WriteServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockRpcFile_WriteServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockRpcFile_WriteServer
func (_mock *MockRpcFile_WriteServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_WriteServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockRpcFile_WriteServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFile_WriteServer_Expecter) SendMsg(m interface{}) *MockRpcFile_WriteServer_SendMsg_Call {
	return &MockRpcFile_WriteServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockRpcFile_WriteServer_SendMsg_Call) Run(run func(m any)) *MockRpcFile_WriteServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_WriteServer_SendMsg_Call) Return(err error) *MockRpcFile_WriteServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_WriteServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFile_WriteServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockRpcFile_WriteServer
func (_mock *MockRpcFile_WriteServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_WriteServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockRpcFile_WriteServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFile_WriteServer_Expecter) SetHeader(mD interface{}) *MockRpcFile_WriteServer_SetHeader_Call {
	return &MockRpcFile_WriteServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockRpcFile_WriteServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockRpcFile_WriteServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_WriteServer_SetHeader_Call) Return(err error) *MockRpcFile_WriteServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_WriteServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockRpcFile_WriteServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockRpcFile_WriteServer
func (_mock *MockRpcFile_WriteServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockRpcFile_WriteServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockRpcFile_WriteServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFile_WriteServer_Expecter) SetTrailer(mD interface{}) *MockRpcFile_WriteServer_SetTrailer_Call {
	return &MockRpcFile_WriteServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockRpcFile_WriteServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockRpcFile_WriteServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_WriteServer_SetTrailer_Call) Return() *MockRpcFile_WriteServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRpcFile_WriteServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockRpcFile_WriteServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
