// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.gmountie.dev/gmountie/pkg/proto"
	"google.golang.org/grpc/metadata"
)

// NewMockRpcFile_ReadServer creates a new instance of MockRpcFile_ReadServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcFile_ReadServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcFile_ReadServer {
	mock := &MockRpcFile_ReadServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcFile_ReadServer is an autogenerated mock type for the RpcFile_ReadServer type
type MockRpcFile_ReadServer struct {
	mock.Mock
}

type MockRpcFile_ReadServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcFile_ReadServer) EXPECT() *MockRpcFile_ReadServer_Expecter {
	return &MockRpcFile_ReadServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function for the type MockRpcFile_ReadServer
func (_mock *MockRpcFile_ReadServer) Context() context.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func() context.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockRpcFile_ReadServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockRpcFile_ReadServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockRpcFile_ReadServer_Expecter) Context() *MockRpcFile_ReadServer_Context_Call {
	return &MockRpcFile_ReadServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockRpcFile_ReadServer_Context_Call) Run(run func()) *MockRpcFile_ReadServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcFile_ReadServer_Context_Call) Return(context1 context.Context) *MockRpcFile_ReadServer_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockRpcFile_ReadServer_Context_Call) RunAndReturn(run func() context.Context) *MockRpcFile_ReadServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function for the type MockRpcFile_ReadServer
func (_mock *MockRpcFile_ReadServer) RecvMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_ReadServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockRpcFile_ReadServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFile_ReadServer_Expecter) RecvMsg(m interface{}) *MockRpcFile_ReadServer_RecvMsg_Call {
	return &MockRpcFile_ReadServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockRpcFile_ReadServer_RecvMsg_Call) Run(run func(m any)) *MockRpcFile_ReadServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_ReadServer_RecvMsg_Call) Return(err error) *MockRpcFile_ReadServer_RecvMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_ReadServer_RecvMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFile_ReadServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function for the type MockRpcFile_ReadServer
func (_mock *MockRpcFile_ReadServer) Send(readFrame *proto.ReadFrame) error {
	ret := _mock.Called(readFrame)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*proto.ReadFrame) error); ok {
		r0 = returnFunc(readFrame)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_ReadServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockRpcFile_ReadServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - readFrame *proto.ReadFrame
func (_e *MockRpcFile_ReadServer_Expecter) Send(readFrame interface{}) *MockRpcFile_ReadServer_Send_Call {
	return &MockRpcFile_ReadServer_Send_Call{Call: _e.mock.On("Send", readFrame)}
}

func (_c *MockRpcFile_ReadServer_Send_Call) Run(run func(readFrame *proto.ReadFrame)) *MockRpcFile_ReadServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *proto.ReadFrame
		if args[0] != nil {
			arg0 = args[0].(*proto.ReadFrame)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_ReadServer_Send_Call) Return(err error) *MockRpcFile_ReadServer_Send_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_ReadServer_Send_Call) RunAndReturn(run func(readFrame *proto.ReadFrame) error) *MockRpcFile_ReadServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function for the type MockRpcFile_ReadServer
func (_mock *MockRpcFile_ReadServer) SendHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_ReadServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockRpcFile_ReadServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFile_ReadServer_Expecter) SendHeader(mD interface{}) *MockRpcFile_ReadServer_SendHeader_Call {
	return &MockRpcFile_ReadServer_SendHeader_Call{Call: _e.mock.On("SendHeader", mD)}
}

func (_c *MockRpcFile_ReadServer_SendHeader_Call) Run(run func(mD metadata.MD)) *MockRpcFile_ReadServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_ReadServer_SendHeader_Call) Return(err error) *MockRpcFile_ReadServer_SendHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_ReadServer_SendHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockRpcFile_ReadServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function for the type MockRpcFile_ReadServer
func (_mock *MockRpcFile_ReadServer) SendMsg(m any) error {
	ret := _mock.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(any) error); ok {
		r0 = returnFunc(m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_ReadServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockRpcFile_ReadServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m any
func (_e *MockRpcFile_ReadServer_Expecter) SendMsg(m interface{}) *MockRpcFile_ReadServer_SendMsg_Call {
	return &MockRpcFile_ReadServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockRpcFile_ReadServer_SendMsg_Call) Run(run func(m any)) *MockRpcFile_ReadServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_ReadServer_SendMsg_Call) Return(err error) *MockRpcFile_ReadServer_SendMsg_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_ReadServer_SendMsg_Call) RunAndReturn(run func(m any) error) *MockRpcFile_ReadServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function for the type MockRpcFile_ReadServer
func (_mock *MockRpcFile_ReadServer) SetHeader(mD metadata.MD) error {
	ret := _mock.Called(mD)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = returnFunc(mD)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcFile_ReadServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockRpcFile_ReadServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFile_ReadServer_Expecter) SetHeader(mD interface{}) *MockRpcFile_ReadServer_SetHeader_Call {
	return &MockRpcFile_ReadServer_SetHeader_Call{Call: _e.mock.On("SetHeader", mD)}
}

func (_c *MockRpcFile_ReadServer_SetHeader_Call) Run(run func(mD metadata.MD)) *MockRpcFile_ReadServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_ReadServer_SetHeader_Call) Return(err error) *MockRpcFile_ReadServer_SetHeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcFile_ReadServer_SetHeader_Call) RunAndReturn(run func(mD metadata.MD) error) *MockRpcFile_ReadServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function for the type MockRpcFile_ReadServer
func (_mock *MockRpcFile_ReadServer) SetTrailer(mD metadata.MD) {
	_mock.Called(mD)
	return
}

// MockRpcFile_ReadServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockRpcFile_ReadServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - mD metadata.MD
func (_e *MockRpcFile_ReadServer_Expecter) SetTrailer(mD interface{}) *MockRpcFile_ReadServer_SetTrailer_Call {
	return &MockRpcFile_ReadServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", mD)}
}

func (_c *MockRpcFile_ReadServer_SetTrailer_Call) Run(run func(mD metadata.MD)) *MockRpcFile_ReadServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 metadata.MD
		if args[0] != nil {
			arg0 = args[0].(metadata.MD)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcFile_ReadServer_SetTrailer_Call) Return() *MockRpcFile_ReadServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRpcFile_ReadServer_SetTrailer_Call) RunAndReturn(run func(mD metadata.MD)) *MockRpcFile_ReadServer_SetTrailer_Call {
	_c.Run(run)
	return _c
}
