// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package proto

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockisCompoundOp_Op creates a new instance of mockisCompoundOp_Op. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockisCompoundOp_Op(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockisCompoundOp_Op {
	mock := &mockisCompoundOp_Op{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockisCompoundOp_Op is an autogenerated mock type for the isCompoundOp_Op type
type mockisCompoundOp_Op struct {
	mock.Mock
}

type mockisCompoundOp_Op_Expecter struct {
	mock *mock.Mock
}

func (_m *mockisCompoundOp_Op) EXPECT() *mockisCompoundOp_Op_Expecter {
	return &mockisCompoundOp_Op_Expecter{mock: &_m.Mock}
}

// isCompoundOp_Op provides a mock function for the type mockisCompoundOp_Op
func (_mock *mockisCompoundOp_Op) isCompoundOp_Op() {
	_mock.Called()
	return
}

// mockisCompoundOp_Op_isCompoundOp_Op_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isCompoundOp_Op'
type mockisCompoundOp_Op_isCompoundOp_Op_Call struct {
	*mock.Call
}

// isCompoundOp_Op is a helper method to define mock.On call
func (_e *mockisCompoundOp_Op_Expecter) isCompoundOp_Op() *mockisCompoundOp_Op_isCompoundOp_Op_Call {
	return &mockisCompoundOp_Op_isCompoundOp_Op_Call{Call: _e.mock.On("isCompoundOp_Op")}
}

func (_c *mockisCompoundOp_Op_isCompoundOp_Op_Call) Run(run func()) *mockisCompoundOp_Op_isCompoundOp_Op_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockisCompoundOp_Op_isCompoundOp_Op_Call) Return() *mockisCompoundOp_Op_isCompoundOp_Op_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockisCompoundOp_Op_isCompoundOp_Op_Call) RunAndReturn(run func()) *mockisCompoundOp_Op_isCompoundOp_Op_Call {
	_c.Run(run)
	return _c
}
