// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package io

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileHandle creates a new instance of MockFileHandle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileHandle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileHandle {
	mock := &MockFileHandle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileHandle is an autogenerated mock type for the FileHandle type
type MockFileHandle struct {
	mock.Mock
}

type MockFileHandle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileHandle) EXPECT() *MockFileHandle_Expecter {
	return &MockFileHandle_Expecter{mock: &_m.Mock}
}

// Path provides a mock function for the type MockFileHandle
func (_mock *MockFileHandle) Path() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFileHandle_Path_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Path'
type MockFileHandle_Path_Call struct {
	*mock.Call
}

// Path is a helper method to define mock.On call
func (_e *MockFileHandle_Expecter) Path() *MockFileHandle_Path_Call {
	return &MockFileHandle_Path_Call{Call: _e.mock.On("Path")}
}

func (_c *MockFileHandle_Path_Call) Run(run func()) *MockFileHandle_Path_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFileHandle_Path_Call) Return(s string) *MockFileHandle_Path_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFileHandle_Path_Call) RunAndReturn(run func() string) *MockFileHandle_Path_Call {
	_c.Call.Return(run)
	return _c
}
