// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"gmountie/pkg/common"
	"gmountie/pkg/proto"

	"github.com/hanwen/go-fuse/v2/fuse/pathfs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVolumeService creates a new instance of MockVolumeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVolumeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVolumeService {
	mock := &MockVolumeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVolumeService is an autogenerated mock type for the VolumeService type
type MockVolumeService struct {
	mock.Mock
}

type MockVolumeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVolumeService) EXPECT() *MockVolumeService_Expecter {
	return &MockVolumeService_Expecter{mock: &_m.Mock}
}

// BindIdentity provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) BindIdentity(ctx context.Context, volume string, caller *proto.Caller) (pathfs.FileSystem, error) {
	ret := _mock.Called(ctx, volume, caller)

	if len(ret) == 0 {
		panic("no return value specified for BindIdentity")
	}

	var r0 pathfs.FileSystem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *proto.Caller) (pathfs.FileSystem, error)); ok {
		return returnFunc(ctx, volume, caller)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *proto.Caller) pathfs.FileSystem); ok {
		r0 = returnFunc(ctx, volume, caller)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pathfs.FileSystem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *proto.Caller) error); ok {
		r1 = returnFunc(ctx, volume, caller)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_BindIdentity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindIdentity'
type MockVolumeService_BindIdentity_Call struct {
	*mock.Call
}

// BindIdentity is a helper method to define mock.On call
//   - ctx context.Context
//   - volume string
//   - caller *proto.Caller
func (_e *MockVolumeService_Expecter) BindIdentity(ctx interface{}, volume interface{}, caller interface{}) *MockVolumeService_BindIdentity_Call {
	return &MockVolumeService_BindIdentity_Call{Call: _e.mock.On("BindIdentity", ctx, volume, caller)}
}

func (_c *MockVolumeService_BindIdentity_Call) Run(run func(ctx context.Context, volume string, caller *proto.Caller)) *MockVolumeService_BindIdentity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *proto.Caller
		if args[2] != nil {
			arg2 = args[2].(*proto.Caller)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVolumeService_BindIdentity_Call) Return(fileSystem pathfs.FileSystem, err error) *MockVolumeService_BindIdentity_Call {
	_c.Call.Return(fileSystem, err)
	return _c
}

func (_c *MockVolumeService_BindIdentity_Call) RunAndReturn(run func(ctx context.Context, volume string, caller *proto.Caller) (pathfs.FileSystem, error)) *MockVolumeService_BindIdentity_Call {
	_c.Call.Return(run)
	return _c
}

// GetVolumeFileSystem provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) GetVolumeFileSystem(name string) (pathfs.FileSystem, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetVolumeFileSystem")
	}

	var r0 pathfs.FileSystem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (pathfs.FileSystem, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) pathfs.FileSystem); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pathfs.FileSystem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_GetVolumeFileSystem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVolumeFileSystem'
type MockVolumeService_GetVolumeFileSystem_Call struct {
	*mock.Call
}

// GetVolumeFileSystem is a helper method to define mock.On call
//   - name string
func (_e *MockVolumeService_Expecter) GetVolumeFileSystem(name interface{}) *MockVolumeService_GetVolumeFileSystem_Call {
	return &MockVolumeService_GetVolumeFileSystem_Call{Call: _e.mock.On("GetVolumeFileSystem", name)}
}

func (_c *MockVolumeService_GetVolumeFileSystem_Call) Run(run func(name string)) *MockVolumeService_GetVolumeFileSystem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVolumeService_GetVolumeFileSystem_Call) Return(fileSystem pathfs.FileSystem, err error) *MockVolumeService_GetVolumeFileSystem_Call {
	_c.Call.Return(fileSystem, err)
	return _c
}

func (_c *MockVolumeService_GetVolumeFileSystem_Call) RunAndReturn(run func(name string) (pathfs.FileSystem, error)) *MockVolumeService_GetVolumeFileSystem_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVolumeService
func (_mock *MockVolumeService) List() ([]common.Volume, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []common.Volume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]common.Volume, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []common.Volume); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]common.Volume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVolumeService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVolumeService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockVolumeService_Expecter) List() *MockVolumeService_List_Call {
	return &MockVolumeService_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockVolumeService_List_Call) Run(run func()) *MockVolumeService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVolumeService_List_Call) Return(volumes []common.Volume, err error) *MockVolumeService_List_Call {
	_c.Call.Return(volumes, err)
	return _c
}

func (_c *MockVolumeService_List_Call) RunAndReturn(run func() ([]common.Volume, error)) *MockVolumeService_List_Call {
	_c.Call.Return(run)
	return _c
}
