// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/file.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcFile_Open_FullMethodName          = "/gmountie.RpcFile/Open"
	RpcFile_Create_FullMethodName        = "/gmountie.RpcFile/Create"
	RpcFile_Read_FullMethodName          = "/gmountie.RpcFile/Read"
	RpcFile_Write_FullMethodName         = "/gmountie.RpcFile/Write"
	RpcFile_Release_FullMethodName       = "/gmountie.RpcFile/Release"
	RpcFile_Fsync_FullMethodName         = "/gmountie.RpcFile/Fsync"
	RpcFile_Flush_FullMethodName         = "/gmountie.RpcFile/Flush"
	RpcFile_WriteAndFlush_FullMethodName = "/gmountie.RpcFile/WriteAndFlush"
	RpcFile_GetLk_FullMethodName         = "/gmountie.RpcFile/GetLk"
	RpcFile_SetLk_FullMethodName         = "/gmountie.RpcFile/SetLk"
	RpcFile_SetLkw_FullMethodName        = "/gmountie.RpcFile/SetLkw"
	RpcFile_Allocate_FullMethodName      = "/gmountie.RpcFile/Allocate"
	RpcFile_CopyFileRange_FullMethodName = "/gmountie.RpcFile/CopyFileRange"
	RpcFile_Lseek_FullMethodName         = "/gmountie.RpcFile/Lseek"
)

// RpcFileClient is the client API for RpcFile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcFileClient interface {
	Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenReply, error)
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFrame], error)
	Write(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFrame, WriteReply], error)
	Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseReply, error)
	Fsync(ctx context.Context, in *FsyncRequest, opts ...grpc.CallOption) (*FsyncReply, error)
	Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushReply, error)
	WriteAndFlush(ctx context.Context, in *WriteAndFlushRequest, opts ...grpc.CallOption) (*WriteAndFlushReply, error)
	GetLk(ctx context.Context, in *GetLkRequest, opts ...grpc.CallOption) (*GetLkReply, error)
	SetLk(ctx context.Context, in *SetLkRequest, opts ...grpc.CallOption) (*SetLkReply, error)
	SetLkw(ctx context.Context, in *SetLkwRequest, opts ...grpc.CallOption) (*SetLkwReply, error)
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateReply, error)
	CopyFileRange(ctx context.Context, in *CopyFileRangeRequest, opts ...grpc.CallOption) (*CopyFileRangeReply, error)
	Lseek(ctx context.Context, in *LseekRequest, opts ...grpc.CallOption) (*LseekReply, error)
}

type rpcFileClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcFileClient(cc grpc.ClientConnInterface) RpcFileClient {
	return &rpcFileClient{cc}
}

func (c *rpcFileClient) Open(ctx context.Context, in *OpenRequest, opts ...grpc.CallOption) (*OpenReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenReply)
	err := c.cc.Invoke(ctx, RpcFile_Open_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReply)
	err := c.cc.Invoke(ctx, RpcFile_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RpcFile_ServiceDesc.Streams[0], RpcFile_Read_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRequest, ReadFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcFile_ReadClient = grpc.ServerStreamingClient[ReadFrame]

func (c *rpcFileClient) Write(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteFrame, WriteReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RpcFile_ServiceDesc.Streams[1], RpcFile_Write_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteFrame, WriteReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcFile_WriteClient = grpc.ClientStreamingClient[WriteFrame, WriteReply]

func (c *rpcFileClient) Release(ctx context.Context, in *ReleaseRequest, opts ...grpc.CallOption) (*ReleaseReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseReply)
	err := c.cc.Invoke(ctx, RpcFile_Release_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) Fsync(ctx context.Context, in *FsyncRequest, opts ...grpc.CallOption) (*FsyncReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FsyncReply)
	err := c.cc.Invoke(ctx, RpcFile_Fsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) Flush(ctx context.Context, in *FlushRequest, opts ...grpc.CallOption) (*FlushReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushReply)
	err := c.cc.Invoke(ctx, RpcFile_Flush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) WriteAndFlush(ctx context.Context, in *WriteAndFlushRequest, opts ...grpc.CallOption) (*WriteAndFlushReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteAndFlushReply)
	err := c.cc.Invoke(ctx, RpcFile_WriteAndFlush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) GetLk(ctx context.Context, in *GetLkRequest, opts ...grpc.CallOption) (*GetLkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLkReply)
	err := c.cc.Invoke(ctx, RpcFile_GetLk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) SetLk(ctx context.Context, in *SetLkRequest, opts ...grpc.CallOption) (*SetLkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLkReply)
	err := c.cc.Invoke(ctx, RpcFile_SetLk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) SetLkw(ctx context.Context, in *SetLkwRequest, opts ...grpc.CallOption) (*SetLkwReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetLkwReply)
	err := c.cc.Invoke(ctx, RpcFile_SetLkw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateReply)
	err := c.cc.Invoke(ctx, RpcFile_Allocate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) CopyFileRange(ctx context.Context, in *CopyFileRangeRequest, opts ...grpc.CallOption) (*CopyFileRangeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyFileRangeReply)
	err := c.cc.Invoke(ctx, RpcFile_CopyFileRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFileClient) Lseek(ctx context.Context, in *LseekRequest, opts ...grpc.CallOption) (*LseekReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LseekReply)
	err := c.cc.Invoke(ctx, RpcFile_Lseek_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcFileServer is the server API for RpcFile service.
// All implementations must embed UnimplementedRpcFileServer
// for forward compatibility.
type RpcFileServer interface {
	Open(context.Context, *OpenRequest) (*OpenReply, error)
	Create(context.Context, *CreateRequest) (*CreateReply, error)
	Read(*ReadRequest, grpc.ServerStreamingServer[ReadFrame]) error
	Write(grpc.ClientStreamingServer[WriteFrame, WriteReply]) error
	Release(context.Context, *ReleaseRequest) (*ReleaseReply, error)
	Fsync(context.Context, *FsyncRequest) (*FsyncReply, error)
	Flush(context.Context, *FlushRequest) (*FlushReply, error)
	WriteAndFlush(context.Context, *WriteAndFlushRequest) (*WriteAndFlushReply, error)
	GetLk(context.Context, *GetLkRequest) (*GetLkReply, error)
	SetLk(context.Context, *SetLkRequest) (*SetLkReply, error)
	SetLkw(context.Context, *SetLkwRequest) (*SetLkwReply, error)
	Allocate(context.Context, *AllocateRequest) (*AllocateReply, error)
	CopyFileRange(context.Context, *CopyFileRangeRequest) (*CopyFileRangeReply, error)
	Lseek(context.Context, *LseekRequest) (*LseekReply, error)
	mustEmbedUnimplementedRpcFileServer()
}

// UnimplementedRpcFileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcFileServer struct{}

func (UnimplementedRpcFileServer) Open(context.Context, *OpenRequest) (*OpenReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedRpcFileServer) Create(context.Context, *CreateRequest) (*CreateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedRpcFileServer) Read(*ReadRequest, grpc.ServerStreamingServer[ReadFrame]) error {
	return status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedRpcFileServer) Write(grpc.ClientStreamingServer[WriteFrame, WriteReply]) error {
	return status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedRpcFileServer) Release(context.Context, *ReleaseRequest) (*ReleaseReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Release not implemented")
}
func (UnimplementedRpcFileServer) Fsync(context.Context, *FsyncRequest) (*FsyncReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Fsync not implemented")
}
func (UnimplementedRpcFileServer) Flush(context.Context, *FlushRequest) (*FlushReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Flush not implemented")
}
func (UnimplementedRpcFileServer) WriteAndFlush(context.Context, *WriteAndFlushRequest) (*WriteAndFlushReply, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteAndFlush not implemented")
}
func (UnimplementedRpcFileServer) GetLk(context.Context, *GetLkRequest) (*GetLkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLk not implemented")
}
func (UnimplementedRpcFileServer) SetLk(context.Context, *SetLkRequest) (*SetLkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLk not implemented")
}
func (UnimplementedRpcFileServer) SetLkw(context.Context, *SetLkwRequest) (*SetLkwReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SetLkw not implemented")
}
func (UnimplementedRpcFileServer) Allocate(context.Context, *AllocateRequest) (*AllocateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedRpcFileServer) CopyFileRange(context.Context, *CopyFileRangeRequest) (*CopyFileRangeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyFileRange not implemented")
}
func (UnimplementedRpcFileServer) Lseek(context.Context, *LseekRequest) (*LseekReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Lseek not implemented")
}
func (UnimplementedRpcFileServer) mustEmbedUnimplementedRpcFileServer() {}
func (UnimplementedRpcFileServer) testEmbeddedByValue()                 {}

// UnsafeRpcFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcFileServer will
// result in compilation errors.
type UnsafeRpcFileServer interface {
	mustEmbedUnimplementedRpcFileServer()
}

func RegisterRpcFileServer(s grpc.ServiceRegistrar, srv RpcFileServer) {
	// If the following call panics, it indicates UnimplementedRpcFileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcFile_ServiceDesc, srv)
}

func _RpcFile_Open_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).Open(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_Open_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).Open(ctx, req.(*OpenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RpcFileServer).Read(m, &grpc.GenericServerStream[ReadRequest, ReadFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcFile_ReadServer = grpc.ServerStreamingServer[ReadFrame]

func _RpcFile_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RpcFileServer).Write(&grpc.GenericServerStream[WriteFrame, WriteReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcFile_WriteServer = grpc.ClientStreamingServer[WriteFrame, WriteReply]

func _RpcFile_Release_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).Release(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_Release_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).Release(ctx, req.(*ReleaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_Fsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FsyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).Fsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_Fsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).Fsync(ctx, req.(*FsyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_Flush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).Flush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_Flush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).Flush(ctx, req.(*FlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_WriteAndFlush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WriteAndFlushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).WriteAndFlush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_WriteAndFlush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).WriteAndFlush(ctx, req.(*WriteAndFlushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_GetLk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).GetLk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_GetLk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).GetLk(ctx, req.(*GetLkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_SetLk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).SetLk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_SetLk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).SetLk(ctx, req.(*SetLkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_SetLkw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetLkwRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).SetLkw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_SetLkw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).SetLkw(ctx, req.(*SetLkwRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_Allocate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_CopyFileRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyFileRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).CopyFileRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_CopyFileRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).CopyFileRange(ctx, req.(*CopyFileRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFile_Lseek_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LseekRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFileServer).Lseek(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFile_Lseek_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFileServer).Lseek(ctx, req.(*LseekRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcFile_ServiceDesc is the grpc.ServiceDesc for RpcFile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcFile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gmountie.RpcFile",
	HandlerType: (*RpcFileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Open",
			Handler:    _RpcFile_Open_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _RpcFile_Create_Handler,
		},
		{
			MethodName: "Release",
			Handler:    _RpcFile_Release_Handler,
		},
		{
			MethodName: "Fsync",
			Handler:    _RpcFile_Fsync_Handler,
		},
		{
			MethodName: "Flush",
			Handler:    _RpcFile_Flush_Handler,
		},
		{
			MethodName: "WriteAndFlush",
			Handler:    _RpcFile_WriteAndFlush_Handler,
		},
		{
			MethodName: "GetLk",
			Handler:    _RpcFile_GetLk_Handler,
		},
		{
			MethodName: "SetLk",
			Handler:    _RpcFile_SetLk_Handler,
		},
		{
			MethodName: "SetLkw",
			Handler:    _RpcFile_SetLkw_Handler,
		},
		{
			MethodName: "Allocate",
			Handler:    _RpcFile_Allocate_Handler,
		},
		{
			MethodName: "CopyFileRange",
			Handler:    _RpcFile_CopyFileRange_Handler,
		},
		{
			MethodName: "Lseek",
			Handler:    _RpcFile_Lseek_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _RpcFile_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Write",
			Handler:       _RpcFile_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/proto/file.proto",
}
