// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/file.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint64                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint64                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Typ           uint32                 `protobuf:"varint,3,opt,name=typ,proto3" json:"typ,omitempty"`
	Pid           uint32                 `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileLock) Reset() {
	*x = FileLock{}
	mi := &file_api_proto_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileLock) ProtoMessage() {}

func (x *FileLock) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileLock.ProtoReflect.Descriptor instead.
func (*FileLock) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileLock) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *FileLock) GetEnd() uint64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *FileLock) GetTyp() uint32 {
	if x != nil {
		return x.Typ
	}
	return 0
}

func (x *FileLock) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_api_proto_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{1}
}

func (x *OpenRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *OpenRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *OpenRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *OpenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type OpenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            uint64                 `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenReply) Reset() {
	*x = OpenReply{}
	mi := &file_api_proto_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenReply) ProtoMessage() {}

func (x *OpenReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenReply.ProtoReflect.Descriptor instead.
func (*OpenReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{2}
}

func (x *OpenReply) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *OpenReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_api_proto_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *CreateRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *CreateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *CreateRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CreateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type CreateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fd            uint64                 `protobuf:"varint,1,opt,name=fd,proto3" json:"fd,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Attributes    *Attr                  `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"` // lets the client fill EntryOut without a post-create GetAttr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReply) Reset() {
	*x = CreateReply{}
	mi := &file_api_proto_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReply) ProtoMessage() {}

func (x *CreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReply.ProtoReflect.Descriptor instead.
func (*CreateReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{4}
}

func (x *CreateReply) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *CreateReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateReply) GetAttributes() *Attr {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_api_proto_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ReadRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ReadRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ReadFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFrame) Reset() {
	*x = ReadFrame{}
	mi := &file_api_proto_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFrame) ProtoMessage() {}

func (x *ReadFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFrame.ProtoReflect.Descriptor instead.
func (*ReadFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{6}
}

func (x *ReadFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ReadFrame) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// WriteFrame is a single chunk of a client-streaming Write RPC. The FIRST
// frame carries the full header (volume/fd/session_id/request_id/offset).
// Subsequent frames carry only `data` — header fields MUST be either
// zero-valued or exactly equal to frame 1 (the server pins the values
// from frame 1 and rejects any other value as InvalidArgument).
type WriteFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFrame) Reset() {
	*x = WriteFrame{}
	mi := &file_api_proto_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFrame) ProtoMessage() {}

func (x *WriteFrame) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFrame.ProtoReflect.Descriptor instead.
func (*WriteFrame) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{7}
}

func (x *WriteFrame) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *WriteFrame) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *WriteFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WriteFrame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *WriteFrame) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       uint32                 `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteReply) Reset() {
	*x = WriteReply{}
	mi := &file_api_proto_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteReply) ProtoMessage() {}

func (x *WriteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteReply.ProtoReflect.Descriptor instead.
func (*WriteReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{8}
}

func (x *WriteReply) GetWritten() uint32 {
	if x != nil {
		return x.Written
	}
	return 0
}

func (x *WriteReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Flags         int64                  `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsyncRequest) Reset() {
	*x = FsyncRequest{}
	mi := &file_api_proto_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsyncRequest) ProtoMessage() {}

func (x *FsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsyncRequest.ProtoReflect.Descriptor instead.
func (*FsyncRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{9}
}

func (x *FsyncRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *FsyncRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *FsyncRequest) GetFlags() int64 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *FsyncRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FsyncReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsyncReply) Reset() {
	*x = FsyncReply{}
	mi := &file_api_proto_file_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsyncReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsyncReply) ProtoMessage() {}

func (x *FsyncReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsyncReply.ProtoReflect.Descriptor instead.
func (*FsyncReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{10}
}

func (x *FsyncReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_api_proto_file_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{11}
}

func (x *ReleaseRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ReleaseRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *ReleaseRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ReleaseReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseReply) Reset() {
	*x = ReleaseReply{}
	mi := &file_api_proto_file_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseReply) ProtoMessage() {}

func (x *ReleaseReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseReply.ProtoReflect.Descriptor instead.
func (*ReleaseReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{12}
}

type FlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRequest) Reset() {
	*x = FlushRequest{}
	mi := &file_api_proto_file_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRequest) ProtoMessage() {}

func (x *FlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRequest.ProtoReflect.Descriptor instead.
func (*FlushRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{13}
}

func (x *FlushRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *FlushRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *FlushRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type FlushReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushReply) Reset() {
	*x = FlushReply{}
	mi := &file_api_proto_file_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushReply) ProtoMessage() {}

func (x *FlushReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushReply.ProtoReflect.Descriptor instead.
func (*FlushReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{14}
}

func (x *FlushReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// WriteAndFlush fuses the deferred coalesced write and the flush into one RPC
// at FUSE FLUSH time (the errno reaches the app's close()). data may be empty
// (a pure flush). Unary: only used for buffers <= WriteCoalesceBytes.
type WriteAndFlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAndFlushRequest) Reset() {
	*x = WriteAndFlushRequest{}
	mi := &file_api_proto_file_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAndFlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAndFlushRequest) ProtoMessage() {}

func (x *WriteAndFlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAndFlushRequest.ProtoReflect.Descriptor instead.
func (*WriteAndFlushRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{15}
}

func (x *WriteAndFlushRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *WriteAndFlushRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *WriteAndFlushRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteAndFlushRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *WriteAndFlushRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type WriteAndFlushReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       uint32                 `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // write errno if the write failed, else the flush errno
	FinalAttr     *Attr                  `protobuf:"bytes,3,opt,name=final_attr,json=finalAttr,proto3" json:"final_attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteAndFlushReply) Reset() {
	*x = WriteAndFlushReply{}
	mi := &file_api_proto_file_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteAndFlushReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteAndFlushReply) ProtoMessage() {}

func (x *WriteAndFlushReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteAndFlushReply.ProtoReflect.Descriptor instead.
func (*WriteAndFlushReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{16}
}

func (x *WriteAndFlushReply) GetWritten() uint32 {
	if x != nil {
		return x.Written
	}
	return 0
}

func (x *WriteAndFlushReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *WriteAndFlushReply) GetFinalAttr() *Attr {
	if x != nil {
		return x.FinalAttr
	}
	return nil
}

type GetLkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Owner         uint64                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	Lk            *FileLock              `protobuf:"bytes,5,opt,name=lk,proto3" json:"lk,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLkRequest) Reset() {
	*x = GetLkRequest{}
	mi := &file_api_proto_file_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLkRequest) ProtoMessage() {}

func (x *GetLkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLkRequest.ProtoReflect.Descriptor instead.
func (*GetLkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{17}
}

func (x *GetLkRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *GetLkRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *GetLkRequest) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *GetLkRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *GetLkRequest) GetLk() *FileLock {
	if x != nil {
		return x.Lk
	}
	return nil
}

func (x *GetLkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetLkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Lk            *FileLock              `protobuf:"bytes,2,opt,name=lk,proto3" json:"lk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLkReply) Reset() {
	*x = GetLkReply{}
	mi := &file_api_proto_file_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLkReply) ProtoMessage() {}

func (x *GetLkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLkReply.ProtoReflect.Descriptor instead.
func (*GetLkReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{18}
}

func (x *GetLkReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetLkReply) GetLk() *FileLock {
	if x != nil {
		return x.Lk
	}
	return nil
}

type SetLkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Owner         uint64                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	Lk            *FileLock              `protobuf:"bytes,5,opt,name=lk,proto3" json:"lk,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLkRequest) Reset() {
	*x = SetLkRequest{}
	mi := &file_api_proto_file_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLkRequest) ProtoMessage() {}

func (x *SetLkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLkRequest.ProtoReflect.Descriptor instead.
func (*SetLkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{19}
}

func (x *SetLkRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *SetLkRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *SetLkRequest) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *SetLkRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *SetLkRequest) GetLk() *FileLock {
	if x != nil {
		return x.Lk
	}
	return nil
}

func (x *SetLkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SetLkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLkReply) Reset() {
	*x = SetLkReply{}
	mi := &file_api_proto_file_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLkReply) ProtoMessage() {}

func (x *SetLkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLkReply.ProtoReflect.Descriptor instead.
func (*SetLkReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{20}
}

func (x *SetLkReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type SetLkwRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Fd            uint64                 `protobuf:"varint,2,opt,name=fd,proto3" json:"fd,omitempty"`
	Owner         uint64                 `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Flags         uint32                 `protobuf:"varint,4,opt,name=flags,proto3" json:"flags,omitempty"`
	Lk            *FileLock              `protobuf:"bytes,5,opt,name=lk,proto3" json:"lk,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLkwRequest) Reset() {
	*x = SetLkwRequest{}
	mi := &file_api_proto_file_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLkwRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLkwRequest) ProtoMessage() {}

func (x *SetLkwRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLkwRequest.ProtoReflect.Descriptor instead.
func (*SetLkwRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{21}
}

func (x *SetLkwRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *SetLkwRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *SetLkwRequest) GetOwner() uint64 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *SetLkwRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *SetLkwRequest) GetLk() *FileLock {
	if x != nil {
		return x.Lk
	}
	return nil
}

func (x *SetLkwRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SetLkwReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetLkwReply) Reset() {
	*x = SetLkwReply{}
	mi := &file_api_proto_file_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetLkwReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLkwReply) ProtoMessage() {}

func (x *SetLkwReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLkwReply.ProtoReflect.Descriptor instead.
func (*SetLkwReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{22}
}

func (x *SetLkwReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AllocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Fd            uint64                 `protobuf:"varint,3,opt,name=fd,proto3" json:"fd,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Off           uint64                 `protobuf:"varint,5,opt,name=off,proto3" json:"off,omitempty"`
	Size          uint64                 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`
	SessionId     string                 `protobuf:"bytes,8,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_api_proto_file_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{23}
}

func (x *AllocateRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *AllocateRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *AllocateRequest) GetFd() uint64 {
	if x != nil {
		return x.Fd
	}
	return 0
}

func (x *AllocateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AllocateRequest) GetOff() uint64 {
	if x != nil {
		return x.Off
	}
	return 0
}

func (x *AllocateRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AllocateRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *AllocateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type AllocateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateReply) Reset() {
	*x = AllocateReply{}
	mi := &file_api_proto_file_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateReply) ProtoMessage() {}

func (x *AllocateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_file_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateReply.ProtoReflect.Descriptor instead.
func (*AllocateReply) Descriptor() ([]byte, []int) {
	return file_api_proto_file_proto_rawDescGZIP(), []int{24}
}

func (x *AllocateReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_api_proto_file_proto protoreflect.FileDescriptor

const file_api_proto_file_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/file.proto\x12\bgmountie\x1a\x16api/proto/common.proto\x1a\x12api/proto/fs.proto\"V\n" +
	"\bFileLock\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x04R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x04R\x03end\x12\x10\n" +
	"\x03typ\x18\x03 \x01(\rR\x03typ\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\rR\x03pid\"\xb7\x01\n" +
	"\vOpenRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"3\n" +
	"\tOpenReply\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x04R\x02fd\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\xcd\x01\n" +
	"\rCreateRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"e\n" +
	"\vCreateReply\x12\x0e\n" +
	"\x02fd\x18\x01 \x01(\x04R\x02fd\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12.\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x0e.gmountie.AttrR\n" +
	"attributes\"\x80\x01\n" +
	"\vReadRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"7\n" +
	"\tReadFrame\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\x9e\x01\n" +
	"\n" +
	"WriteFrame\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\">\n" +
	"\n" +
	"WriteReply\x12\x18\n" +
	"\awritten\x18\x01 \x01(\rR\awritten\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"k\n" +
	"\fFsyncRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\x03R\x05flags\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\"$\n" +
	"\n" +
	"FsyncReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"W\n" +
	"\x0eReleaseRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x0e\n" +
	"\fReleaseReply\"U\n" +
	"\fFlushRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"$\n" +
	"\n" +
	"FlushReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\x89\x01\n" +
	"\x14WriteAndFlushRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"u\n" +
	"\x12WriteAndFlushReply\x12\x18\n" +
	"\awritten\x18\x01 \x01(\rR\awritten\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12-\n" +
	"\n" +
	"final_attr\x18\x03 \x01(\v2\x0e.gmountie.AttrR\tfinalAttr\"\xa5\x01\n" +
	"\fGetLkRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\x04R\x05owner\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12\"\n" +
	"\x02lk\x18\x05 \x01(\v2\x12.gmountie.FileLockR\x02lk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"H\n" +
	"\n" +
	"GetLkReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\"\n" +
	"\x02lk\x18\x02 \x01(\v2\x12.gmountie.FileLockR\x02lk\"\xa5\x01\n" +
	"\fSetLkRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\x04R\x05owner\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12\"\n" +
	"\x02lk\x18\x05 \x01(\v2\x12.gmountie.FileLockR\x02lk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"$\n" +
	"\n" +
	"SetLkReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\xa6\x01\n" +
	"\rSetLkwRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x0e\n" +
	"\x02fd\x18\x02 \x01(\x04R\x02fd\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\x04R\x05owner\x12\x14\n" +
	"\x05flags\x18\x04 \x01(\rR\x05flags\x12\"\n" +
	"\x02lk\x18\x05 \x01(\v2\x12.gmountie.FileLockR\x02lk\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"%\n" +
	"\vSetLkwReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\xd0\x01\n" +
	"\x0fAllocateRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x0e\n" +
	"\x02fd\x18\x03 \x01(\x04R\x02fd\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x10\n" +
	"\x03off\x18\x05 \x01(\x04R\x03off\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x04R\x04size\x12\x12\n" +
	"\x04mode\x18\a \x01(\rR\x04mode\x12\x1d\n" +
	"\n" +
	"session_id\x18\b \x01(\tR\tsessionId\"'\n" +
	"\rAllocateReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status2\xc6\x05\n" +
	"\aRpcFile\x122\n" +
	"\x04Open\x12\x15.gmountie.OpenRequest\x1a\x13.gmountie.OpenReply\x128\n" +
	"\x06Create\x12\x17.gmountie.CreateRequest\x1a\x15.gmountie.CreateReply\x124\n" +
	"\x04Read\x12\x15.gmountie.ReadRequest\x1a\x13.gmountie.ReadFrame0\x01\x125\n" +
	"\x05Write\x12\x14.gmountie.WriteFrame\x1a\x14.gmountie.WriteReply(\x01\x12;\n" +
	"\aRelease\x12\x18.gmountie.ReleaseRequest\x1a\x16.gmountie.ReleaseReply\x125\n" +
	"\x05Fsync\x12\x16.gmountie.FsyncRequest\x1a\x14.gmountie.FsyncReply\x125\n" +
	"\x05Flush\x12\x16.gmountie.FlushRequest\x1a\x14.gmountie.FlushReply\x12M\n" +
	"\rWriteAndFlush\x12\x1e.gmountie.WriteAndFlushRequest\x1a\x1c.gmountie.WriteAndFlushReply\x125\n" +
	"\x05GetLk\x12\x16.gmountie.GetLkRequest\x1a\x14.gmountie.GetLkReply\x125\n" +
	"\x05SetLk\x12\x16.gmountie.SetLkRequest\x1a\x14.gmountie.SetLkReply\x128\n" +
	"\x06SetLkw\x12\x17.gmountie.SetLkwRequest\x1a\x15.gmountie.SetLkwReply\x12>\n" +
	"\bAllocate\x12\x19.gmountie.AllocateRequest\x1a\x17.gmountie.AllocateReplyB\vZ\tpkg/protob\x06proto3"

var (
	file_api_proto_file_proto_rawDescOnce sync.Once
	file_api_proto_file_proto_rawDescData []byte
)

func file_api_proto_file_proto_rawDescGZIP() []byte {
	file_api_proto_file_proto_rawDescOnce.Do(func() {
		file_api_proto_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_file_proto_rawDesc), len(file_api_proto_file_proto_rawDesc)))
	})
	return file_api_proto_file_proto_rawDescData
}

var file_api_proto_file_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_proto_file_proto_goTypes = []any{
	(*FileLock)(nil),             // 0: gmountie.FileLock
	(*OpenRequest)(nil),          // 1: gmountie.OpenRequest
	(*OpenReply)(nil),            // 2: gmountie.OpenReply
	(*CreateRequest)(nil),        // 3: gmountie.CreateRequest
	(*CreateReply)(nil),          // 4: gmountie.CreateReply
	(*ReadRequest)(nil),          // 5: gmountie.ReadRequest
	(*ReadFrame)(nil),            // 6: gmountie.ReadFrame
	(*WriteFrame)(nil),           // 7: gmountie.WriteFrame
	(*WriteReply)(nil),           // 8: gmountie.WriteReply
	(*FsyncRequest)(nil),         // 9: gmountie.FsyncRequest
	(*FsyncReply)(nil),           // 10: gmountie.FsyncReply
	(*ReleaseRequest)(nil),       // 11: gmountie.ReleaseRequest
	(*ReleaseReply)(nil),         // 12: gmountie.ReleaseReply
	(*FlushRequest)(nil),         // 13: gmountie.FlushRequest
	(*FlushReply)(nil),           // 14: gmountie.FlushReply
	(*WriteAndFlushRequest)(nil), // 15: gmountie.WriteAndFlushRequest
	(*WriteAndFlushReply)(nil),   // 16: gmountie.WriteAndFlushReply
	(*GetLkRequest)(nil),         // 17: gmountie.GetLkRequest
	(*GetLkReply)(nil),           // 18: gmountie.GetLkReply
	(*SetLkRequest)(nil),         // 19: gmountie.SetLkRequest
	(*SetLkReply)(nil),           // 20: gmountie.SetLkReply
	(*SetLkwRequest)(nil),        // 21: gmountie.SetLkwRequest
	(*SetLkwReply)(nil),          // 22: gmountie.SetLkwReply
	(*AllocateRequest)(nil),      // 23: gmountie.AllocateRequest
	(*AllocateReply)(nil),        // 24: gmountie.AllocateReply
	(*Caller)(nil),               // 25: gmountie.Caller
	(*Attr)(nil),                 // 26: gmountie.Attr
}
var file_api_proto_file_proto_depIdxs = []int32{
	25, // 0: gmountie.OpenRequest.caller:type_name -> gmountie.Caller
	25, // 1: gmountie.CreateRequest.caller:type_name -> gmountie.Caller
	26, // 2: gmountie.CreateReply.attributes:type_name -> gmountie.Attr
	26, // 3: gmountie.WriteAndFlushReply.final_attr:type_name -> gmountie.Attr
	0,  // 4: gmountie.GetLkRequest.lk:type_name -> gmountie.FileLock
	0,  // 5: gmountie.GetLkReply.lk:type_name -> gmountie.FileLock
	0,  // 6: gmountie.SetLkRequest.lk:type_name -> gmountie.FileLock
	0,  // 7: gmountie.SetLkwRequest.lk:type_name -> gmountie.FileLock
	25, // 8: gmountie.AllocateRequest.caller:type_name -> gmountie.Caller
	1,  // 9: gmountie.RpcFile.Open:input_type -> gmountie.OpenRequest
	3,  // 10: gmountie.RpcFile.Create:input_type -> gmountie.CreateRequest
	5,  // 11: gmountie.RpcFile.Read:input_type -> gmountie.ReadRequest
	7,  // 12: gmountie.RpcFile.Write:input_type -> gmountie.WriteFrame
	11, // 13: gmountie.RpcFile.Release:input_type -> gmountie.ReleaseRequest
	9,  // 14: gmountie.RpcFile.Fsync:input_type -> gmountie.FsyncRequest
	13, // 15: gmountie.RpcFile.Flush:input_type -> gmountie.FlushRequest
	15, // 16: gmountie.RpcFile.WriteAndFlush:input_type -> gmountie.WriteAndFlushRequest
	17, // 17: gmountie.RpcFile.GetLk:input_type -> gmountie.GetLkRequest
	19, // 18: gmountie.RpcFile.SetLk:input_type -> gmountie.SetLkRequest
	21, // 19: gmountie.RpcFile.SetLkw:input_type -> gmountie.SetLkwRequest
	23, // 20: gmountie.RpcFile.Allocate:input_type -> gmountie.AllocateRequest
	2,  // 21: gmountie.RpcFile.Open:output_type -> gmountie.OpenReply
	4,  // 22: gmountie.RpcFile.Create:output_type -> gmountie.CreateReply
	6,  // 23: gmountie.RpcFile.Read:output_type -> gmountie.ReadFrame
	8,  // 24: gmountie.RpcFile.Write:output_type -> gmountie.WriteReply
	12, // 25: gmountie.RpcFile.Release:output_type -> gmountie.ReleaseReply
	10, // 26: gmountie.RpcFile.Fsync:output_type -> gmountie.FsyncReply
	14, // 27: gmountie.RpcFile.Flush:output_type -> gmountie.FlushReply
	16, // 28: gmountie.RpcFile.WriteAndFlush:output_type -> gmountie.WriteAndFlushReply
	18, // 29: gmountie.RpcFile.GetLk:output_type -> gmountie.GetLkReply
	20, // 30: gmountie.RpcFile.SetLk:output_type -> gmountie.SetLkReply
	22, // 31: gmountie.RpcFile.SetLkw:output_type -> gmountie.SetLkwReply
	24, // 32: gmountie.RpcFile.Allocate:output_type -> gmountie.AllocateReply
	21, // [21:33] is the sub-list for method output_type
	9,  // [9:21] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_file_proto_init() }
func file_api_proto_file_proto_init() {
	if File_api_proto_file_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	file_api_proto_fs_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_file_proto_rawDesc), len(file_api_proto_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_file_proto_goTypes,
		DependencyIndexes: file_api_proto_file_proto_depIdxs,
		MessageInfos:      file_api_proto_file_proto_msgTypes,
	}.Build()
	File_api_proto_file_proto = out.File
	file_api_proto_file_proto_goTypes = nil
	file_api_proto_file_proto_depIdxs = nil
}
