// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/fs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeEvent_Kind int32

const (
	SubscribeEvent_KIND_UNSPECIFIED SubscribeEvent_Kind = 0
	SubscribeEvent_MUTATED          SubscribeEvent_Kind = 1 // Write / Truncate / Chmod / Chown / Allocate / Create / Mkdir
	SubscribeEvent_DELETED          SubscribeEvent_Kind = 2 // Unlink / Rmdir
	SubscribeEvent_RENAMED          SubscribeEvent_Kind = 3 // Rename — new_path populated
	SubscribeEvent_HEARTBEAT        SubscribeEvent_Kind = 4 // periodic, no path
)

// Enum value maps for SubscribeEvent_Kind.
var (
	SubscribeEvent_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "MUTATED",
		2: "DELETED",
		3: "RENAMED",
		4: "HEARTBEAT",
	}
	SubscribeEvent_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"MUTATED":          1,
		"DELETED":          2,
		"RENAMED":          3,
		"HEARTBEAT":        4,
	}
)

func (x SubscribeEvent_Kind) Enum() *SubscribeEvent_Kind {
	p := new(SubscribeEvent_Kind)
	*p = x
	return p
}

func (x SubscribeEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscribeEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_fs_proto_enumTypes[0].Descriptor()
}

func (SubscribeEvent_Kind) Type() protoreflect.EnumType {
	return &file_api_proto_fs_proto_enumTypes[0]
}

func (x SubscribeEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscribeEvent_Kind.Descriptor instead.
func (SubscribeEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{9, 0}
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          uint32                 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ino           uint64                 `protobuf:"varint,3,opt,name=ino,proto3" json:"ino,omitempty"`
	Off           uint64                 `protobuf:"varint,4,opt,name=off,proto3" json:"off,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_api_proto_fs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{0}
}

func (x *DirEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *DirEntry) GetOff() uint64 {
	if x != nil {
		return x.Off
	}
	return 0
}

type Attr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ino           uint64                 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Blocks        uint64                 `protobuf:"varint,3,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Atime         uint64                 `protobuf:"varint,4,opt,name=atime,proto3" json:"atime,omitempty"`
	Mtime         uint64                 `protobuf:"varint,5,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Ctime         uint64                 `protobuf:"varint,6,opt,name=ctime,proto3" json:"ctime,omitempty"`
	Atimensec     uint32                 `protobuf:"varint,7,opt,name=atimensec,proto3" json:"atimensec,omitempty"`
	Mtimensec     uint32                 `protobuf:"varint,8,opt,name=mtimensec,proto3" json:"mtimensec,omitempty"`
	Ctimensec     uint32                 `protobuf:"varint,9,opt,name=ctimensec,proto3" json:"ctimensec,omitempty"`
	Mode          uint32                 `protobuf:"varint,10,opt,name=mode,proto3" json:"mode,omitempty"`
	Nlink         uint32                 `protobuf:"varint,11,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Owner         *Owner                 `protobuf:"bytes,12,opt,name=owner,proto3" json:"owner,omitempty"`
	Uid           uint32                 `protobuf:"varint,13,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,14,opt,name=gid,proto3" json:"gid,omitempty"`
	Rdev          uint32                 `protobuf:"varint,15,opt,name=rdev,proto3" json:"rdev,omitempty"`
	Blksize       uint32                 `protobuf:"varint,16,opt,name=blksize,proto3" json:"blksize,omitempty"`
	Padding       uint32                 `protobuf:"varint,17,opt,name=padding,proto3" json:"padding,omitempty"`
	Version       uint64                 `protobuf:"varint,18,opt,name=version,proto3" json:"version,omitempty"` // Sub-spec D: VersionFromAttr(mtime, size, ctime). Zero from older clients.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attr) Reset() {
	*x = Attr{}
	mi := &file_api_proto_fs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attr) ProtoMessage() {}

func (x *Attr) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attr.ProtoReflect.Descriptor instead.
func (*Attr) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{1}
}

func (x *Attr) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *Attr) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Attr) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *Attr) GetAtime() uint64 {
	if x != nil {
		return x.Atime
	}
	return 0
}

func (x *Attr) GetMtime() uint64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *Attr) GetCtime() uint64 {
	if x != nil {
		return x.Ctime
	}
	return 0
}

func (x *Attr) GetAtimensec() uint32 {
	if x != nil {
		return x.Atimensec
	}
	return 0
}

func (x *Attr) GetMtimensec() uint32 {
	if x != nil {
		return x.Mtimensec
	}
	return 0
}

func (x *Attr) GetCtimensec() uint32 {
	if x != nil {
		return x.Ctimensec
	}
	return 0
}

func (x *Attr) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *Attr) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *Attr) GetOwner() *Owner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *Attr) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Attr) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *Attr) GetRdev() uint32 {
	if x != nil {
		return x.Rdev
	}
	return 0
}

func (x *Attr) GetBlksize() uint32 {
	if x != nil {
		return x.Blksize
	}
	return 0
}

func (x *Attr) GetPadding() uint32 {
	if x != nil {
		return x.Padding
	}
	return 0
}

func (x *Attr) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StatFsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFsRequest) Reset() {
	*x = StatFsRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFsRequest) ProtoMessage() {}

func (x *StatFsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFsRequest.ProtoReflect.Descriptor instead.
func (*StatFsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{2}
}

func (x *StatFsRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *StatFsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatFsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        uint64                 `protobuf:"varint,1,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Bfree         uint64                 `protobuf:"varint,2,opt,name=bfree,proto3" json:"bfree,omitempty"`
	Bavail        uint64                 `protobuf:"varint,3,opt,name=bavail,proto3" json:"bavail,omitempty"`
	Files         uint64                 `protobuf:"varint,4,opt,name=files,proto3" json:"files,omitempty"`
	Ffree         uint64                 `protobuf:"varint,5,opt,name=ffree,proto3" json:"ffree,omitempty"`
	Bsize         uint32                 `protobuf:"varint,6,opt,name=bsize,proto3" json:"bsize,omitempty"`
	Namelen       uint32                 `protobuf:"varint,7,opt,name=namelen,proto3" json:"namelen,omitempty"`
	Frsize        uint32                 `protobuf:"varint,8,opt,name=frsize,proto3" json:"frsize,omitempty"`
	Padding       uint32                 `protobuf:"varint,9,opt,name=padding,proto3" json:"padding,omitempty"`
	Spare         []uint32               `protobuf:"varint,10,rep,packed,name=spare,proto3" json:"spare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFsReply) Reset() {
	*x = StatFsReply{}
	mi := &file_api_proto_fs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFsReply) ProtoMessage() {}

func (x *StatFsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFsReply.ProtoReflect.Descriptor instead.
func (*StatFsReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{3}
}

func (x *StatFsReply) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *StatFsReply) GetBfree() uint64 {
	if x != nil {
		return x.Bfree
	}
	return 0
}

func (x *StatFsReply) GetBavail() uint64 {
	if x != nil {
		return x.Bavail
	}
	return 0
}

func (x *StatFsReply) GetFiles() uint64 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *StatFsReply) GetFfree() uint64 {
	if x != nil {
		return x.Ffree
	}
	return 0
}

func (x *StatFsReply) GetBsize() uint32 {
	if x != nil {
		return x.Bsize
	}
	return 0
}

func (x *StatFsReply) GetNamelen() uint32 {
	if x != nil {
		return x.Namelen
	}
	return 0
}

func (x *StatFsReply) GetFrsize() uint32 {
	if x != nil {
		return x.Frsize
	}
	return 0
}

func (x *StatFsReply) GetPadding() uint32 {
	if x != nil {
		return x.Padding
	}
	return 0
}

func (x *StatFsReply) GetSpare() []uint32 {
	if x != nil {
		return x.Spare
	}
	return nil
}

type GetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrRequest) Reset() {
	*x = GetAttrRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrRequest) ProtoMessage() {}

func (x *GetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrRequest.ProtoReflect.Descriptor instead.
func (*GetAttrRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{4}
}

func (x *GetAttrRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *GetAttrRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *GetAttrRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetAttrReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    *Attr                  `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrReply) Reset() {
	*x = GetAttrReply{}
	mi := &file_api_proto_fs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrReply) ProtoMessage() {}

func (x *GetAttrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrReply.ProtoReflect.Descriptor instead.
func (*GetAttrReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{5}
}

func (x *GetAttrReply) GetAttributes() *Attr {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *GetAttrReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetAttrIfChangedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	KnownVersion  uint64                 `protobuf:"varint,3,opt,name=known_version,json=knownVersion,proto3" json:"known_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrIfChangedRequest) Reset() {
	*x = GetAttrIfChangedRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrIfChangedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrIfChangedRequest) ProtoMessage() {}

func (x *GetAttrIfChangedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrIfChangedRequest.ProtoReflect.Descriptor instead.
func (*GetAttrIfChangedRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{6}
}

func (x *GetAttrIfChangedRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *GetAttrIfChangedRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetAttrIfChangedRequest) GetKnownVersion() uint64 {
	if x != nil {
		return x.KnownVersion
	}
	return 0
}

type GetAttrIfChangedReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NotModified   bool                   `protobuf:"varint,1,opt,name=not_modified,json=notModified,proto3" json:"not_modified,omitempty"`
	Attrs         *Attr                  `protobuf:"bytes,2,opt,name=attrs,proto3" json:"attrs,omitempty"` // unset when not_modified=true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrIfChangedReply) Reset() {
	*x = GetAttrIfChangedReply{}
	mi := &file_api_proto_fs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrIfChangedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrIfChangedReply) ProtoMessage() {}

func (x *GetAttrIfChangedReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrIfChangedReply.ProtoReflect.Descriptor instead.
func (*GetAttrIfChangedReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{7}
}

func (x *GetAttrIfChangedReply) GetNotModified() bool {
	if x != nil {
		return x.NotModified
	}
	return false
}

func (x *GetAttrIfChangedReply) GetAttrs() *Attr {
	if x != nil {
		return x.Attrs
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{8}
}

func (x *SubscribeRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

type SubscribeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          SubscribeEvent_Kind    `protobuf:"varint,1,opt,name=kind,proto3,enum=gmountie.SubscribeEvent_Kind" json:"kind,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	NewPath       string                 `protobuf:"bytes,3,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`           // RENAMED only
	NewVersion    uint64                 `protobuf:"varint,4,opt,name=new_version,json=newVersion,proto3" json:"new_version,omitempty"` // 0 for DELETED / HEARTBEAT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEvent) Reset() {
	*x = SubscribeEvent{}
	mi := &file_api_proto_fs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEvent) ProtoMessage() {}

func (x *SubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEvent.ProtoReflect.Descriptor instead.
func (*SubscribeEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{9}
}

func (x *SubscribeEvent) GetKind() SubscribeEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return SubscribeEvent_KIND_UNSPECIFIED
}

func (x *SubscribeEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SubscribeEvent) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *SubscribeEvent) GetNewVersion() uint64 {
	if x != nil {
		return x.NewVersion
	}
	return 0
}

type OpenDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDirRequest) Reset() {
	*x = OpenDirRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDirRequest) ProtoMessage() {}

func (x *OpenDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDirRequest.ProtoReflect.Descriptor instead.
func (*OpenDirRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{10}
}

func (x *OpenDirRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *OpenDirRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *OpenDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenDirReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDirReply) Reset() {
	*x = OpenDirReply{}
	mi := &file_api_proto_fs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDirReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDirReply) ProtoMessage() {}

func (x *OpenDirReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDirReply.ProtoReflect.Descriptor instead.
func (*OpenDirReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{11}
}

func (x *OpenDirReply) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *OpenDirReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UnlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkRequest) Reset() {
	*x = UnlinkRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkRequest) ProtoMessage() {}

func (x *UnlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkRequest.ProtoReflect.Descriptor instead.
func (*UnlinkRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{12}
}

func (x *UnlinkRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *UnlinkRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *UnlinkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UnlinkRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UnlinkRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type UnlinkReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkReply) Reset() {
	*x = UnlinkReply{}
	mi := &file_api_proto_fs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkReply) ProtoMessage() {}

func (x *UnlinkReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkReply.ProtoReflect.Descriptor instead.
func (*UnlinkReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{13}
}

func (x *UnlinkReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type AccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{14}
}

func (x *AccessRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *AccessRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *AccessRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AccessRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type AccessReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessReply) Reset() {
	*x = AccessReply{}
	mi := &file_api_proto_fs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessReply) ProtoMessage() {}

func (x *AccessReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessReply.ProtoReflect.Descriptor instead.
func (*AccessReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{15}
}

func (x *AccessReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TruncateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateRequest) Reset() {
	*x = TruncateRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateRequest) ProtoMessage() {}

func (x *TruncateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateRequest.ProtoReflect.Descriptor instead.
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{16}
}

func (x *TruncateRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *TruncateRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *TruncateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TruncateRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TruncateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TruncateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TruncateReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateReply) Reset() {
	*x = TruncateReply{}
	mi := &file_api_proto_fs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateReply) ProtoMessage() {}

func (x *TruncateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateReply.ProtoReflect.Descriptor instead.
func (*TruncateReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{17}
}

func (x *TruncateReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ChownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Uid           uint32                 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,5,opt,name=gid,proto3" json:"gid,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,7,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChownRequest) Reset() {
	*x = ChownRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChownRequest) ProtoMessage() {}

func (x *ChownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChownRequest.ProtoReflect.Descriptor instead.
func (*ChownRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{18}
}

func (x *ChownRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ChownRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *ChownRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChownRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChownRequest) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *ChownRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChownRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChownReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChownReply) Reset() {
	*x = ChownReply{}
	mi := &file_api_proto_fs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChownReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChownReply) ProtoMessage() {}

func (x *ChownReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChownReply.ProtoReflect.Descriptor instead.
func (*ChownReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{19}
}

func (x *ChownReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ChmodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodRequest) Reset() {
	*x = ChmodRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodRequest) ProtoMessage() {}

func (x *ChmodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodRequest.ProtoReflect.Descriptor instead.
func (*ChmodRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{20}
}

func (x *ChmodRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *ChmodRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *ChmodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChmodRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ChmodRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ChmodRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ChmodReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodReply) Reset() {
	*x = ChmodReply{}
	mi := &file_api_proto_fs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodReply) ProtoMessage() {}

func (x *ChmodReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodReply.ProtoReflect.Descriptor instead.
func (*ChmodReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{21}
}

func (x *ChmodReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{22}
}

func (x *MkdirRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *MkdirRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MkdirRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *MkdirRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MkdirReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirReply) Reset() {
	*x = MkdirReply{}
	mi := &file_api_proto_fs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirReply) ProtoMessage() {}

func (x *MkdirReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirReply.ProtoReflect.Descriptor instead.
func (*MkdirReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{23}
}

func (x *MkdirReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RmdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirRequest) Reset() {
	*x = RmdirRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirRequest) ProtoMessage() {}

func (x *RmdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirRequest.ProtoReflect.Descriptor instead.
func (*RmdirRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{24}
}

func (x *RmdirRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *RmdirRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *RmdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RmdirRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RmdirRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RmdirReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirReply) Reset() {
	*x = RmdirReply{}
	mi := &file_api_proto_fs_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirReply) ProtoMessage() {}

func (x *RmdirReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirReply.ProtoReflect.Descriptor instead.
func (*RmdirReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{25}
}

func (x *RmdirReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	OldName       string                 `protobuf:"bytes,3,opt,name=old_name,json=oldName,proto3" json:"old_name,omitempty"`
	NewName       string                 `protobuf:"bytes,4,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{26}
}

func (x *RenameRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *RenameRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *RenameRequest) GetOldName() string {
	if x != nil {
		return x.OldName
	}
	return ""
}

func (x *RenameRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

func (x *RenameRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RenameRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RenameReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameReply) Reset() {
	*x = RenameReply{}
	mi := &file_api_proto_fs_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameReply) ProtoMessage() {}

func (x *RenameReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameReply.ProtoReflect.Descriptor instead.
func (*RenameReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{27}
}

func (x *RenameReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetXAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volume        string                 `protobuf:"bytes,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Caller        *Caller                `protobuf:"bytes,2,opt,name=caller,proto3" json:"caller,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Attribute     string                 `protobuf:"bytes,4,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXAttrRequest) Reset() {
	*x = GetXAttrRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXAttrRequest) ProtoMessage() {}

func (x *GetXAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXAttrRequest.ProtoReflect.Descriptor instead.
func (*GetXAttrRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{28}
}

func (x *GetXAttrRequest) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *GetXAttrRequest) GetCaller() *Caller {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *GetXAttrRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetXAttrRequest) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

type GetXAttrReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetXAttrReply) Reset() {
	*x = GetXAttrReply{}
	mi := &file_api_proto_fs_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetXAttrReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetXAttrReply) ProtoMessage() {}

func (x *GetXAttrReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetXAttrReply.ProtoReflect.Descriptor instead.
func (*GetXAttrReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{29}
}

func (x *GetXAttrReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetXAttrReply) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// CompoundOp carries a single read-only metadata op inside a Compound batch.
// The set is intentionally limited to ops with no idempotency / session
// requirements (no request_id / session_id fields). Per NFSv4 Compound
// semantics, per-op errors do NOT abort the batch — see CompoundReply.
type CompoundOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*CompoundOp_GetAttr
	//	*CompoundOp_StatFs
	//	*CompoundOp_OpenDir
	//	*CompoundOp_Access
	//	*CompoundOp_GetXattr
	Op            isCompoundOp_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompoundOp) Reset() {
	*x = CompoundOp{}
	mi := &file_api_proto_fs_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompoundOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompoundOp) ProtoMessage() {}

func (x *CompoundOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompoundOp.ProtoReflect.Descriptor instead.
func (*CompoundOp) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{30}
}

func (x *CompoundOp) GetOp() isCompoundOp_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *CompoundOp) GetGetAttr() *GetAttrRequest {
	if x != nil {
		if x, ok := x.Op.(*CompoundOp_GetAttr); ok {
			return x.GetAttr
		}
	}
	return nil
}

func (x *CompoundOp) GetStatFs() *StatFsRequest {
	if x != nil {
		if x, ok := x.Op.(*CompoundOp_StatFs); ok {
			return x.StatFs
		}
	}
	return nil
}

func (x *CompoundOp) GetOpenDir() *OpenDirRequest {
	if x != nil {
		if x, ok := x.Op.(*CompoundOp_OpenDir); ok {
			return x.OpenDir
		}
	}
	return nil
}

func (x *CompoundOp) GetAccess() *AccessRequest {
	if x != nil {
		if x, ok := x.Op.(*CompoundOp_Access); ok {
			return x.Access
		}
	}
	return nil
}

func (x *CompoundOp) GetGetXattr() *GetXAttrRequest {
	if x != nil {
		if x, ok := x.Op.(*CompoundOp_GetXattr); ok {
			return x.GetXattr
		}
	}
	return nil
}

type isCompoundOp_Op interface {
	isCompoundOp_Op()
}

type CompoundOp_GetAttr struct {
	GetAttr *GetAttrRequest `protobuf:"bytes,1,opt,name=get_attr,json=getAttr,proto3,oneof"`
}

type CompoundOp_StatFs struct {
	StatFs *StatFsRequest `protobuf:"bytes,2,opt,name=stat_fs,json=statFs,proto3,oneof"`
}

type CompoundOp_OpenDir struct {
	OpenDir *OpenDirRequest `protobuf:"bytes,3,opt,name=open_dir,json=openDir,proto3,oneof"`
}

type CompoundOp_Access struct {
	Access *AccessRequest `protobuf:"bytes,4,opt,name=access,proto3,oneof"`
}

type CompoundOp_GetXattr struct {
	GetXattr *GetXAttrRequest `protobuf:"bytes,5,opt,name=get_xattr,json=getXattr,proto3,oneof"`
}

func (*CompoundOp_GetAttr) isCompoundOp_Op() {}

func (*CompoundOp_StatFs) isCompoundOp_Op() {}

func (*CompoundOp_OpenDir) isCompoundOp_Op() {}

func (*CompoundOp_Access) isCompoundOp_Op() {}

func (*CompoundOp_GetXattr) isCompoundOp_Op() {}

// CompoundReply is the per-op result inside a CompoundBatch. The variant
// matches the request op when it produced a typed reply; on a transport-class
// failure (e.g. unknown volume) the slot carries `status` (an int32 fuse
// status, errno-equivalent) so the batch shape stays N-in / N-out regardless
// of which sub-ops failed.
type CompoundReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Reply:
	//
	//	*CompoundReply_GetAttr
	//	*CompoundReply_StatFs
	//	*CompoundReply_OpenDir
	//	*CompoundReply_Access
	//	*CompoundReply_GetXattr
	//	*CompoundReply_Status
	Reply         isCompoundReply_Reply `protobuf_oneof:"reply"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompoundReply) Reset() {
	*x = CompoundReply{}
	mi := &file_api_proto_fs_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompoundReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompoundReply) ProtoMessage() {}

func (x *CompoundReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompoundReply.ProtoReflect.Descriptor instead.
func (*CompoundReply) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{31}
}

func (x *CompoundReply) GetReply() isCompoundReply_Reply {
	if x != nil {
		return x.Reply
	}
	return nil
}

func (x *CompoundReply) GetGetAttr() *GetAttrReply {
	if x != nil {
		if x, ok := x.Reply.(*CompoundReply_GetAttr); ok {
			return x.GetAttr
		}
	}
	return nil
}

func (x *CompoundReply) GetStatFs() *StatFsReply {
	if x != nil {
		if x, ok := x.Reply.(*CompoundReply_StatFs); ok {
			return x.StatFs
		}
	}
	return nil
}

func (x *CompoundReply) GetOpenDir() *OpenDirReply {
	if x != nil {
		if x, ok := x.Reply.(*CompoundReply_OpenDir); ok {
			return x.OpenDir
		}
	}
	return nil
}

func (x *CompoundReply) GetAccess() *AccessReply {
	if x != nil {
		if x, ok := x.Reply.(*CompoundReply_Access); ok {
			return x.Access
		}
	}
	return nil
}

func (x *CompoundReply) GetGetXattr() *GetXAttrReply {
	if x != nil {
		if x, ok := x.Reply.(*CompoundReply_GetXattr); ok {
			return x.GetXattr
		}
	}
	return nil
}

func (x *CompoundReply) GetStatus() int32 {
	if x != nil {
		if x, ok := x.Reply.(*CompoundReply_Status); ok {
			return x.Status
		}
	}
	return 0
}

type isCompoundReply_Reply interface {
	isCompoundReply_Reply()
}

type CompoundReply_GetAttr struct {
	GetAttr *GetAttrReply `protobuf:"bytes,1,opt,name=get_attr,json=getAttr,proto3,oneof"`
}

type CompoundReply_StatFs struct {
	StatFs *StatFsReply `protobuf:"bytes,2,opt,name=stat_fs,json=statFs,proto3,oneof"`
}

type CompoundReply_OpenDir struct {
	OpenDir *OpenDirReply `protobuf:"bytes,3,opt,name=open_dir,json=openDir,proto3,oneof"`
}

type CompoundReply_Access struct {
	Access *AccessReply `protobuf:"bytes,4,opt,name=access,proto3,oneof"`
}

type CompoundReply_GetXattr struct {
	GetXattr *GetXAttrReply `protobuf:"bytes,5,opt,name=get_xattr,json=getXattr,proto3,oneof"`
}

type CompoundReply_Status struct {
	Status int32 `protobuf:"varint,6,opt,name=status,proto3,oneof"`
}

func (*CompoundReply_GetAttr) isCompoundReply_Reply() {}

func (*CompoundReply_StatFs) isCompoundReply_Reply() {}

func (*CompoundReply_OpenDir) isCompoundReply_Reply() {}

func (*CompoundReply_Access) isCompoundReply_Reply() {}

func (*CompoundReply_GetXattr) isCompoundReply_Reply() {}

func (*CompoundReply_Status) isCompoundReply_Reply() {}

type CompoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*CompoundOp          `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompoundRequest) Reset() {
	*x = CompoundRequest{}
	mi := &file_api_proto_fs_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompoundRequest) ProtoMessage() {}

func (x *CompoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompoundRequest.ProtoReflect.Descriptor instead.
func (*CompoundRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{32}
}

func (x *CompoundRequest) GetOps() []*CompoundOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type CompoundBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replies       []*CompoundReply       `protobuf:"bytes,1,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompoundBatch) Reset() {
	*x = CompoundBatch{}
	mi := &file_api_proto_fs_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompoundBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompoundBatch) ProtoMessage() {}

func (x *CompoundBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_fs_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompoundBatch.ProtoReflect.Descriptor instead.
func (*CompoundBatch) Descriptor() ([]byte, []int) {
	return file_api_proto_fs_proto_rawDescGZIP(), []int{33}
}

func (x *CompoundBatch) GetReplies() []*CompoundReply {
	if x != nil {
		return x.Replies
	}
	return nil
}

var File_api_proto_fs_proto protoreflect.FileDescriptor

const file_api_proto_fs_proto_rawDesc = "" +
	"\n" +
	"\x12api/proto/fs.proto\x12\bgmountie\x1a\x16api/proto/common.proto\"V\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03ino\x18\x03 \x01(\x04R\x03ino\x12\x10\n" +
	"\x03off\x18\x04 \x01(\x04R\x03off\"\xb7\x03\n" +
	"\x04Attr\x12\x10\n" +
	"\x03ino\x18\x01 \x01(\x04R\x03ino\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x16\n" +
	"\x06blocks\x18\x03 \x01(\x04R\x06blocks\x12\x14\n" +
	"\x05atime\x18\x04 \x01(\x04R\x05atime\x12\x14\n" +
	"\x05mtime\x18\x05 \x01(\x04R\x05mtime\x12\x14\n" +
	"\x05ctime\x18\x06 \x01(\x04R\x05ctime\x12\x1c\n" +
	"\tatimensec\x18\a \x01(\rR\tatimensec\x12\x1c\n" +
	"\tmtimensec\x18\b \x01(\rR\tmtimensec\x12\x1c\n" +
	"\tctimensec\x18\t \x01(\rR\tctimensec\x12\x12\n" +
	"\x04mode\x18\n" +
	" \x01(\rR\x04mode\x12\x14\n" +
	"\x05nlink\x18\v \x01(\rR\x05nlink\x12%\n" +
	"\x05owner\x18\f \x01(\v2\x0f.gmountie.OwnerR\x05owner\x12\x10\n" +
	"\x03uid\x18\r \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x0e \x01(\rR\x03gid\x12\x12\n" +
	"\x04rdev\x18\x0f \x01(\rR\x04rdev\x12\x18\n" +
	"\ablksize\x18\x10 \x01(\rR\ablksize\x12\x18\n" +
	"\apadding\x18\x11 \x01(\rR\apadding\x12\x18\n" +
	"\aversion\x18\x12 \x01(\x04R\aversion\";\n" +
	"\rStatFsRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xfb\x01\n" +
	"\vStatFsReply\x12\x16\n" +
	"\x06blocks\x18\x01 \x01(\x04R\x06blocks\x12\x14\n" +
	"\x05bfree\x18\x02 \x01(\x04R\x05bfree\x12\x16\n" +
	"\x06bavail\x18\x03 \x01(\x04R\x06bavail\x12\x14\n" +
	"\x05files\x18\x04 \x01(\x04R\x05files\x12\x14\n" +
	"\x05ffree\x18\x05 \x01(\x04R\x05ffree\x12\x14\n" +
	"\x05bsize\x18\x06 \x01(\rR\x05bsize\x12\x18\n" +
	"\anamelen\x18\a \x01(\rR\anamelen\x12\x16\n" +
	"\x06frsize\x18\b \x01(\rR\x06frsize\x12\x18\n" +
	"\apadding\x18\t \x01(\rR\apadding\x12\x18\n" +
	"\x05spare\x18\n" +
	" \x03(\rB\x02\x10\x01R\x05spare\"f\n" +
	"\x0eGetAttrRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"V\n" +
	"\fGetAttrReply\x12.\n" +
	"\n" +
	"attributes\x18\x01 \x01(\v2\x0e.gmountie.AttrR\n" +
	"attributes\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"j\n" +
	"\x17GetAttrIfChangedRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12#\n" +
	"\rknown_version\x18\x03 \x01(\x04R\fknownVersion\"`\n" +
	"\x15GetAttrIfChangedReply\x12!\n" +
	"\fnot_modified\x18\x01 \x01(\bR\vnotModified\x12$\n" +
	"\x05attrs\x18\x02 \x01(\v2\x0e.gmountie.AttrR\x05attrs\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\"\xe7\x01\n" +
	"\x0eSubscribeEvent\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.gmountie.SubscribeEvent.KindR\x04kind\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\bnew_path\x18\x03 \x01(\tR\anewPath\x12\x1f\n" +
	"\vnew_version\x18\x04 \x01(\x04R\n" +
	"newVersion\"R\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aMUTATED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\v\n" +
	"\aRENAMED\x10\x03\x12\r\n" +
	"\tHEARTBEAT\x10\x04\"f\n" +
	"\x0eOpenDirRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\"T\n" +
	"\fOpenDirReply\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.gmountie.DirEntryR\aentries\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\xa3\x01\n" +
	"\rUnlinkRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"%\n" +
	"\vUnlinkReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"y\n" +
	"\rAccessRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\"%\n" +
	"\vAccessReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\xb9\x01\n" +
	"\x0fTruncateRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"'\n" +
	"\rTruncateReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\xc6\x01\n" +
	"\fChownRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x05 \x01(\rR\x03gid\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\a \x01(\tR\tsessionId\"$\n" +
	"\n" +
	"ChownReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\xb6\x01\n" +
	"\fChmodRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"$\n" +
	"\n" +
	"ChmodReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\xb6\x01\n" +
	"\fMkdirRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"$\n" +
	"\n" +
	"MkdirReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\xa2\x01\n" +
	"\fRmdirRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\"$\n" +
	"\n" +
	"RmdirReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\xc5\x01\n" +
	"\rRenameRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x19\n" +
	"\bold_name\x18\x03 \x01(\tR\aoldName\x12\x19\n" +
	"\bnew_name\x18\x04 \x01(\tR\anewName\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\"%\n" +
	"\vRenameReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\"\x85\x01\n" +
	"\x0fGetXAttrRequest\x12\x16\n" +
	"\x06volume\x18\x01 \x01(\tR\x06volume\x12(\n" +
	"\x06caller\x18\x02 \x01(\v2\x10.gmountie.CallerR\x06caller\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1c\n" +
	"\tattribute\x18\x04 \x01(\tR\tattribute\";\n" +
	"\rGetXAttrReply\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\xa1\x02\n" +
	"\n" +
	"CompoundOp\x125\n" +
	"\bget_attr\x18\x01 \x01(\v2\x18.gmountie.GetAttrRequestH\x00R\agetAttr\x122\n" +
	"\astat_fs\x18\x02 \x01(\v2\x17.gmountie.StatFsRequestH\x00R\x06statFs\x125\n" +
	"\bopen_dir\x18\x03 \x01(\v2\x18.gmountie.OpenDirRequestH\x00R\aopenDir\x121\n" +
	"\x06access\x18\x04 \x01(\v2\x17.gmountie.AccessRequestH\x00R\x06access\x128\n" +
	"\tget_xattr\x18\x05 \x01(\v2\x19.gmountie.GetXAttrRequestH\x00R\bgetXattrB\x04\n" +
	"\x02op\"\xb7\x02\n" +
	"\rCompoundReply\x123\n" +
	"\bget_attr\x18\x01 \x01(\v2\x16.gmountie.GetAttrReplyH\x00R\agetAttr\x120\n" +
	"\astat_fs\x18\x02 \x01(\v2\x15.gmountie.StatFsReplyH\x00R\x06statFs\x123\n" +
	"\bopen_dir\x18\x03 \x01(\v2\x16.gmountie.OpenDirReplyH\x00R\aopenDir\x12/\n" +
	"\x06access\x18\x04 \x01(\v2\x15.gmountie.AccessReplyH\x00R\x06access\x126\n" +
	"\tget_xattr\x18\x05 \x01(\v2\x17.gmountie.GetXAttrReplyH\x00R\bgetXattr\x12\x18\n" +
	"\x06status\x18\x06 \x01(\x05H\x00R\x06statusB\a\n" +
	"\x05reply\"9\n" +
	"\x0fCompoundRequest\x12&\n" +
	"\x03ops\x18\x01 \x03(\v2\x14.gmountie.CompoundOpR\x03ops\"B\n" +
	"\rCompoundBatch\x121\n" +
	"\areplies\x18\x01 \x03(\v2\x17.gmountie.CompoundReplyR\areplies2\xa2\a\n" +
	"\x05RpcFs\x12;\n" +
	"\aGetAttr\x12\x18.gmountie.GetAttrRequest\x1a\x16.gmountie.GetAttrReply\x128\n" +
	"\x06StatFs\x12\x17.gmountie.StatFsRequest\x1a\x15.gmountie.StatFsReply\x12;\n" +
	"\aOpenDir\x12\x18.gmountie.OpenDirRequest\x1a\x16.gmountie.OpenDirReply\x128\n" +
	"\x06Unlink\x12\x17.gmountie.UnlinkRequest\x1a\x15.gmountie.UnlinkReply\x128\n" +
	"\x06Access\x12\x17.gmountie.AccessRequest\x1a\x15.gmountie.AccessReply\x12>\n" +
	"\bTruncate\x12\x19.gmountie.TruncateRequest\x1a\x17.gmountie.TruncateReply\x125\n" +
	"\x05Chown\x12\x16.gmountie.ChownRequest\x1a\x14.gmountie.ChownReply\x125\n" +
	"\x05Chmod\x12\x16.gmountie.ChmodRequest\x1a\x14.gmountie.ChmodReply\x125\n" +
	"\x05Mkdir\x12\x16.gmountie.MkdirRequest\x1a\x14.gmountie.MkdirReply\x125\n" +
	"\x05Rmdir\x12\x16.gmountie.RmdirRequest\x1a\x14.gmountie.RmdirReply\x128\n" +
	"\x06Rename\x12\x17.gmountie.RenameRequest\x1a\x15.gmountie.RenameReply\x12>\n" +
	"\bGetXAttr\x12\x19.gmountie.GetXAttrRequest\x1a\x17.gmountie.GetXAttrReply\x12>\n" +
	"\bCompound\x12\x19.gmountie.CompoundRequest\x1a\x17.gmountie.CompoundBatch\x12V\n" +
	"\x10GetAttrIfChanged\x12!.gmountie.GetAttrIfChangedRequest\x1a\x1f.gmountie.GetAttrIfChangedReply\x12C\n" +
	"\tSubscribe\x12\x1a.gmountie.SubscribeRequest\x1a\x18.gmountie.SubscribeEvent0\x01B\vZ\tpkg/protob\x06proto3"

var (
	file_api_proto_fs_proto_rawDescOnce sync.Once
	file_api_proto_fs_proto_rawDescData []byte
)

func file_api_proto_fs_proto_rawDescGZIP() []byte {
	file_api_proto_fs_proto_rawDescOnce.Do(func() {
		file_api_proto_fs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_fs_proto_rawDesc), len(file_api_proto_fs_proto_rawDesc)))
	})
	return file_api_proto_fs_proto_rawDescData
}

var file_api_proto_fs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_fs_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_proto_fs_proto_goTypes = []any{
	(SubscribeEvent_Kind)(0),        // 0: gmountie.SubscribeEvent.Kind
	(*DirEntry)(nil),                // 1: gmountie.DirEntry
	(*Attr)(nil),                    // 2: gmountie.Attr
	(*StatFsRequest)(nil),           // 3: gmountie.StatFsRequest
	(*StatFsReply)(nil),             // 4: gmountie.StatFsReply
	(*GetAttrRequest)(nil),          // 5: gmountie.GetAttrRequest
	(*GetAttrReply)(nil),            // 6: gmountie.GetAttrReply
	(*GetAttrIfChangedRequest)(nil), // 7: gmountie.GetAttrIfChangedRequest
	(*GetAttrIfChangedReply)(nil),   // 8: gmountie.GetAttrIfChangedReply
	(*SubscribeRequest)(nil),        // 9: gmountie.SubscribeRequest
	(*SubscribeEvent)(nil),          // 10: gmountie.SubscribeEvent
	(*OpenDirRequest)(nil),          // 11: gmountie.OpenDirRequest
	(*OpenDirReply)(nil),            // 12: gmountie.OpenDirReply
	(*UnlinkRequest)(nil),           // 13: gmountie.UnlinkRequest
	(*UnlinkReply)(nil),             // 14: gmountie.UnlinkReply
	(*AccessRequest)(nil),           // 15: gmountie.AccessRequest
	(*AccessReply)(nil),             // 16: gmountie.AccessReply
	(*TruncateRequest)(nil),         // 17: gmountie.TruncateRequest
	(*TruncateReply)(nil),           // 18: gmountie.TruncateReply
	(*ChownRequest)(nil),            // 19: gmountie.ChownRequest
	(*ChownReply)(nil),              // 20: gmountie.ChownReply
	(*ChmodRequest)(nil),            // 21: gmountie.ChmodRequest
	(*ChmodReply)(nil),              // 22: gmountie.ChmodReply
	(*MkdirRequest)(nil),            // 23: gmountie.MkdirRequest
	(*MkdirReply)(nil),              // 24: gmountie.MkdirReply
	(*RmdirRequest)(nil),            // 25: gmountie.RmdirRequest
	(*RmdirReply)(nil),              // 26: gmountie.RmdirReply
	(*RenameRequest)(nil),           // 27: gmountie.RenameRequest
	(*RenameReply)(nil),             // 28: gmountie.RenameReply
	(*GetXAttrRequest)(nil),         // 29: gmountie.GetXAttrRequest
	(*GetXAttrReply)(nil),           // 30: gmountie.GetXAttrReply
	(*CompoundOp)(nil),              // 31: gmountie.CompoundOp
	(*CompoundReply)(nil),           // 32: gmountie.CompoundReply
	(*CompoundRequest)(nil),         // 33: gmountie.CompoundRequest
	(*CompoundBatch)(nil),           // 34: gmountie.CompoundBatch
	(*Owner)(nil),                   // 35: gmountie.Owner
	(*Caller)(nil),                  // 36: gmountie.Caller
}
var file_api_proto_fs_proto_depIdxs = []int32{
	35, // 0: gmountie.Attr.owner:type_name -> gmountie.Owner
	36, // 1: gmountie.GetAttrRequest.caller:type_name -> gmountie.Caller
	2,  // 2: gmountie.GetAttrReply.attributes:type_name -> gmountie.Attr
	2,  // 3: gmountie.GetAttrIfChangedReply.attrs:type_name -> gmountie.Attr
	0,  // 4: gmountie.SubscribeEvent.kind:type_name -> gmountie.SubscribeEvent.Kind
	36, // 5: gmountie.OpenDirRequest.caller:type_name -> gmountie.Caller
	1,  // 6: gmountie.OpenDirReply.entries:type_name -> gmountie.DirEntry
	36, // 7: gmountie.UnlinkRequest.caller:type_name -> gmountie.Caller
	36, // 8: gmountie.AccessRequest.caller:type_name -> gmountie.Caller
	36, // 9: gmountie.TruncateRequest.caller:type_name -> gmountie.Caller
	36, // 10: gmountie.ChownRequest.caller:type_name -> gmountie.Caller
	36, // 11: gmountie.ChmodRequest.caller:type_name -> gmountie.Caller
	36, // 12: gmountie.MkdirRequest.caller:type_name -> gmountie.Caller
	36, // 13: gmountie.RmdirRequest.caller:type_name -> gmountie.Caller
	36, // 14: gmountie.RenameRequest.caller:type_name -> gmountie.Caller
	36, // 15: gmountie.GetXAttrRequest.caller:type_name -> gmountie.Caller
	5,  // 16: gmountie.CompoundOp.get_attr:type_name -> gmountie.GetAttrRequest
	3,  // 17: gmountie.CompoundOp.stat_fs:type_name -> gmountie.StatFsRequest
	11, // 18: gmountie.CompoundOp.open_dir:type_name -> gmountie.OpenDirRequest
	15, // 19: gmountie.CompoundOp.access:type_name -> gmountie.AccessRequest
	29, // 20: gmountie.CompoundOp.get_xattr:type_name -> gmountie.GetXAttrRequest
	6,  // 21: gmountie.CompoundReply.get_attr:type_name -> gmountie.GetAttrReply
	4,  // 22: gmountie.CompoundReply.stat_fs:type_name -> gmountie.StatFsReply
	12, // 23: gmountie.CompoundReply.open_dir:type_name -> gmountie.OpenDirReply
	16, // 24: gmountie.CompoundReply.access:type_name -> gmountie.AccessReply
	30, // 25: gmountie.CompoundReply.get_xattr:type_name -> gmountie.GetXAttrReply
	31, // 26: gmountie.CompoundRequest.ops:type_name -> gmountie.CompoundOp
	32, // 27: gmountie.CompoundBatch.replies:type_name -> gmountie.CompoundReply
	5,  // 28: gmountie.RpcFs.GetAttr:input_type -> gmountie.GetAttrRequest
	3,  // 29: gmountie.RpcFs.StatFs:input_type -> gmountie.StatFsRequest
	11, // 30: gmountie.RpcFs.OpenDir:input_type -> gmountie.OpenDirRequest
	13, // 31: gmountie.RpcFs.Unlink:input_type -> gmountie.UnlinkRequest
	15, // 32: gmountie.RpcFs.Access:input_type -> gmountie.AccessRequest
	17, // 33: gmountie.RpcFs.Truncate:input_type -> gmountie.TruncateRequest
	19, // 34: gmountie.RpcFs.Chown:input_type -> gmountie.ChownRequest
	21, // 35: gmountie.RpcFs.Chmod:input_type -> gmountie.ChmodRequest
	23, // 36: gmountie.RpcFs.Mkdir:input_type -> gmountie.MkdirRequest
	25, // 37: gmountie.RpcFs.Rmdir:input_type -> gmountie.RmdirRequest
	27, // 38: gmountie.RpcFs.Rename:input_type -> gmountie.RenameRequest
	29, // 39: gmountie.RpcFs.GetXAttr:input_type -> gmountie.GetXAttrRequest
	33, // 40: gmountie.RpcFs.Compound:input_type -> gmountie.CompoundRequest
	7,  // 41: gmountie.RpcFs.GetAttrIfChanged:input_type -> gmountie.GetAttrIfChangedRequest
	9,  // 42: gmountie.RpcFs.Subscribe:input_type -> gmountie.SubscribeRequest
	6,  // 43: gmountie.RpcFs.GetAttr:output_type -> gmountie.GetAttrReply
	4,  // 44: gmountie.RpcFs.StatFs:output_type -> gmountie.StatFsReply
	12, // 45: gmountie.RpcFs.OpenDir:output_type -> gmountie.OpenDirReply
	14, // 46: gmountie.RpcFs.Unlink:output_type -> gmountie.UnlinkReply
	16, // 47: gmountie.RpcFs.Access:output_type -> gmountie.AccessReply
	18, // 48: gmountie.RpcFs.Truncate:output_type -> gmountie.TruncateReply
	20, // 49: gmountie.RpcFs.Chown:output_type -> gmountie.ChownReply
	22, // 50: gmountie.RpcFs.Chmod:output_type -> gmountie.ChmodReply
	24, // 51: gmountie.RpcFs.Mkdir:output_type -> gmountie.MkdirReply
	26, // 52: gmountie.RpcFs.Rmdir:output_type -> gmountie.RmdirReply
	28, // 53: gmountie.RpcFs.Rename:output_type -> gmountie.RenameReply
	30, // 54: gmountie.RpcFs.GetXAttr:output_type -> gmountie.GetXAttrReply
	34, // 55: gmountie.RpcFs.Compound:output_type -> gmountie.CompoundBatch
	8,  // 56: gmountie.RpcFs.GetAttrIfChanged:output_type -> gmountie.GetAttrIfChangedReply
	10, // 57: gmountie.RpcFs.Subscribe:output_type -> gmountie.SubscribeEvent
	43, // [43:58] is the sub-list for method output_type
	28, // [28:43] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_api_proto_fs_proto_init() }
func file_api_proto_fs_proto_init() {
	if File_api_proto_fs_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	file_api_proto_fs_proto_msgTypes[30].OneofWrappers = []any{
		(*CompoundOp_GetAttr)(nil),
		(*CompoundOp_StatFs)(nil),
		(*CompoundOp_OpenDir)(nil),
		(*CompoundOp_Access)(nil),
		(*CompoundOp_GetXattr)(nil),
	}
	file_api_proto_fs_proto_msgTypes[31].OneofWrappers = []any{
		(*CompoundReply_GetAttr)(nil),
		(*CompoundReply_StatFs)(nil),
		(*CompoundReply_OpenDir)(nil),
		(*CompoundReply_Access)(nil),
		(*CompoundReply_GetXattr)(nil),
		(*CompoundReply_Status)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_fs_proto_rawDesc), len(file_api_proto_fs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_fs_proto_goTypes,
		DependencyIndexes: file_api_proto_fs_proto_depIdxs,
		EnumInfos:         file_api_proto_fs_proto_enumTypes,
		MessageInfos:      file_api_proto_fs_proto_msgTypes,
	}.Build()
	File_api_proto_fs_proto = out.File
	file_api_proto_fs_proto_goTypes = nil
	file_api_proto_fs_proto_depIdxs = nil
}
