// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: api/proto/fs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RpcFs_GetAttr_FullMethodName          = "/gmountie.RpcFs/GetAttr"
	RpcFs_StatFs_FullMethodName           = "/gmountie.RpcFs/StatFs"
	RpcFs_OpenDir_FullMethodName          = "/gmountie.RpcFs/OpenDir"
	RpcFs_Unlink_FullMethodName           = "/gmountie.RpcFs/Unlink"
	RpcFs_Access_FullMethodName           = "/gmountie.RpcFs/Access"
	RpcFs_Truncate_FullMethodName         = "/gmountie.RpcFs/Truncate"
	RpcFs_Chown_FullMethodName            = "/gmountie.RpcFs/Chown"
	RpcFs_Chmod_FullMethodName            = "/gmountie.RpcFs/Chmod"
	RpcFs_Utimens_FullMethodName          = "/gmountie.RpcFs/Utimens"
	RpcFs_Mkdir_FullMethodName            = "/gmountie.RpcFs/Mkdir"
	RpcFs_Rmdir_FullMethodName            = "/gmountie.RpcFs/Rmdir"
	RpcFs_Rename_FullMethodName           = "/gmountie.RpcFs/Rename"
	RpcFs_GetXAttr_FullMethodName         = "/gmountie.RpcFs/GetXAttr"
	RpcFs_Compound_FullMethodName         = "/gmountie.RpcFs/Compound"
	RpcFs_GetAttrIfChanged_FullMethodName = "/gmountie.RpcFs/GetAttrIfChanged"
	RpcFs_Subscribe_FullMethodName        = "/gmountie.RpcFs/Subscribe"
)

// RpcFsClient is the client API for RpcFs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcFsClient interface {
	GetAttr(ctx context.Context, in *GetAttrRequest, opts ...grpc.CallOption) (*GetAttrReply, error)
	StatFs(ctx context.Context, in *StatFsRequest, opts ...grpc.CallOption) (*StatFsReply, error)
	OpenDir(ctx context.Context, in *OpenDirRequest, opts ...grpc.CallOption) (*OpenDirReply, error)
	Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*UnlinkReply, error)
	Access(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessReply, error)
	Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateReply, error)
	Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*ChownReply, error)
	Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*ChmodReply, error)
	Utimens(ctx context.Context, in *UtimensRequest, opts ...grpc.CallOption) (*UtimensReply, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirReply, error)
	Rmdir(ctx context.Context, in *RmdirRequest, opts ...grpc.CallOption) (*RmdirReply, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameReply, error)
	GetXAttr(ctx context.Context, in *GetXAttrRequest, opts ...grpc.CallOption) (*GetXAttrReply, error)
	Compound(ctx context.Context, in *CompoundRequest, opts ...grpc.CallOption) (*CompoundBatch, error)
	GetAttrIfChanged(ctx context.Context, in *GetAttrIfChangedRequest, opts ...grpc.CallOption) (*GetAttrIfChangedReply, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEvent], error)
}

type rpcFsClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcFsClient(cc grpc.ClientConnInterface) RpcFsClient {
	return &rpcFsClient{cc}
}

func (c *rpcFsClient) GetAttr(ctx context.Context, in *GetAttrRequest, opts ...grpc.CallOption) (*GetAttrReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttrReply)
	err := c.cc.Invoke(ctx, RpcFs_GetAttr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) StatFs(ctx context.Context, in *StatFsRequest, opts ...grpc.CallOption) (*StatFsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatFsReply)
	err := c.cc.Invoke(ctx, RpcFs_StatFs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) OpenDir(ctx context.Context, in *OpenDirRequest, opts ...grpc.CallOption) (*OpenDirReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenDirReply)
	err := c.cc.Invoke(ctx, RpcFs_OpenDir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*UnlinkReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlinkReply)
	err := c.cc.Invoke(ctx, RpcFs_Unlink_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Access(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*AccessReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessReply)
	err := c.cc.Invoke(ctx, RpcFs_Access_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*TruncateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TruncateReply)
	err := c.cc.Invoke(ctx, RpcFs_Truncate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Chown(ctx context.Context, in *ChownRequest, opts ...grpc.CallOption) (*ChownReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChownReply)
	err := c.cc.Invoke(ctx, RpcFs_Chown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*ChmodReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChmodReply)
	err := c.cc.Invoke(ctx, RpcFs_Chmod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Utimens(ctx context.Context, in *UtimensRequest, opts ...grpc.CallOption) (*UtimensReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UtimensReply)
	err := c.cc.Invoke(ctx, RpcFs_Utimens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*MkdirReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MkdirReply)
	err := c.cc.Invoke(ctx, RpcFs_Mkdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Rmdir(ctx context.Context, in *RmdirRequest, opts ...grpc.CallOption) (*RmdirReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RmdirReply)
	err := c.cc.Invoke(ctx, RpcFs_Rmdir_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameReply)
	err := c.cc.Invoke(ctx, RpcFs_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) GetXAttr(ctx context.Context, in *GetXAttrRequest, opts ...grpc.CallOption) (*GetXAttrReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetXAttrReply)
	err := c.cc.Invoke(ctx, RpcFs_GetXAttr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Compound(ctx context.Context, in *CompoundRequest, opts ...grpc.CallOption) (*CompoundBatch, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompoundBatch)
	err := c.cc.Invoke(ctx, RpcFs_Compound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) GetAttrIfChanged(ctx context.Context, in *GetAttrIfChangedRequest, opts ...grpc.CallOption) (*GetAttrIfChangedReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttrIfChangedReply)
	err := c.cc.Invoke(ctx, RpcFs_GetAttrIfChanged_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcFsClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RpcFs_ServiceDesc.Streams[0], RpcFs_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcFs_SubscribeClient = grpc.ServerStreamingClient[SubscribeEvent]

// RpcFsServer is the server API for RpcFs service.
// All implementations must embed UnimplementedRpcFsServer
// for forward compatibility.
type RpcFsServer interface {
	GetAttr(context.Context, *GetAttrRequest) (*GetAttrReply, error)
	StatFs(context.Context, *StatFsRequest) (*StatFsReply, error)
	OpenDir(context.Context, *OpenDirRequest) (*OpenDirReply, error)
	Unlink(context.Context, *UnlinkRequest) (*UnlinkReply, error)
	Access(context.Context, *AccessRequest) (*AccessReply, error)
	Truncate(context.Context, *TruncateRequest) (*TruncateReply, error)
	Chown(context.Context, *ChownRequest) (*ChownReply, error)
	Chmod(context.Context, *ChmodRequest) (*ChmodReply, error)
	Utimens(context.Context, *UtimensRequest) (*UtimensReply, error)
	Mkdir(context.Context, *MkdirRequest) (*MkdirReply, error)
	Rmdir(context.Context, *RmdirRequest) (*RmdirReply, error)
	Rename(context.Context, *RenameRequest) (*RenameReply, error)
	GetXAttr(context.Context, *GetXAttrRequest) (*GetXAttrReply, error)
	Compound(context.Context, *CompoundRequest) (*CompoundBatch, error)
	GetAttrIfChanged(context.Context, *GetAttrIfChangedRequest) (*GetAttrIfChangedReply, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeEvent]) error
	mustEmbedUnimplementedRpcFsServer()
}

// UnimplementedRpcFsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRpcFsServer struct{}

func (UnimplementedRpcFsServer) GetAttr(context.Context, *GetAttrRequest) (*GetAttrReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttr not implemented")
}
func (UnimplementedRpcFsServer) StatFs(context.Context, *StatFsRequest) (*StatFsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method StatFs not implemented")
}
func (UnimplementedRpcFsServer) OpenDir(context.Context, *OpenDirRequest) (*OpenDirReply, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenDir not implemented")
}
func (UnimplementedRpcFsServer) Unlink(context.Context, *UnlinkRequest) (*UnlinkReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlink not implemented")
}
func (UnimplementedRpcFsServer) Access(context.Context, *AccessRequest) (*AccessReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Access not implemented")
}
func (UnimplementedRpcFsServer) Truncate(context.Context, *TruncateRequest) (*TruncateReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Truncate not implemented")
}
func (UnimplementedRpcFsServer) Chown(context.Context, *ChownRequest) (*ChownReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Chown not implemented")
}
func (UnimplementedRpcFsServer) Chmod(context.Context, *ChmodRequest) (*ChmodReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Chmod not implemented")
}
func (UnimplementedRpcFsServer) Utimens(context.Context, *UtimensRequest) (*UtimensReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Utimens not implemented")
}
func (UnimplementedRpcFsServer) Mkdir(context.Context, *MkdirRequest) (*MkdirReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Mkdir not implemented")
}
func (UnimplementedRpcFsServer) Rmdir(context.Context, *RmdirRequest) (*RmdirReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Rmdir not implemented")
}
func (UnimplementedRpcFsServer) Rename(context.Context, *RenameRequest) (*RenameReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedRpcFsServer) GetXAttr(context.Context, *GetXAttrRequest) (*GetXAttrReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetXAttr not implemented")
}
func (UnimplementedRpcFsServer) Compound(context.Context, *CompoundRequest) (*CompoundBatch, error) {
	return nil, status.Error(codes.Unimplemented, "method Compound not implemented")
}
func (UnimplementedRpcFsServer) GetAttrIfChanged(context.Context, *GetAttrIfChangedRequest) (*GetAttrIfChangedReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttrIfChanged not implemented")
}
func (UnimplementedRpcFsServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedRpcFsServer) mustEmbedUnimplementedRpcFsServer() {}
func (UnimplementedRpcFsServer) testEmbeddedByValue()               {}

// UnsafeRpcFsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcFsServer will
// result in compilation errors.
type UnsafeRpcFsServer interface {
	mustEmbedUnimplementedRpcFsServer()
}

func RegisterRpcFsServer(s grpc.ServiceRegistrar, srv RpcFsServer) {
	// If the following call panics, it indicates UnimplementedRpcFsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RpcFs_ServiceDesc, srv)
}

func _RpcFs_GetAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).GetAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_GetAttr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).GetAttr(ctx, req.(*GetAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_StatFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatFsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).StatFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_StatFs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).StatFs(ctx, req.(*StatFsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_OpenDir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).OpenDir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_OpenDir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).OpenDir(ctx, req.(*OpenDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Unlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Unlink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Unlink_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Unlink(ctx, req.(*UnlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Access_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Access(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Access_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Access(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Truncate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TruncateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Truncate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Truncate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Truncate(ctx, req.(*TruncateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Chown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Chown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Chown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Chown(ctx, req.(*ChownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Chmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChmodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Chmod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Chmod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Chmod(ctx, req.(*ChmodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Utimens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UtimensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Utimens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Utimens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Utimens(ctx, req.(*UtimensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Mkdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Mkdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Mkdir(ctx, req.(*MkdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Rmdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RmdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Rmdir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Rmdir_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Rmdir(ctx, req.(*RmdirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_GetXAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetXAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).GetXAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_GetXAttr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).GetXAttr(ctx, req.(*GetXAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Compound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompoundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).Compound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_Compound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).Compound(ctx, req.(*CompoundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_GetAttrIfChanged_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttrIfChangedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcFsServer).GetAttrIfChanged(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RpcFs_GetAttrIfChanged_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcFsServer).GetAttrIfChanged(ctx, req.(*GetAttrIfChangedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcFs_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RpcFsServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RpcFs_SubscribeServer = grpc.ServerStreamingServer[SubscribeEvent]

// RpcFs_ServiceDesc is the grpc.ServiceDesc for RpcFs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcFs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gmountie.RpcFs",
	HandlerType: (*RpcFsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAttr",
			Handler:    _RpcFs_GetAttr_Handler,
		},
		{
			MethodName: "StatFs",
			Handler:    _RpcFs_StatFs_Handler,
		},
		{
			MethodName: "OpenDir",
			Handler:    _RpcFs_OpenDir_Handler,
		},
		{
			MethodName: "Unlink",
			Handler:    _RpcFs_Unlink_Handler,
		},
		{
			MethodName: "Access",
			Handler:    _RpcFs_Access_Handler,
		},
		{
			MethodName: "Truncate",
			Handler:    _RpcFs_Truncate_Handler,
		},
		{
			MethodName: "Chown",
			Handler:    _RpcFs_Chown_Handler,
		},
		{
			MethodName: "Chmod",
			Handler:    _RpcFs_Chmod_Handler,
		},
		{
			MethodName: "Utimens",
			Handler:    _RpcFs_Utimens_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _RpcFs_Mkdir_Handler,
		},
		{
			MethodName: "Rmdir",
			Handler:    _RpcFs_Rmdir_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _RpcFs_Rename_Handler,
		},
		{
			MethodName: "GetXAttr",
			Handler:    _RpcFs_GetXAttr_Handler,
		},
		{
			MethodName: "Compound",
			Handler:    _RpcFs_Compound_Handler,
		},
		{
			MethodName: "GetAttrIfChanged",
			Handler:    _RpcFs_GetAttrIfChanged_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _RpcFs_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/proto/fs.proto",
}
