// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/volume.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_api_proto_volume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_volume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_api_proto_volume_proto_rawDescGZIP(), []int{0}
}

func (x *Volume) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type VolumeListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeListRequest) Reset() {
	*x = VolumeListRequest{}
	mi := &file_api_proto_volume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeListRequest) ProtoMessage() {}

func (x *VolumeListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_volume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeListRequest.ProtoReflect.Descriptor instead.
func (*VolumeListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_volume_proto_rawDescGZIP(), []int{1}
}

type VolumeListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Volumes       []*Volume              `protobuf:"bytes,1,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeListReply) Reset() {
	*x = VolumeListReply{}
	mi := &file_api_proto_volume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeListReply) ProtoMessage() {}

func (x *VolumeListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_volume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeListReply.ProtoReflect.Descriptor instead.
func (*VolumeListReply) Descriptor() ([]byte, []int) {
	return file_api_proto_volume_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeListReply) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

var File_api_proto_volume_proto protoreflect.FileDescriptor

const file_api_proto_volume_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/volume.proto\x12\bgmountie\"\x1c\n" +
	"\x06Volume\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x13\n" +
	"\x11VolumeListRequest\"=\n" +
	"\x0fVolumeListReply\x12*\n" +
	"\avolumes\x18\x01 \x03(\v2\x10.gmountie.VolumeR\avolumes2O\n" +
	"\rVolumeService\x12>\n" +
	"\x04List\x12\x1b.gmountie.VolumeListRequest\x1a\x19.gmountie.VolumeListReplyB\vZ\tpkg/protob\x06proto3"

var (
	file_api_proto_volume_proto_rawDescOnce sync.Once
	file_api_proto_volume_proto_rawDescData []byte
)

func file_api_proto_volume_proto_rawDescGZIP() []byte {
	file_api_proto_volume_proto_rawDescOnce.Do(func() {
		file_api_proto_volume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_volume_proto_rawDesc), len(file_api_proto_volume_proto_rawDesc)))
	})
	return file_api_proto_volume_proto_rawDescData
}

var file_api_proto_volume_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_volume_proto_goTypes = []any{
	(*Volume)(nil),            // 0: gmountie.Volume
	(*VolumeListRequest)(nil), // 1: gmountie.VolumeListRequest
	(*VolumeListReply)(nil),   // 2: gmountie.VolumeListReply
}
var file_api_proto_volume_proto_depIdxs = []int32{
	0, // 0: gmountie.VolumeListReply.volumes:type_name -> gmountie.Volume
	1, // 1: gmountie.VolumeService.List:input_type -> gmountie.VolumeListRequest
	2, // 2: gmountie.VolumeService.List:output_type -> gmountie.VolumeListReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_volume_proto_init() }
func file_api_proto_volume_proto_init() {
	if File_api_proto_volume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_volume_proto_rawDesc), len(file_api_proto_volume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_volume_proto_goTypes,
		DependencyIndexes: file_api_proto_volume_proto_depIdxs,
		MessageInfos:      file_api_proto_volume_proto_msgTypes,
	}.Build()
	File_api_proto_volume_proto = out.File
	file_api_proto_volume_proto_goTypes = nil
	file_api_proto_volume_proto_depIdxs = nil
}
